import { themes, structural, densities, type ColorTokens } from './tokens.ts';

export function kebab(key: string): string {
  return key.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/([a-zA-Z])(\d)/g, '$1-$2').toLowerCase();
}

function colorDecls(t: ColorTokens): string {
  return (Object.entries(t) as Array<[string, string | number]>).map(([k, v]) => `  --${kebab(k)}: ${v};`).join('\n');
}

function densityDecls(d: (typeof densities)[keyof typeof densities]): string {
  return [
    `  --row-pad-y: ${d.rowPadY};`, `  --row-pad-x: ${d.rowPadX};`, `  --row-gap: ${d.rowGap};`,
    `  --group-gap: ${d.groupGap};`, `  --avatar-size: ${d.avatar};`, `  --line-height: ${d.lineHeight};`,
  ].join('\n');
}

function structuralDecls(): string {
  const s = structural;
  const lines = [
    `  --font-mono: ${s.font.mono};`, `  --font-serif-italic: ${s.font.serifItalic};`,
    ...Object.entries(s.text).map(([k, v]) => `  --text-${k}: ${v};`),
    ...Object.entries(s.weight).map(([k, v]) => `  --weight-${k}: ${v};`),
    `  --label-tracking: ${s.labelTracking};`,
    ...Object.entries(s.radius).map(([k, v]) => `  --r-${k}: ${v};`),
    ...Object.entries(s.opacity).map(([k, v]) => `  --opacity-${k}: ${v};`),
    `  --shadow-1: ${s.shadow.s1};`, `  --shadow-2: ${s.shadow.s2};`,
    ...Object.entries(s.layout).map(([k, v]) => `  --${kebab(k)}: ${v};`),
    `  --focus-ring: ${s.focusRing};`,
    `  --duration-fast: ${s.motion.fast};`, `  --duration-normal: ${s.motion.normal};`, `  --duration-slow: ${s.motion.slow};`,
    `  --ease-out: ${s.motion.easeOut};`, `  --duration-toast: ${s.motion.toast};`, `  --duration-pulse: ${s.motion.pulse};`,
    `  --duration-caret: ${s.motion.caret};`, `  --duration-flash: ${s.motion.flash};`, `  --duration-meter: ${s.motion.meter};`,
  ];
  return lines.join('\n');
}

export function renderCss(): string {
  const reduced = ['fast', 'normal', 'slow', 'toast', 'pulse', 'caret', 'flash'].map(k => `    --duration-${k}: 0ms;`).join('\n');
  return [
    '/* Generated by packages/design-tokens (npm run build). Do not edit. */',
    `:root {\n${colorDecls(themes.mesh)}\n${structuralDecls()}\n${densityDecls(densities.regular)}\n  color-scheme: dark;\n}`,
    `[data-theme="mesh"] {\n${colorDecls(themes.mesh)}\n  color-scheme: dark;\n}`,
    `[data-theme="light"] {\n${colorDecls(themes.light)}\n  color-scheme: light;\n}`,
    `[data-theme="high-contrast"] {\n${colorDecls(themes['high-contrast'])}\n  color-scheme: dark;\n}`,
    `@media (prefers-color-scheme: light) {\n  :root:not([data-theme]) {\n${colorDecls(themes.light).replace(/^/gm, '  ')}\n    color-scheme: light;\n  }\n}`,
    `[data-density="compact"] {\n${densityDecls(densities.compact)}\n}`,
    `[data-density="regular"] {\n${densityDecls(densities.regular)}\n}`,
    `[data-density="cozy"] {\n${densityDecls(densities.cozy)}\n}`,
    `@media (prefers-reduced-motion: reduce) {\n  :root {\n${reduced}\n  }\n}`,
    '',
  ].join('\n\n');
}
