// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package pgdb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
DELETE FROM login_attempts WHERE user_id = $1 AND ok = 0
`

type ClearLoginFailuresParams struct {
	UserID *id.ID
}

func (q *Queries) ClearLoginFailures(ctx context.Context, arg ClearLoginFailuresParams) error {
	_, err := q.db.ExecContext(ctx, clearLoginFailures, arg.UserID)
	return err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
UPDATE recovery_codes SET used_at = $1 WHERE user_id = $2 AND code_hash = $3 AND used_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	UsedAt   sql.NullInt64
	UserID   id.ID
	CodeHash []byte
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeRecoveryCode, arg.UsedAt, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeTOTPCounter = `-- name: ConsumeTOTPCounter :execrows
UPDATE totp_secrets SET last_counter = $1 WHERE user_id = $2 AND last_counter < $3
`

type ConsumeTOTPCounterParams struct {
	LastCounter   int64
	UserID        id.ID
	LastCounter_2 int64
}

func (q *Queries) ConsumeTOTPCounter(ctx context.Context, arg ConsumeTOTPCounterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeTOTPCounter, arg.LastCounter, arg.UserID, arg.LastCounter_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countLoginFailures = `-- name: CountLoginFailures :one
SELECT count(*) FROM login_attempts WHERE user_id = $1 AND ok = 0 AND at >= $2
`

type CountLoginFailuresParams struct {
	UserID *id.ID
	At     int64
}

func (q *Queries) CountLoginFailures(ctx context.Context, arg CountLoginFailuresParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoginFailures, arg.UserID, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecoveryCodes = `-- name: CountRecoveryCodes :one
SELECT count(*) FROM recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

type CountRecoveryCodesParams struct {
	UserID id.ID
}

func (q *Queries) CountRecoveryCodes(ctx context.Context, arg CountRecoveryCodesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecoveryCodes, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCeremony = `-- name: DeleteCeremony :execrows
DELETE FROM webauthn_ceremonies WHERE id = $1
`

type DeleteCeremonyParams struct {
	ID id.ID
}

func (q *Queries) DeleteCeremony(ctx context.Context, arg DeleteCeremonyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCeremony, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

type DeleteRecoveryCodesParams struct {
	UserID id.ID
}

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, arg DeleteRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, arg.UserID)
	return err
}

const getCeremony = `-- name: GetCeremony :one
SELECT id, kind, user_id, session_json, created, expires FROM webauthn_ceremonies WHERE id = $1 AND expires > $2
`

type GetCeremonyParams struct {
	ID      id.ID
	Expires int64
}

func (q *Queries) GetCeremony(ctx context.Context, arg GetCeremonyParams) (WebauthnCeremonies, error) {
	row := q.db.QueryRowContext(ctx, getCeremony, arg.ID, arg.Expires)
	var i WebauthnCeremonies
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.SessionJson,
		&i.Created,
		&i.Expires,
	)
	return i, err
}

const getOIDCIdentity = `-- name: GetOIDCIdentity :one
SELECT user_id FROM oidc_identities WHERE issuer = $1 AND subject = $2
`

type GetOIDCIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetOIDCIdentity(ctx context.Context, arg GetOIDCIdentityParams) (id.ID, error) {
	row := q.db.QueryRowContext(ctx, getOIDCIdentity, arg.Issuer, arg.Subject)
	var user_id id.ID
	err := row.Scan(&user_id)
	return user_id, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT phc FROM password_credentials WHERE user_id = $1
`

type GetPasswordCredentialParams struct {
	UserID id.ID
}

func (q *Queries) GetPasswordCredential(ctx context.Context, arg GetPasswordCredentialParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordCredential, arg.UserID)
	var phc string
	err := row.Scan(&phc)
	return phc, err
}

const getTOTP = `-- name: GetTOTP :one
SELECT user_id, secret, digits, period, algorithm, confirmed_at, last_counter, created FROM totp_secrets WHERE user_id = $1
`

type GetTOTPParams struct {
	UserID id.ID
}

func (q *Queries) GetTOTP(ctx context.Context, arg GetTOTPParams) (TotpSecrets, error) {
	row := q.db.QueryRowContext(ctx, getTOTP, arg.UserID)
	var i TotpSecrets
	err := row.Scan(
		&i.UserID,
		&i.Secret,
		&i.Digits,
		&i.Period,
		&i.Algorithm,
		&i.ConfirmedAt,
		&i.LastCounter,
		&i.Created,
	)
	return i, err
}

const getWebauthnCredential = `-- name: GetWebauthnCredential :one
SELECT cred_id, rp_id, user_id, public_key, sign_count, attestation_type, attestation_format, transports, flags, extensions_json, name, created, last_used FROM webauthn_credentials WHERE cred_id = $1
`

type GetWebauthnCredentialParams struct {
	CredID []byte
}

func (q *Queries) GetWebauthnCredential(ctx context.Context, arg GetWebauthnCredentialParams) (WebauthnCredentials, error) {
	row := q.db.QueryRowContext(ctx, getWebauthnCredential, arg.CredID)
	var i WebauthnCredentials
	err := row.Scan(
		&i.CredID,
		&i.RpID,
		&i.UserID,
		&i.PublicKey,
		&i.SignCount,
		&i.AttestationType,
		&i.AttestationFormat,
		&i.Transports,
		&i.Flags,
		&i.ExtensionsJson,
		&i.Name,
		&i.Created,
		&i.LastUsed,
	)
	return i, err
}

const getWebauthnUserByHandle = `-- name: GetWebauthnUserByHandle :one
SELECT user_id FROM webauthn_users WHERE rp_id = $1 AND user_handle = $2
`

type GetWebauthnUserByHandleParams struct {
	RpID       string
	UserHandle []byte
}

func (q *Queries) GetWebauthnUserByHandle(ctx context.Context, arg GetWebauthnUserByHandleParams) (id.ID, error) {
	row := q.db.QueryRowContext(ctx, getWebauthnUserByHandle, arg.RpID, arg.UserHandle)
	var user_id id.ID
	err := row.Scan(&user_id)
	return user_id, err
}

const getWebauthnUserHandle = `-- name: GetWebauthnUserHandle :one
SELECT user_handle FROM webauthn_users WHERE rp_id = $1 AND user_id = $2
`

type GetWebauthnUserHandleParams struct {
	RpID   string
	UserID id.ID
}

func (q *Queries) GetWebauthnUserHandle(ctx context.Context, arg GetWebauthnUserHandleParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getWebauthnUserHandle, arg.RpID, arg.UserID)
	var user_handle []byte
	err := row.Scan(&user_handle)
	return user_handle, err
}

const listWebauthnCredentials = `-- name: ListWebauthnCredentials :many
SELECT cred_id, rp_id, user_id, public_key, sign_count, attestation_type, attestation_format, transports, flags, extensions_json, name, created, last_used FROM webauthn_credentials WHERE rp_id = $1 AND user_id = $2 ORDER BY created
`

type ListWebauthnCredentialsParams struct {
	RpID   string
	UserID id.ID
}

func (q *Queries) ListWebauthnCredentials(ctx context.Context, arg ListWebauthnCredentialsParams) ([]WebauthnCredentials, error) {
	rows, err := q.db.QueryContext(ctx, listWebauthnCredentials, arg.RpID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredentials{}
	for rows.Next() {
		var i WebauthnCredentials
		if err := rows.Scan(
			&i.CredID,
			&i.RpID,
			&i.UserID,
			&i.PublicKey,
			&i.SignCount,
			&i.AttestationType,
			&i.AttestationFormat,
			&i.Transports,
			&i.Flags,
			&i.ExtensionsJson,
			&i.Name,
			&i.Created,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCeremonies = `-- name: PruneCeremonies :execrows
DELETE FROM webauthn_ceremonies WHERE expires <= $1
`

type PruneCeremoniesParams struct {
	Expires int64
}

func (q *Queries) PruneCeremonies(ctx context.Context, arg PruneCeremoniesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneCeremonies, arg.Expires)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const putCeremony = `-- name: PutCeremony :exec
INSERT INTO webauthn_ceremonies (id, kind, user_id, session_json, created, expires)
VALUES ($1, $2, $3, $4, $5, $6)
`

type PutCeremonyParams struct {
	ID          id.ID
	Kind        int64
	UserID      *id.ID
	SessionJson string
	Created     int64
	Expires     int64
}

func (q *Queries) PutCeremony(ctx context.Context, arg PutCeremonyParams) error {
	_, err := q.db.ExecContext(ctx, putCeremony,
		arg.ID,
		arg.Kind,
		arg.UserID,
		arg.SessionJson,
		arg.Created,
		arg.Expires,
	)
	return err
}

const putOIDCIdentity = `-- name: PutOIDCIdentity :exec
INSERT INTO oidc_identities (issuer, subject, user_id, created) VALUES ($1, $2, $3, $4)
ON CONFLICT (issuer, subject) DO NOTHING
`

type PutOIDCIdentityParams struct {
	Issuer  string
	Subject string
	UserID  id.ID
	Created int64
}

func (q *Queries) PutOIDCIdentity(ctx context.Context, arg PutOIDCIdentityParams) error {
	_, err := q.db.ExecContext(ctx, putOIDCIdentity,
		arg.Issuer,
		arg.Subject,
		arg.UserID,
		arg.Created,
	)
	return err
}

const putPasswordCredential = `-- name: PutPasswordCredential :exec
INSERT INTO password_credentials (user_id, phc, updated) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET phc = excluded.phc, updated = excluded.updated
`

type PutPasswordCredentialParams struct {
	UserID  id.ID
	Phc     string
	Updated int64
}

func (q *Queries) PutPasswordCredential(ctx context.Context, arg PutPasswordCredentialParams) error {
	_, err := q.db.ExecContext(ctx, putPasswordCredential, arg.UserID, arg.Phc, arg.Updated)
	return err
}

const putRecoveryCode = `-- name: PutRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash, created, used_at) VALUES ($1, $2, $3, NULL)
`

type PutRecoveryCodeParams struct {
	UserID   id.ID
	CodeHash []byte
	Created  int64
}

func (q *Queries) PutRecoveryCode(ctx context.Context, arg PutRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, putRecoveryCode, arg.UserID, arg.CodeHash, arg.Created)
	return err
}

const putTOTP = `-- name: PutTOTP :exec
INSERT INTO totp_secrets (user_id, secret, digits, period, algorithm, confirmed_at, last_counter, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET secret = excluded.secret, digits = excluded.digits,
  period = excluded.period, algorithm = excluded.algorithm, confirmed_at = excluded.confirmed_at,
  last_counter = excluded.last_counter
`

type PutTOTPParams struct {
	UserID      id.ID
	Secret      []byte
	Digits      int64
	Period      int64
	Algorithm   string
	ConfirmedAt sql.NullInt64
	LastCounter int64
	Created     int64
}

func (q *Queries) PutTOTP(ctx context.Context, arg PutTOTPParams) error {
	_, err := q.db.ExecContext(ctx, putTOTP,
		arg.UserID,
		arg.Secret,
		arg.Digits,
		arg.Period,
		arg.Algorithm,
		arg.ConfirmedAt,
		arg.LastCounter,
		arg.Created,
	)
	return err
}

const putWebauthnCredential = `-- name: PutWebauthnCredential :exec
INSERT INTO webauthn_credentials (cred_id, rp_id, user_id, public_key, sign_count, attestation_type, attestation_format, transports, flags, extensions_json, name, created, last_used)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type PutWebauthnCredentialParams struct {
	CredID            []byte
	RpID              string
	UserID            id.ID
	PublicKey         []byte
	SignCount         int64
	AttestationType   string
	AttestationFormat string
	Transports        string
	Flags             []byte
	ExtensionsJson    string
	Name              string
	Created           int64
	LastUsed          sql.NullInt64
}

func (q *Queries) PutWebauthnCredential(ctx context.Context, arg PutWebauthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, putWebauthnCredential,
		arg.CredID,
		arg.RpID,
		arg.UserID,
		arg.PublicKey,
		arg.SignCount,
		arg.AttestationType,
		arg.AttestationFormat,
		arg.Transports,
		arg.Flags,
		arg.ExtensionsJson,
		arg.Name,
		arg.Created,
		arg.LastUsed,
	)
	return err
}

const putWebauthnUser = `-- name: PutWebauthnUser :exec
INSERT INTO webauthn_users (rp_id, user_id, user_handle, created) VALUES ($1, $2, $3, $4)
ON CONFLICT (rp_id, user_id) DO NOTHING
`

type PutWebauthnUserParams struct {
	RpID       string
	UserID     id.ID
	UserHandle []byte
	Created    int64
}

// DO NOTHING, not DO UPDATE: a user handle is minted once and never rotated.
// The authenticator stores the handle it saw at registration, so overwriting it
// on a later ceremony makes GetWebauthnUserByHandle miss and permanently breaks
// discoverable login for that account (deviation ID11).
func (q *Queries) PutWebauthnUser(ctx context.Context, arg PutWebauthnUserParams) error {
	_, err := q.db.ExecContext(ctx, putWebauthnUser,
		arg.RpID,
		arg.UserID,
		arg.UserHandle,
		arg.Created,
	)
	return err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (user_id, ip, method, ok, at) VALUES ($1, $2, $3, $4, $5)
`

type RecordLoginAttemptParams struct {
	UserID *id.ID
	Ip     string
	Method int64
	Ok     int64
	At     int64
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordLoginAttempt,
		arg.UserID,
		arg.Ip,
		arg.Method,
		arg.Ok,
		arg.At,
	)
	return err
}

const updateWebauthnCredential = `-- name: UpdateWebauthnCredential :exec
UPDATE webauthn_credentials SET sign_count = $1, flags = $2, last_used = $3 WHERE cred_id = $4
`

type UpdateWebauthnCredentialParams struct {
	SignCount int64
	Flags     []byte
	LastUsed  sql.NullInt64
	CredID    []byte
}

func (q *Queries) UpdateWebauthnCredential(ctx context.Context, arg UpdateWebauthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateWebauthnCredential,
		arg.SignCount,
		arg.Flags,
		arg.LastUsed,
		arg.CredID,
	)
	return err
}
