// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package pgdb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const backupRefersToBlob = `-- name: BackupRefersToBlob :one
SELECT COUNT(*) FROM backups WHERE backups.blob_id = $1
`

type BackupRefersToBlobParams struct {
	BlobID []byte
}

// COUNT, not EXISTS, for the reason GetBlobTombstone gives.
func (q *Queries) BackupRefersToBlob(ctx context.Context, arg BackupRefersToBlobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, backupRefersToBlob, arg.BlobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearBlobUnreferenced = `-- name: ClearBlobUnreferenced :exec
UPDATE blobs SET unref_since = NULL WHERE blobs.blob_id = $1
`

type ClearBlobUnreferencedParams struct {
	BlobID []byte
}

func (q *Queries) ClearBlobUnreferenced(ctx context.Context, arg ClearBlobUnreferencedParams) error {
	_, err := q.db.ExecContext(ctx, clearBlobUnreferenced, arg.BlobID)
	return err
}

const countBlobRefs = `-- name: CountBlobRefs :one
SELECT COUNT(*) FROM blob_refs WHERE blob_id = $1
`

type CountBlobRefsParams struct {
	BlobID []byte
}

func (q *Queries) CountBlobRefs(ctx context.Context, arg CountBlobRefsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlobRefs, arg.BlobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllBlobRefs = `-- name: DeleteAllBlobRefs :execrows
DELETE FROM blob_refs WHERE blob_id = $1
`

type DeleteAllBlobRefsParams struct {
	BlobID []byte
}

// P2-D18 (Plan 2 task 11): the admin purge removes every reference to the blob, in every
// channel, in one statement.
func (q *Queries) DeleteAllBlobRefs(ctx context.Context, arg DeleteAllBlobRefsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllBlobRefs, arg.BlobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBlob = `-- name: DeleteBlob :execrows
DELETE FROM blobs WHERE blob_id = $1
`

type DeleteBlobParams struct {
	BlobID []byte
}

func (q *Queries) DeleteBlob(ctx context.Context, arg DeleteBlobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBlob, arg.BlobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBlobRef = `-- name: DeleteBlobRef :exec
DELETE FROM blob_refs WHERE blob_id = $1 AND channel_id = $2
`

type DeleteBlobRefParams struct {
	BlobID    []byte
	ChannelID id.ID
}

func (q *Queries) DeleteBlobRef(ctx context.Context, arg DeleteBlobRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlobRef, arg.BlobID, arg.ChannelID)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT user_id, kind, device_id, chunk_seq, blob_id, manifest_sig, created
FROM backups WHERE user_id = $1 AND kind = $2 AND device_id = $3 AND chunk_seq = $4
`

type GetBackupParams struct {
	UserID   id.ID
	Kind     int64
	DeviceID id.ID
	ChunkSeq int64
}

func (q *Queries) GetBackup(ctx context.Context, arg GetBackupParams) (Backups, error) {
	row := q.db.QueryRowContext(ctx, getBackup,
		arg.UserID,
		arg.Kind,
		arg.DeviceID,
		arg.ChunkSeq,
	)
	var i Backups
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.DeviceID,
		&i.ChunkSeq,
		&i.BlobID,
		&i.ManifestSig,
		&i.Created,
	)
	return i, err
}

const getBlob = `-- name: GetBlob :one
SELECT blob_id, size, storage_ref, created, unref_since FROM blobs WHERE blob_id = $1
`

type GetBlobParams struct {
	BlobID []byte
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (Blobs, error) {
	row := q.db.QueryRowContext(ctx, getBlob, arg.BlobID)
	var i Blobs
	err := row.Scan(
		&i.BlobID,
		&i.Size,
		&i.StorageRef,
		&i.Created,
		&i.UnrefSince,
	)
	return i, err
}

const getBlobRef = `-- name: GetBlobRef :one
SELECT blob_id, channel_id, uploader_device, mime, created
FROM blob_refs WHERE blob_id = $1 AND channel_id = $2
`

type GetBlobRefParams struct {
	BlobID    []byte
	ChannelID id.ID
}

func (q *Queries) GetBlobRef(ctx context.Context, arg GetBlobRefParams) (BlobRefs, error) {
	row := q.db.QueryRowContext(ctx, getBlobRef, arg.BlobID, arg.ChannelID)
	var i BlobRefs
	err := row.Scan(
		&i.BlobID,
		&i.ChannelID,
		&i.UploaderDevice,
		&i.Mime,
		&i.Created,
	)
	return i, err
}

const getBlobTombstone = `-- name: GetBlobTombstone :one
SELECT COUNT(*) FROM blob_tombstones WHERE blob_id = $1
`

type GetBlobTombstoneParams struct {
	BlobID []byte
}

// COUNT, not EXISTS: EXISTS is int64 on SQLite and bool on Postgres, and the two Querier
// interfaces must stay identical.
func (q *Queries) GetBlobTombstone(ctx context.Context, arg GetBlobTombstoneParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlobTombstone, arg.BlobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBackup = `-- name: InsertBackup :exec
INSERT INTO backups (user_id, kind, device_id, chunk_seq, blob_id, manifest_sig, created)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertBackupParams struct {
	UserID      id.ID
	Kind        int64
	DeviceID    id.ID
	ChunkSeq    int64
	BlobID      []byte
	ManifestSig []byte
	Created     int64
}

// dilla-web-2a (L-SQL-21, F3, Q27): the root object is written once. No ON CONFLICT: a taken
// (user_id, kind, device_id, chunk_seq) is a unique violation, which the adapters map to ErrConflict.
func (q *Queries) InsertBackup(ctx context.Context, arg InsertBackupParams) error {
	_, err := q.db.ExecContext(ctx, insertBackup,
		arg.UserID,
		arg.Kind,
		arg.DeviceID,
		arg.ChunkSeq,
		arg.BlobID,
		arg.ManifestSig,
		arg.Created,
	)
	return err
}

const instanceBlobBytes = `-- name: InstanceBlobBytes :one
SELECT CAST(COALESCE(SUM(size), 0) AS BIGINT) FROM blobs
`

// Fix wave C7: blobs.store_max_bytes. Every row counts, referenced or not: an orphaned or
// unreferenced blob's file is on disk until the sweeper collects it. The cast keeps SUM's
// NUMERIC an int64, as UserBlobBytes does.
func (q *Queries) InstanceBlobBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, instanceBlobBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listBackups = `-- name: ListBackups :many
SELECT user_id, kind, device_id, chunk_seq, blob_id, manifest_sig, created
FROM backups WHERE user_id = $1 AND kind = $2
ORDER BY device_id, chunk_seq
`

type ListBackupsParams struct {
	UserID id.ID
	Kind   int64
}

func (q *Queries) ListBackups(ctx context.Context, arg ListBackupsParams) ([]Backups, error) {
	rows, err := q.db.QueryContext(ctx, listBackups, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backups{}
	for rows.Next() {
		var i Backups
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.DeviceID,
			&i.ChunkSeq,
			&i.BlobID,
			&i.ManifestSig,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlobRefsOfDeletedChannels = `-- name: ListBlobRefsOfDeletedChannels :many
SELECT blob_refs.blob_id, blob_refs.channel_id, blob_refs.uploader_device, blob_refs.mime,
       blob_refs.created
FROM blob_refs
JOIN channels ON channels.id = blob_refs.channel_id
WHERE channels.deleted_at IS NOT NULL
ORDER BY blob_refs.created, blob_refs.channel_id, blob_refs.blob_id
LIMIT $1::bigint
`

type ListBlobRefsOfDeletedChannelsParams struct {
	MaxRows int64
}

// Channels are tombstoned, never removed, so the ON DELETE CASCADE on blob_refs never fires:
// the sweeper drops a deleted channel's references itself.
func (q *Queries) ListBlobRefsOfDeletedChannels(ctx context.Context, arg ListBlobRefsOfDeletedChannelsParams) ([]BlobRefs, error) {
	rows, err := q.db.QueryContext(ctx, listBlobRefsOfDeletedChannels, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlobRefs{}
	for rows.Next() {
		var i BlobRefs
		if err := rows.Scan(
			&i.BlobID,
			&i.ChannelID,
			&i.UploaderDevice,
			&i.Mime,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlobRetentionPolicies = `-- name: ListBlobRetentionPolicies :many
SELECT communities.id, communities.policy_json FROM communities
WHERE communities.deleted_at IS NULL
  AND EXISTS (
    SELECT 1 FROM channels JOIN blob_refs ON blob_refs.channel_id = channels.id
    WHERE channels.community_id = communities.id AND channels.deleted_at IS NULL
  )
ORDER BY communities.id
`

type ListBlobRetentionPoliciesRow struct {
	ID         id.ID
	PolicyJson string
}

// Plan 2 task 11, R28: the policy of every live community that still holds a reference in a
// live channel, so the sweeper parses one policy per community rather than one per reference.
func (q *Queries) ListBlobRetentionPolicies(ctx context.Context) ([]ListBlobRetentionPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlobRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlobRetentionPoliciesRow{}
	for rows.Next() {
		var i ListBlobRetentionPoliciesRow
		if err := rows.Scan(&i.ID, &i.PolicyJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlobs = `-- name: ListBlobs :many
SELECT blobs.blob_id, blobs.size, blobs.storage_ref, blobs.created, blobs.unref_since FROM blobs
WHERE blobs.blob_id > $1
ORDER BY blobs.blob_id
LIMIT $2::bigint
`

type ListBlobsParams struct {
	After   []byte
	MaxRows int64
}

// Plan 2 task 12: the backup's walk over every blob row, in blob_id byte order (bytea compares
// bytewise), resumed after the last id of the previous page. An empty after sorts first.
func (q *Queries) ListBlobs(ctx context.Context, arg ListBlobsParams) ([]Blobs, error) {
	rows, err := q.db.QueryContext(ctx, listBlobs, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blobs{}
	for rows.Next() {
		var i Blobs
		if err := rows.Scan(
			&i.BlobID,
			&i.Size,
			&i.StorageRef,
			&i.Created,
			&i.UnrefSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectableBlobs = `-- name: ListCollectableBlobs :many
SELECT blobs.blob_id, blobs.size, blobs.storage_ref, blobs.created, blobs.unref_since FROM blobs
WHERE blobs.unref_since IS NOT NULL AND blobs.unref_since < $1::bigint
  AND NOT EXISTS (SELECT 1 FROM blob_refs WHERE blob_refs.blob_id = blobs.blob_id)
  AND NOT EXISTS (SELECT 1 FROM backups WHERE backups.blob_id = blobs.blob_id)
ORDER BY blobs.unref_since
LIMIT $2::bigint
`

type ListCollectableBlobsParams struct {
	Before  int64
	MaxRows int64
}

// dilla-web-2a (L-SQL-21): a blob a backups row names is never collectable; backups have no blob_refs row.
func (q *Queries) ListCollectableBlobs(ctx context.Context, arg ListCollectableBlobsParams) ([]Blobs, error) {
	rows, err := q.db.QueryContext(ctx, listCollectableBlobs, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blobs{}
	for rows.Next() {
		var i Blobs
		if err := rows.Scan(
			&i.BlobID,
			&i.Size,
			&i.StorageRef,
			&i.Created,
			&i.UnrefSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredBlobRefs = `-- name: ListExpiredBlobRefs :many
SELECT blob_refs.blob_id, blob_refs.channel_id, blob_refs.uploader_device, blob_refs.mime,
       blob_refs.created
FROM blob_refs
JOIN channels ON channels.id = blob_refs.channel_id
JOIN communities ON communities.id = channels.community_id
WHERE communities.id = $1
  AND blob_refs.created < $2::bigint
ORDER BY blob_refs.created, blob_refs.channel_id, blob_refs.blob_id
LIMIT $3::bigint
`

type ListExpiredBlobRefsParams struct {
	CommunityID id.ID
	Before      int64
	MaxRows     int64
}

// A community's references created strictly before the retention cutoff, oldest first.
func (q *Queries) ListExpiredBlobRefs(ctx context.Context, arg ListExpiredBlobRefsParams) ([]BlobRefs, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredBlobRefs, arg.CommunityID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlobRefs{}
	for rows.Next() {
		var i BlobRefs
		if err := rows.Scan(
			&i.BlobID,
			&i.ChannelID,
			&i.UploaderDevice,
			&i.Mime,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBlob = `-- name: LockBlob :exec
SELECT blob_id FROM blobs WHERE blob_id = $1 FOR UPDATE
`

type LockBlobParams struct {
	BlobID []byte
}

// The per-blob lock the recording transactions take before their cross-table checks: the blobs
// row FOR UPDATE until Tx commits (the caller inserted it first if it was absent).
func (q *Queries) LockBlob(ctx context.Context, arg LockBlobParams) error {
	_, err := q.db.ExecContext(ctx, lockBlob, arg.BlobID)
	return err
}

const markBlobUnreferenced = `-- name: MarkBlobUnreferenced :exec
UPDATE blobs SET unref_since = $1
WHERE blobs.blob_id = $2
  AND blobs.unref_since IS NULL
  AND NOT EXISTS (SELECT 1 FROM blob_refs WHERE blob_refs.blob_id = blobs.blob_id)
`

type MarkBlobUnreferencedParams struct {
	At     sql.NullInt64
	BlobID []byte
}

// Sets the mark only when no reference is left, and only when it is not already set, so a
// repeated delete cannot push collection back.
func (q *Queries) MarkBlobUnreferenced(ctx context.Context, arg MarkBlobUnreferencedParams) error {
	_, err := q.db.ExecContext(ctx, markBlobUnreferenced, arg.At, arg.BlobID)
	return err
}

const putBackup = `-- name: PutBackup :exec
INSERT INTO backups (user_id, kind, device_id, chunk_seq, blob_id, manifest_sig, created)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, kind, device_id, chunk_seq) DO UPDATE SET
  blob_id = excluded.blob_id, manifest_sig = excluded.manifest_sig, created = excluded.created
`

type PutBackupParams struct {
	UserID      id.ID
	Kind        int64
	DeviceID    id.ID
	ChunkSeq    int64
	BlobID      []byte
	ManifestSig []byte
	Created     int64
}

// One row per (user, kind, device, chunk); a re-upload of the same chunk replaces it.
func (q *Queries) PutBackup(ctx context.Context, arg PutBackupParams) error {
	_, err := q.db.ExecContext(ctx, putBackup,
		arg.UserID,
		arg.Kind,
		arg.DeviceID,
		arg.ChunkSeq,
		arg.BlobID,
		arg.ManifestSig,
		arg.Created,
	)
	return err
}

const putBlob = `-- name: PutBlob :exec

INSERT INTO blobs (blob_id, size, storage_ref, created, unref_since)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (blob_id) DO NOTHING
`

type PutBlobParams struct {
	BlobID     []byte
	Size       int64
	StorageRef string
	Created    int64
	UnrefSince sql.NullInt64
}

// Blobs, blob references and tombstones (Plan 2 task 10, 00010_blobs.sql). Every column in a
// statement with a subquery is qualified: sqlc's analyser calls a bare blob_id ambiguous as soon
// as a second table is in scope (gap-47 section 19.4, C11).
// Content addressing makes a second insert of the same id the same object, so it is a no-op
// rather than a conflict: two uploads of the same bytes may race to here.
func (q *Queries) PutBlob(ctx context.Context, arg PutBlobParams) error {
	_, err := q.db.ExecContext(ctx, putBlob,
		arg.BlobID,
		arg.Size,
		arg.StorageRef,
		arg.Created,
		arg.UnrefSince,
	)
	return err
}

const putBlobRef = `-- name: PutBlobRef :exec
INSERT INTO blob_refs (blob_id, channel_id, uploader_device, mime, created)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (blob_id, channel_id) DO NOTHING
`

type PutBlobRefParams struct {
	BlobID         []byte
	ChannelID      id.ID
	UploaderDevice id.ID
	Mime           string
	Created        int64
}

// One reference per (blob, channel); a repeat keeps the first uploader.
func (q *Queries) PutBlobRef(ctx context.Context, arg PutBlobRefParams) error {
	_, err := q.db.ExecContext(ctx, putBlobRef,
		arg.BlobID,
		arg.ChannelID,
		arg.UploaderDevice,
		arg.Mime,
		arg.Created,
	)
	return err
}

const putBlobTombstone = `-- name: PutBlobTombstone :exec
INSERT INTO blob_tombstones (blob_id, reason, by_user, created)
VALUES ($1, $2, $3, $4)
ON CONFLICT (blob_id) DO NOTHING
`

type PutBlobTombstoneParams struct {
	BlobID  []byte
	Reason  string
	ByUser  id.ID
	Created int64
}

// The first purge's record stands.
func (q *Queries) PutBlobTombstone(ctx context.Context, arg PutBlobTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, putBlobTombstone,
		arg.BlobID,
		arg.Reason,
		arg.ByUser,
		arg.Created,
	)
	return err
}

const userBlobBytes = `-- name: UserBlobBytes :one
SELECT CAST(COALESCE(SUM(b.size), 0) AS BIGINT) FROM blobs b
WHERE b.blob_id IN (
  SELECT r.blob_id FROM blob_refs r
  JOIN devices d ON d.id = r.uploader_device
  WHERE d.user_id = $1
  UNION
  SELECT k.blob_id FROM backups k
  WHERE k.user_id = $1
)
`

type UserBlobBytesParams struct {
	UserID id.ID
}

// The quota counts each distinct blob a user uploaded once, however many
// channels they published it into, and the user's own backup objects with them (dilla-web-2a
// boundary ruling 2): a replaced state object leaves the count with its row. SUM over BIGINT is
// NUMERIC on Postgres; the cast keeps it int64 like the SQLite twin.
func (q *Queries) UserBlobBytes(ctx context.Context, arg UserBlobBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userBlobBytes, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const userReferencesBlob = `-- name: UserReferencesBlob :one
SELECT COUNT(*) FROM blob_refs r
JOIN devices d ON d.id = r.uploader_device
WHERE r.blob_id = $1 AND d.user_id = $2
`

type UserReferencesBlobParams struct {
	BlobID []byte
	UserID id.ID
}

// Whether the user already references the blob in some channel, so the bytes already count
// toward their quota. COUNT, not EXISTS, for the reason GetBlobTombstone gives.
func (q *Queries) UserReferencesBlob(ctx context.Context, arg UserReferencesBlobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userReferencesBlob, arg.BlobID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
