// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package pgdb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, user_id, dsk_pub, tier, signer_tier, credential_blob, verified_at, revoked_at, quarantined_at, quarantine_reason, last_seen, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateDeviceParams struct {
	ID               id.ID
	UserID           id.ID
	DskPub           []byte
	Tier             int64
	SignerTier       int64
	CredentialBlob   []byte
	VerifiedAt       sql.NullInt64
	RevokedAt        sql.NullInt64
	QuarantinedAt    sql.NullInt64
	QuarantineReason string
	LastSeen         int64
	Created          int64
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.DskPub,
		arg.Tier,
		arg.SignerTier,
		arg.CredentialBlob,
		arg.VerifiedAt,
		arg.RevokedAt,
		arg.QuarantinedAt,
		arg.QuarantineReason,
		arg.LastSeen,
		arg.Created,
	)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, dsk_pub, tier, signer_tier, credential_blob, verified_at, revoked_at, quarantined_at, quarantine_reason, last_seen, created FROM devices WHERE id = $1
`

type GetDeviceParams struct {
	ID id.ID
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Devices, error) {
	row := q.db.QueryRowContext(ctx, getDevice, arg.ID)
	var i Devices
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DskPub,
		&i.Tier,
		&i.SignerTier,
		&i.CredentialBlob,
		&i.VerifiedAt,
		&i.RevokedAt,
		&i.QuarantinedAt,
		&i.QuarantineReason,
		&i.LastSeen,
		&i.Created,
	)
	return i, err
}

const getDeviceList = `-- name: GetDeviceList :one
SELECT user_id, version, blob, ssk_signature, prev_hash, created FROM device_lists WHERE user_id = $1 ORDER BY version DESC LIMIT 1
`

type GetDeviceListParams struct {
	UserID id.ID
}

func (q *Queries) GetDeviceList(ctx context.Context, arg GetDeviceListParams) (DeviceLists, error) {
	row := q.db.QueryRowContext(ctx, getDeviceList, arg.UserID)
	var i DeviceLists
	err := row.Scan(
		&i.UserID,
		&i.Version,
		&i.Blob,
		&i.SskSignature,
		&i.PrevHash,
		&i.Created,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, dsk_pub, tier, signer_tier, credential_blob, verified_at, revoked_at, quarantined_at, quarantine_reason, last_seen, created FROM devices WHERE user_id = $1 ORDER BY created
`

type ListDevicesByUserParams struct {
	UserID id.ID
}

func (q *Queries) ListDevicesByUser(ctx context.Context, arg ListDevicesByUserParams) ([]Devices, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Devices{}
	for rows.Next() {
		var i Devices
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DskPub,
			&i.Tier,
			&i.SignerTier,
			&i.CredentialBlob,
			&i.VerifiedAt,
			&i.RevokedAt,
			&i.QuarantinedAt,
			&i.QuarantineReason,
			&i.LastSeen,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putDeviceList = `-- name: PutDeviceList :exec
INSERT INTO device_lists (user_id, version, blob, ssk_signature, prev_hash, created)
VALUES ($1, $2, $3, $4, $5, $6)
`

type PutDeviceListParams struct {
	UserID       id.ID
	Version      int64
	Blob         []byte
	SskSignature []byte
	PrevHash     []byte
	Created      int64
}

func (q *Queries) PutDeviceList(ctx context.Context, arg PutDeviceListParams) error {
	_, err := q.db.ExecContext(ctx, putDeviceList,
		arg.UserID,
		arg.Version,
		arg.Blob,
		arg.SskSignature,
		arg.PrevHash,
		arg.Created,
	)
	return err
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE devices SET revoked_at = $1 WHERE id = $2
`

type RevokeDeviceParams struct {
	RevokedAt sql.NullInt64
	ID        id.ID
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.ExecContext(ctx, revokeDevice, arg.RevokedAt, arg.ID)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen = $1 WHERE id = $2
`

type TouchDeviceParams struct {
	LastSeen int64
	ID       id.ID
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchDevice, arg.LastSeen, arg.ID)
	return err
}
