// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package pgdb

import (
	"context"

	id "github.com/jonasthim/dilla/internal/id"
)

const bumpGeneration = `-- name: BumpGeneration :one
UPDATE instances SET generation = generation + 1 RETURNING generation
`

func (q *Queries) BumpGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const createInstance = `-- name: CreateInstance :exec
INSERT INTO instances (instance_id, external_sender_key_id, key_history, franking_key_id, generation, policy_version, created)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInstanceParams struct {
	InstanceID          id.ID
	ExternalSenderKeyID id.ID
	KeyHistory          []byte
	FrankingKeyID       id.ID
	Generation          int64
	PolicyVersion       int64
	Created             int64
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createInstance,
		arg.InstanceID,
		arg.ExternalSenderKeyID,
		arg.KeyHistory,
		arg.FrankingKeyID,
		arg.Generation,
		arg.PolicyVersion,
		arg.Created,
	)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT instance_id, external_sender_key_id, key_history, franking_key_id, generation, policy_version, created
FROM instances LIMIT 1
`

func (q *Queries) GetInstance(ctx context.Context) (Instances, error) {
	row := q.db.QueryRowContext(ctx, getInstance)
	var i Instances
	err := row.Scan(
		&i.InstanceID,
		&i.ExternalSenderKeyID,
		&i.KeyHistory,
		&i.FrankingKeyID,
		&i.Generation,
		&i.PolicyVersion,
		&i.Created,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM instance_settings WHERE key = $1
`

type GetSettingParams struct {
	Key string
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSetting, arg.Key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO instance_settings (key, value, updated) VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated = excluded.updated
`

type PutSettingParams struct {
	Key     string
	Value   []byte
	Updated int64
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.ExecContext(ctx, putSetting, arg.Key, arg.Value, arg.Updated)
	return err
}
