// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package pgdb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const getAppMessage = `-- name: GetAppMessage :one
SELECT group_id, seq, epoch, uploader_device, blob, commitment_c, franking_tag, size, created, expires, deleted_at FROM mls_app_messages WHERE group_id = $1 AND seq = $2
`

type GetAppMessageParams struct {
	GroupID id.ID
	Seq     int64
}

func (q *Queries) GetAppMessage(ctx context.Context, arg GetAppMessageParams) (MlsAppMessages, error) {
	row := q.db.QueryRowContext(ctx, getAppMessage, arg.GroupID, arg.Seq)
	var i MlsAppMessages
	err := row.Scan(
		&i.GroupID,
		&i.Seq,
		&i.Epoch,
		&i.UploaderDevice,
		&i.Blob,
		&i.CommitmentC,
		&i.FrankingTag,
		&i.Size,
		&i.Created,
		&i.Expires,
		&i.DeletedAt,
	)
	return i, err
}

const getCursor = `-- name: GetCursor :one
SELECT device_id, group_id, last_seq, last_epoch, updated FROM device_cursors WHERE device_id = $1 AND group_id = $2
`

type GetCursorParams struct {
	DeviceID id.ID
	GroupID  id.ID
}

func (q *Queries) GetCursor(ctx context.Context, arg GetCursorParams) (DeviceCursors, error) {
	row := q.db.QueryRowContext(ctx, getCursor, arg.DeviceID, arg.GroupID)
	var i DeviceCursors
	err := row.Scan(
		&i.DeviceID,
		&i.GroupID,
		&i.LastSeq,
		&i.LastEpoch,
		&i.Updated,
	)
	return i, err
}

const listAppMessages = `-- name: ListAppMessages :many
SELECT group_id, seq, epoch, uploader_device, blob, commitment_c, franking_tag, size, created, expires, deleted_at FROM mls_app_messages WHERE group_id = $1 AND seq >= $2
ORDER BY seq LIMIT $3::bigint
`

type ListAppMessagesParams struct {
	GroupID id.ID
	Seq     int64
	MaxRows int64
}

func (q *Queries) ListAppMessages(ctx context.Context, arg ListAppMessagesParams) ([]MlsAppMessages, error) {
	rows, err := q.db.QueryContext(ctx, listAppMessages, arg.GroupID, arg.Seq, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlsAppMessages{}
	for rows.Next() {
		var i MlsAppMessages
		if err := rows.Scan(
			&i.GroupID,
			&i.Seq,
			&i.Epoch,
			&i.UploaderDevice,
			&i.Blob,
			&i.CommitmentC,
			&i.FrankingTag,
			&i.Size,
			&i.Created,
			&i.Expires,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const minCursor = `-- name: MinCursor :one
SELECT COALESCE(MIN(last_seq), 0)::bigint AS min_seq FROM device_cursors
WHERE group_id = $1 AND updated >= $2
`

type MinCursorParams struct {
	GroupID id.ID
	Updated int64
}

func (q *Queries) MinCursor(ctx context.Context, arg MinCursorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, minCursor, arg.GroupID, arg.Updated)
	var min_seq int64
	err := row.Scan(&min_seq)
	return min_seq, err
}

const pruneAppMessages = `-- name: PruneAppMessages :execrows
DELETE FROM mls_app_messages WHERE group_id = $1 AND seq < $2 AND created < $3
`

type PruneAppMessagesParams struct {
	GroupID id.ID
	Seq     int64
	Created int64
}

func (q *Queries) PruneAppMessages(ctx context.Context, arg PruneAppMessagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAppMessages, arg.GroupID, arg.Seq, arg.Created)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const putAppMessage = `-- name: PutAppMessage :exec
INSERT INTO mls_app_messages (group_id, seq, epoch, uploader_device, blob, commitment_c,
                              franking_tag, size, created, expires, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type PutAppMessageParams struct {
	GroupID        id.ID
	Seq            int64
	Epoch          int64
	UploaderDevice id.ID
	Blob           []byte
	CommitmentC    []byte
	FrankingTag    []byte
	Size           int64
	Created        int64
	Expires        sql.NullInt64
	DeletedAt      sql.NullInt64
}

func (q *Queries) PutAppMessage(ctx context.Context, arg PutAppMessageParams) error {
	_, err := q.db.ExecContext(ctx, putAppMessage,
		arg.GroupID,
		arg.Seq,
		arg.Epoch,
		arg.UploaderDevice,
		arg.Blob,
		arg.CommitmentC,
		arg.FrankingTag,
		arg.Size,
		arg.Created,
		arg.Expires,
		arg.DeletedAt,
	)
	return err
}

const putCursor = `-- name: PutCursor :exec
INSERT INTO device_cursors (device_id, group_id, last_seq, last_epoch, updated)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (device_id, group_id) DO UPDATE
SET last_seq = excluded.last_seq, last_epoch = excluded.last_epoch, updated = excluded.updated
`

type PutCursorParams struct {
	DeviceID  id.ID
	GroupID   id.ID
	LastSeq   int64
	LastEpoch int64
	Updated   int64
}

func (q *Queries) PutCursor(ctx context.Context, arg PutCursorParams) error {
	_, err := q.db.ExecContext(ctx, putCursor,
		arg.DeviceID,
		arg.GroupID,
		arg.LastSeq,
		arg.LastEpoch,
		arg.Updated,
	)
	return err
}

const tombstoneAppMessage = `-- name: TombstoneAppMessage :exec
UPDATE mls_app_messages SET blob = NULL, deleted_at = $1
WHERE group_id = $2 AND seq = $3 AND deleted_at IS NULL
`

type TombstoneAppMessageParams struct {
	DeletedAt sql.NullInt64
	GroupID   id.ID
	Seq       int64
}

func (q *Queries) TombstoneAppMessage(ctx context.Context, arg TombstoneAppMessageParams) error {
	_, err := q.db.ExecContext(ctx, tombstoneAppMessage, arg.DeletedAt, arg.GroupID, arg.Seq)
	return err
}
