// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

type AuditLog struct {
	ID     int64
	Actor  *id.ID
	Action string
	Target string
	Detail string
	At     int64
}

type DeviceLists struct {
	UserID       id.ID
	Version      int64
	Blob         []byte
	SskSignature []byte
	PrevHash     []byte
	Created      int64
}

type Devices struct {
	ID               id.ID
	UserID           id.ID
	DskPub           []byte
	Tier             int64
	SignerTier       int64
	CredentialBlob   []byte
	VerifiedAt       sql.NullInt64
	RevokedAt        sql.NullInt64
	QuarantinedAt    sql.NullInt64
	QuarantineReason string
	LastSeen         int64
	Created          int64
}

type InstanceSettings struct {
	Key     string
	Value   []byte
	Updated int64
}

type Instances struct {
	InstanceID          id.ID
	ExternalSenderKeyID id.ID
	KeyHistory          []byte
	FrankingKeyID       id.ID
	Generation          int64
	PolicyVersion       int64
	Created             int64
}

type Invites struct {
	ID          id.ID
	CodeHash    []byte
	CommunityID *id.ID
	CreatedBy   *id.ID
	GrantsAdmin int64
	MaxUses     int64
	UsedCount   int64
	Created     int64
	ExpiresAt   int64
	RevokedAt   sql.NullInt64
}

type LoginAttempts struct {
	ID     int64
	UserID *id.ID
	Ip     string
	Method int64
	Ok     int64
	At     int64
}

type OidcIdentities struct {
	Issuer  string
	Subject string
	UserID  id.ID
	Created int64
}

type PasswordCredentials struct {
	UserID  id.ID
	Phc     string
	Updated int64
}

type RecoveryCodes struct {
	UserID   id.ID
	CodeHash []byte
	Created  int64
	UsedAt   sql.NullInt64
}

type Reports struct {
	ID                 id.ID
	Reporter           id.ID
	GroupID            id.ID
	Seq                int64
	RevealedEnvelope   []byte
	KF                 []byte
	FrankingKeyID      id.ID
	VerificationResult string
	Status             int64
	Created            int64
}

type Sessions struct {
	TokenHash   []byte
	DeviceID    id.ID
	UserID      id.ID
	Scope       int64
	Tier        int64
	Created     int64
	Expires     int64
	IdleExpires int64
}

type TotpSecrets struct {
	UserID      id.ID
	Secret      []byte
	Digits      int64
	Period      int64
	Algorithm   string
	ConfirmedAt sql.NullInt64
	LastCounter int64
	Created     int64
}

type Users struct {
	ID         id.ID
	Username   string
	Display    string
	Kind       int64
	UmkPub     []byte
	SskPub     []byte
	SigUmkSsk  []byte
	Flags      int64
	AgeBracket int64
	Created    int64
	DisabledAt sql.NullInt64
	DeletedAt  sql.NullInt64
}

type WebauthnCeremonies struct {
	ID          id.ID
	Kind        int64
	UserID      *id.ID
	SessionJson string
	Created     int64
	Expires     int64
}

type WebauthnCredentials struct {
	CredID            []byte
	RpID              string
	UserID            id.ID
	PublicKey         []byte
	SignCount         int64
	AttestationType   string
	AttestationFormat string
	Transports        string
	Flags             []byte
	ExtensionsJson    string
	Name              string
	Created           int64
	LastUsed          sql.NullInt64
}

type WebauthnUsers struct {
	RpID       string
	UserID     id.ID
	UserHandle []byte
	Created    int64
}
