// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

type AuditLog struct {
	ID     int64
	Actor  *id.ID
	Action string
	Target string
	Detail string
	At     int64
}

type Backups struct {
	UserID      id.ID
	Kind        int64
	DeviceID    id.ID
	ChunkSeq    int64
	BlobID      []byte
	ManifestSig []byte
	Created     int64
}

type Bans struct {
	CommunityID id.ID
	UserID      id.ID
	Reason      string
	ByUser      id.ID
	Created     int64
	Expires     sql.NullInt64
}

type BlobRefs struct {
	BlobID         []byte
	ChannelID      id.ID
	UploaderDevice id.ID
	Mime           string
	Created        int64
}

type BlobTombstones struct {
	BlobID  []byte
	Reason  string
	ByUser  id.ID
	Created int64
}

type Blobs struct {
	BlobID     []byte
	Size       int64
	StorageRef string
	Created    int64
	UnrefSince sql.NullInt64
}

type ChannelMembers struct {
	ChannelID id.ID
	UserID    id.ID
	Added     int64
}

type ChannelOverwrites struct {
	ChannelID  id.ID
	TargetKind int64
	TargetID   id.ID
	Allow      int64
	Deny       int64
}

type Channels struct {
	ID                id.ID
	CommunityID       *id.ID
	Kind              int64
	Mode              int64
	Visibility        int64
	ParentID          *id.ID
	Name              string
	Topic             string
	Position          int64
	SettingsJson      string
	HostPolicyVersion int64
	SlowmodeSeconds   int64
	Seq               int64
	Created           int64
	DeletedAt         sql.NullInt64
}

type Communities struct {
	ID                   id.ID
	Owner                id.ID
	Name                 string
	IconBlob             []byte
	PolicyJson           string
	PolicyVersion        int64
	MinAccountAgeSeconds int64
	RequireMod2fa        int64
	Created              int64
	DeletedAt            sql.NullInt64
}

type DeviceCursors struct {
	DeviceID  id.ID
	GroupID   id.ID
	LastSeq   int64
	LastEpoch int64
	Updated   int64
}

type DeviceLists struct {
	UserID       id.ID
	Version      int64
	Blob         []byte
	SskSignature []byte
	PrevHash     []byte
	Created      int64
}

type Devices struct {
	ID               id.ID
	UserID           id.ID
	DskPub           []byte
	Tier             int64
	SignerTier       int64
	CredentialBlob   []byte
	VerifiedAt       sql.NullInt64
	RevokedAt        sql.NullInt64
	QuarantinedAt    sql.NullInt64
	QuarantineReason string
	LastSeen         int64
	Created          int64
}

type ForkReports struct {
	GroupID        id.ID
	Seq            int64
	ReporterDevice id.ID
	Epoch          int64
	Reason         string
	Created        int64
}

type InstanceSettings struct {
	Key     string
	Value   []byte
	Updated int64
}

type Instances struct {
	InstanceID          id.ID
	ExternalSenderKeyID id.ID
	KeyHistory          []byte
	FrankingKeyID       id.ID
	Generation          int64
	PolicyVersion       int64
	Created             int64
}

type Invites struct {
	ID          id.ID
	CodeHash    []byte
	CommunityID *id.ID
	CreatedBy   *id.ID
	GrantsAdmin int64
	MaxUses     int64
	UsedCount   int64
	Created     int64
	ExpiresAt   int64
	RevokedAt   sql.NullInt64
}

type KeyPackages struct {
	DeviceID   id.ID
	KpRef      []byte
	Blob       []byte
	LastResort int64
	Expires    int64
	Created    int64
	ConsumedAt sql.NullInt64
}

type LoginAttempts struct {
	ID     int64
	UserID *id.ID
	Ip     string
	Method int64
	Ok     int64
	At     int64
}

type MemberRoles struct {
	CommunityID id.ID
	UserID      id.ID
	RoleID      id.ID
}

type Members struct {
	CommunityID id.ID
	UserID      id.ID
	Joined      int64
	Nick        string
}

type MlsAppMessages struct {
	GroupID        id.ID
	Seq            int64
	Epoch          int64
	UploaderDevice id.ID
	Blob           []byte
	CommitmentC    []byte
	FrankingTag    []byte
	Size           int64
	Created        int64
	Expires        sql.NullInt64
	DeletedAt      sql.NullInt64
	FrankingKeyID  id.ID
}

type MlsEpochTrees struct {
	GroupID     id.ID
	Epoch       int64
	RatchetTree []byte
	TreeHash    []byte
	Created     int64
}

type MlsGroups struct {
	GroupID                 id.ID
	Binding                 []byte
	Kind                    int64
	CommunityID             *id.ID
	TargetID                id.ID
	CallID                  *id.ID
	Ciphersuite             int64
	Epoch                   int64
	Seq                     int64
	GroupInfoBlob           []byte
	TreeHash                []byte
	PublicGroupState        []byte
	ExternalSenderKeyID     id.ID
	E2eeVersion             int64
	MediaVersion            int64
	PolicyVersion           int64
	EpochUnknown            int64
	HealDeadline            sql.NullInt64
	Created                 int64
	ClosedAt                sql.NullInt64
	PrunedBelow             int64
	HandshakesPrunedThrough int64
}

type MlsHandshakes struct {
	GroupID      id.ID
	Seq          int64
	Epoch        int64
	Kind         int64
	SenderLeaf   sql.NullInt64
	SenderDevice []byte
	Blob         []byte
	Created      int64
}

type MlsMembers struct {
	GroupID      id.ID
	LeafIndex    int64
	UserID       id.ID
	DeviceID     id.ID
	SignatureKey []byte
	AddedEpoch   int64
	RemovedEpoch sql.NullInt64
}

type MlsPendingProposals struct {
	GroupID      id.ID
	Ref          []byte
	Epoch        int64
	Kind         int64
	TargetLeaf   sql.NullInt64
	TargetDevice []byte
	KeyPackage   []byte
	Origin       int64
	ActionID     id.ID
	IssuedAt     int64
	Ttl          int64
	VoidAt       sql.NullInt64
}

type MlsWelcomePayloads struct {
	BlobSha256 []byte
	GroupID    id.ID
	Epoch      int64
	Blob       []byte
	Created    int64
}

type MlsWelcomes struct {
	WelcomeID   int64
	DeviceID    id.ID
	GroupID     id.ID
	Epoch       int64
	CommitSeq   int64
	BlobSha256  []byte
	Created     int64
	Expires     int64
	DeliveredAt sql.NullInt64
}

type OidcIdentities struct {
	Issuer  string
	Subject string
	UserID  id.ID
	Created int64
}

type PasswordCredentials struct {
	UserID  id.ID
	Phc     string
	Updated int64
}

type PendingJoins struct {
	GroupID  id.ID
	DeviceID id.ID
	Queued   int64
}

type ReadState struct {
	UserID      id.ID
	ChannelID   id.ID
	LastReadSeq int64
}

type ReadableMessages struct {
	ID             int64
	ChannelID      id.ID
	ChannelHex     string
	Seq            int64
	Sender         id.ID
	Envelope       []byte
	Body           string
	FrankingTag    []byte
	FrankingKeyID  id.ID
	MentionCount   int64
	Created        int64
	Edited         sql.NullInt64
	Deleted        sql.NullInt64
	BodyTsv        string
	UploaderDevice id.ID
	CommitmentC    []byte
}

type RecoveryCodes struct {
	UserID   id.ID
	CodeHash []byte
	Created  int64
	UsedAt   sql.NullInt64
}

type Reports struct {
	ID                 id.ID
	Reporter           id.ID
	GroupID            id.ID
	Seq                int64
	RevealedEnvelope   []byte
	KF                 []byte
	FrankingKeyID      id.ID
	VerificationResult string
	Status             int64
	Created            int64
}

type Roles struct {
	ID          id.ID
	CommunityID id.ID
	Name        string
	Color       int64
	Position    int64
	Allow       int64
	Deny        int64
	Hoist       int64
	Mentionable int64
	Created     int64
}

type Sessions struct {
	TokenHash   []byte
	DeviceID    id.ID
	UserID      id.ID
	Scope       int64
	Tier        int64
	Created     int64
	Expires     int64
	IdleExpires int64
}

type TotpSecrets struct {
	UserID      id.ID
	Secret      []byte
	Digits      int64
	Period      int64
	Algorithm   string
	ConfirmedAt sql.NullInt64
	LastCounter int64
	Created     int64
}

type Users struct {
	ID         id.ID
	Username   string
	Display    string
	Kind       int64
	UmkPub     []byte
	SskPub     []byte
	SigUmkSsk  []byte
	Flags      int64
	AgeBracket int64
	Created    int64
	DisabledAt sql.NullInt64
	DeletedAt  sql.NullInt64
}

type VoiceSessions struct {
	CallID      id.ID
	ChannelID   id.ID
	GroupID     *id.ID
	LivekitRoom string
	Started     int64
	Ended       sql.NullInt64
}

type WebauthnCeremonies struct {
	ID          id.ID
	Kind        int64
	UserID      *id.ID
	SessionJson string
	Created     int64
	Expires     int64
}

type WebauthnCredentials struct {
	CredID            []byte
	RpID              string
	UserID            id.ID
	PublicKey         []byte
	SignCount         int64
	AttestationType   string
	AttestationFormat string
	Transports        string
	Flags             []byte
	ExtensionsJson    string
	Name              string
	Created           int64
	LastUsed          sql.NullInt64
}

type WebauthnUsers struct {
	RpID       string
	UserID     id.ID
	UserHandle []byte
	Created    int64
}
