// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops.sql

package pgdb

import (
	"context"

	id "github.com/jonasthim/dilla/internal/id"
)

const getReport = `-- name: GetReport :one
SELECT id, reporter, group_id, seq, revealed_envelope, k_f, franking_key_id, verification_result, status, created FROM reports WHERE id = $1
`

type GetReportParams struct {
	ID id.ID
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (Reports, error) {
	row := q.db.QueryRowContext(ctx, getReport, arg.ID)
	var i Reports
	err := row.Scan(
		&i.ID,
		&i.Reporter,
		&i.GroupID,
		&i.Seq,
		&i.RevealedEnvelope,
		&i.KF,
		&i.FrankingKeyID,
		&i.VerificationResult,
		&i.Status,
		&i.Created,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (actor, action, target, detail, at) VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditParams struct {
	Actor  *id.ID
	Action string
	Target string
	Detail string
	At     int64
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Detail,
		arg.At,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor, action, target, detail, at FROM audit_log WHERE at >= $1 ORDER BY id DESC LIMIT $2::bigint
`

type ListAuditParams struct {
	At      int64
	MaxRows int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.At, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT id, reporter, group_id, seq, revealed_envelope, k_f, franking_key_id, verification_result, status, created FROM reports ORDER BY created DESC, id DESC LIMIT $1::bigint
`

type ListReportsParams struct {
	MaxRows int64
}

// GET /v1/reports (Plan 2 task 17): the queue, newest first, ties broken by id.
func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Reports, error) {
	rows, err := q.db.QueryContext(ctx, listReports, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reports{}
	for rows.Next() {
		var i Reports
		if err := rows.Scan(
			&i.ID,
			&i.Reporter,
			&i.GroupID,
			&i.Seq,
			&i.RevealedEnvelope,
			&i.KF,
			&i.FrankingKeyID,
			&i.VerificationResult,
			&i.Status,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putReport = `-- name: PutReport :exec
INSERT INTO reports (id, reporter, group_id, seq, revealed_envelope, k_f, franking_key_id, verification_result, status, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type PutReportParams struct {
	ID                 id.ID
	Reporter           id.ID
	GroupID            id.ID
	Seq                int64
	RevealedEnvelope   []byte
	KF                 []byte
	FrankingKeyID      id.ID
	VerificationResult string
	Status             int64
	Created            int64
}

func (q *Queries) PutReport(ctx context.Context, arg PutReportParams) error {
	_, err := q.db.ExecContext(ctx, putReport,
		arg.ID,
		arg.Reporter,
		arg.GroupID,
		arg.Seq,
		arg.RevealedEnvelope,
		arg.KF,
		arg.FrankingKeyID,
		arg.VerificationResult,
		arg.Status,
		arg.Created,
	)
	return err
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports SET status = $1, verification_result = $2 WHERE id = $3
`

type UpdateReportStatusParams struct {
	Status             int64
	VerificationResult string
	ID                 id.ID
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReportStatus, arg.Status, arg.VerificationResult, arg.ID)
	return err
}
