// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"context"

	id "github.com/jonasthim/dilla/internal/id"
)

type Querier interface {
	BumpGeneration(ctx context.Context) (int64, error)
	ClearLoginFailures(ctx context.Context, arg ClearLoginFailuresParams) error
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error)
	ConsumeTOTPCounter(ctx context.Context, arg ConsumeTOTPCounterParams) (int64, error)
	CountLoginFailures(ctx context.Context, arg CountLoginFailuresParams) (int64, error)
	CountRecoveryCodes(ctx context.Context, arg CountRecoveryCodesParams) (int64, error)
	CountSessionsByDevice(ctx context.Context, arg CountSessionsByDeviceParams) (int64, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	CreateInstance(ctx context.Context, arg CreateInstanceParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteCeremony(ctx context.Context, arg DeleteCeremonyParams) (int64, error)
	DeleteOldestSessionForDevice(ctx context.Context, arg DeleteOldestSessionForDeviceParams) error
	DeleteRecoveryCodes(ctx context.Context, arg DeleteRecoveryCodesParams) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteSessionsByDevice(ctx context.Context, arg DeleteSessionsByDeviceParams) (int64, error)
	DeleteSessionsByUser(ctx context.Context, arg DeleteSessionsByUserParams) (int64, error)
	GetCeremony(ctx context.Context, arg GetCeremonyParams) (WebauthnCeremonies, error)
	GetDevice(ctx context.Context, arg GetDeviceParams) (Devices, error)
	GetDeviceList(ctx context.Context, arg GetDeviceListParams) (DeviceLists, error)
	GetInstance(ctx context.Context) (Instances, error)
	GetInviteByHash(ctx context.Context, arg GetInviteByHashParams) (Invites, error)
	GetOIDCIdentity(ctx context.Context, arg GetOIDCIdentityParams) (id.ID, error)
	GetPasswordCredential(ctx context.Context, arg GetPasswordCredentialParams) (string, error)
	GetReport(ctx context.Context, arg GetReportParams) (Reports, error)
	GetSessionByHash(ctx context.Context, arg GetSessionByHashParams) (Sessions, error)
	GetSetting(ctx context.Context, arg GetSettingParams) ([]byte, error)
	GetTOTP(ctx context.Context, arg GetTOTPParams) (TotpSecrets, error)
	GetUser(ctx context.Context, arg GetUserParams) (Users, error)
	GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (Users, error)
	GetWebauthnCredential(ctx context.Context, arg GetWebauthnCredentialParams) (WebauthnCredentials, error)
	GetWebauthnUserByHandle(ctx context.Context, arg GetWebauthnUserByHandleParams) (id.ID, error)
	GetWebauthnUserHandle(ctx context.Context, arg GetWebauthnUserHandleParams) ([]byte, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error)
	ListDevicesByUser(ctx context.Context, arg ListDevicesByUserParams) ([]Devices, error)
	ListInvites(ctx context.Context) ([]Invites, error)
	ListInvitesByCommunity(ctx context.Context, arg ListInvitesByCommunityParams) ([]Invites, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	ListWebauthnCredentials(ctx context.Context, arg ListWebauthnCredentialsParams) ([]WebauthnCredentials, error)
	PruneCeremonies(ctx context.Context, arg PruneCeremoniesParams) (int64, error)
	PruneSessions(ctx context.Context, arg PruneSessionsParams) (int64, error)
	PutCeremony(ctx context.Context, arg PutCeremonyParams) error
	PutDeviceList(ctx context.Context, arg PutDeviceListParams) error
	PutOIDCIdentity(ctx context.Context, arg PutOIDCIdentityParams) error
	PutPasswordCredential(ctx context.Context, arg PutPasswordCredentialParams) error
	PutRecoveryCode(ctx context.Context, arg PutRecoveryCodeParams) error
	PutReport(ctx context.Context, arg PutReportParams) error
	PutSetting(ctx context.Context, arg PutSettingParams) error
	PutTOTP(ctx context.Context, arg PutTOTPParams) error
	PutWebauthnCredential(ctx context.Context, arg PutWebauthnCredentialParams) error
	// DO NOTHING, not DO UPDATE: a user handle is minted once and never rotated.
	// The authenticator stores the handle it saw at registration, so overwriting it
	// on a later ceremony makes GetWebauthnUserByHandle miss and permanently breaks
	// discoverable login for that account (deviation ID11).
	PutWebauthnUser(ctx context.Context, arg PutWebauthnUserParams) error
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	RedeemInvite(ctx context.Context, arg RedeemInviteParams) (Invites, error)
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	TombstoneUser(ctx context.Context, arg TombstoneUserParams) error
	TouchDevice(ctx context.Context, arg TouchDeviceParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error
	UpdateWebauthnCredential(ctx context.Context, arg UpdateWebauthnCredentialParams) error
}

var _ Querier = (*Queries)(nil)
