// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package pgdb

import (
	"context"

	id "github.com/jonasthim/dilla/internal/id"
)

const countSessionsByDevice = `-- name: CountSessionsByDevice :one
SELECT count(*) FROM sessions WHERE device_id = $1
`

type CountSessionsByDeviceParams struct {
	DeviceID id.ID
}

func (q *Queries) CountSessionsByDevice(ctx context.Context, arg CountSessionsByDeviceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsByDevice, arg.DeviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, device_id, user_id, scope, tier, created, expires, idle_expires)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSessionParams struct {
	TokenHash   []byte
	DeviceID    id.ID
	UserID      id.ID
	Scope       int64
	Tier        int64
	Created     int64
	Expires     int64
	IdleExpires int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.DeviceID,
		arg.UserID,
		arg.Scope,
		arg.Tier,
		arg.Created,
		arg.Expires,
		arg.IdleExpires,
	)
	return err
}

const deleteOldestSessionForDevice = `-- name: DeleteOldestSessionForDevice :exec
DELETE FROM sessions WHERE token_hash = (
  SELECT s.token_hash FROM sessions s WHERE s.device_id = $1 ORDER BY s.created LIMIT 1
)
`

type DeleteOldestSessionForDeviceParams struct {
	DeviceID id.ID
}

func (q *Queries) DeleteOldestSessionForDevice(ctx context.Context, arg DeleteOldestSessionForDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldestSessionForDevice, arg.DeviceID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

type DeleteSessionParams struct {
	TokenHash []byte
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.TokenHash)
	return err
}

const deleteSessionsByDevice = `-- name: DeleteSessionsByDevice :execrows
DELETE FROM sessions WHERE device_id = $1
`

type DeleteSessionsByDeviceParams struct {
	DeviceID id.ID
}

func (q *Queries) DeleteSessionsByDevice(ctx context.Context, arg DeleteSessionsByDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsByDevice, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :execrows
DELETE FROM sessions WHERE user_id = $1
`

type DeleteSessionsByUserParams struct {
	UserID id.ID
}

func (q *Queries) DeleteSessionsByUser(ctx context.Context, arg DeleteSessionsByUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsByUser, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT token_hash, device_id, user_id, scope, tier, created, expires, idle_expires FROM sessions WHERE token_hash = $1 AND expires > $2 AND idle_expires > $3
`

type GetSessionByHashParams struct {
	TokenHash   []byte
	Expires     int64
	IdleExpires int64
}

func (q *Queries) GetSessionByHash(ctx context.Context, arg GetSessionByHashParams) (Sessions, error) {
	row := q.db.QueryRowContext(ctx, getSessionByHash, arg.TokenHash, arg.Expires, arg.IdleExpires)
	var i Sessions
	err := row.Scan(
		&i.TokenHash,
		&i.DeviceID,
		&i.UserID,
		&i.Scope,
		&i.Tier,
		&i.Created,
		&i.Expires,
		&i.IdleExpires,
	)
	return i, err
}

const pruneSessions = `-- name: PruneSessions :execrows
DELETE FROM sessions WHERE expires <= $1 OR idle_expires <= $2
`

type PruneSessionsParams struct {
	Expires     int64
	IdleExpires int64
}

func (q *Queries) PruneSessions(ctx context.Context, arg PruneSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneSessions, arg.Expires, arg.IdleExpires)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET idle_expires = $1 WHERE token_hash = $2
`

type TouchSessionParams struct {
	IdleExpires int64
	TokenHash   []byte
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.IdleExpires, arg.TokenHash)
	return err
}
