// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: structure.sql

package pgdb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const createChannel = `-- name: CreateChannel :exec

INSERT INTO channels (id, community_id, kind, mode, visibility, parent_id, name, topic,
                      position, settings_json, host_policy_version, slowmode_seconds,
                      seq, created, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateChannelParams struct {
	ID                id.ID
	CommunityID       *id.ID
	Kind              int64
	Mode              int64
	Visibility        int64
	ParentID          *id.ID
	Name              string
	Topic             string
	Position          int64
	SettingsJson      string
	HostPolicyVersion int64
	SlowmodeSeconds   int64
	Seq               int64
	Created           int64
	DeletedAt         sql.NullInt64
}

// Channels (Plan 2 task 2, 00005_channels.sql).
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.ExecContext(ctx, createChannel,
		arg.ID,
		arg.CommunityID,
		arg.Kind,
		arg.Mode,
		arg.Visibility,
		arg.ParentID,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.SettingsJson,
		arg.HostPolicyVersion,
		arg.SlowmodeSeconds,
		arg.Seq,
		arg.Created,
		arg.DeletedAt,
	)
	return err
}

const createCommunity = `-- name: CreateCommunity :exec
INSERT INTO communities (id, owner, name, icon_blob, policy_json, policy_version,
                         min_account_age_seconds, require_mod_2fa, created, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateCommunityParams struct {
	ID                   id.ID
	Owner                id.ID
	Name                 string
	IconBlob             []byte
	PolicyJson           string
	PolicyVersion        int64
	MinAccountAgeSeconds int64
	RequireMod2fa        int64
	Created              int64
	DeletedAt            sql.NullInt64
}

func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) error {
	_, err := q.db.ExecContext(ctx, createCommunity,
		arg.ID,
		arg.Owner,
		arg.Name,
		arg.IconBlob,
		arg.PolicyJson,
		arg.PolicyVersion,
		arg.MinAccountAgeSeconds,
		arg.RequireMod2fa,
		arg.Created,
		arg.DeletedAt,
	)
	return err
}

const deleteBan = `-- name: DeleteBan :execrows
DELETE FROM bans WHERE community_id = $1 AND user_id = $2
`

type DeleteBanParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) DeleteBan(ctx context.Context, arg DeleteBanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBan, arg.CommunityID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChannel = `-- name: DeleteChannel :execrows
UPDATE channels SET deleted_at = $1 WHERE id = $2 AND deleted_at IS NULL
`

type DeleteChannelParams struct {
	DeletedAt sql.NullInt64
	ID        id.ID
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChannel, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChannelMember = `-- name: DeleteChannelMember :execrows
DELETE FROM channel_members WHERE channel_id = $1 AND user_id = $2
`

type DeleteChannelMemberParams struct {
	ChannelID id.ID
	UserID    id.ID
}

func (q *Queries) DeleteChannelMember(ctx context.Context, arg DeleteChannelMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChannelMember, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChannelsOfCommunity = `-- name: DeleteChannelsOfCommunity :execrows
UPDATE channels SET deleted_at = $1 WHERE community_id = $2 AND deleted_at IS NULL
`

type DeleteChannelsOfCommunityParams struct {
	DeletedAt   sql.NullInt64
	CommunityID *id.ID
}

func (q *Queries) DeleteChannelsOfCommunity(ctx context.Context, arg DeleteChannelsOfCommunityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChannelsOfCommunity, arg.DeletedAt, arg.CommunityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCommunityChannelMembers = `-- name: DeleteCommunityChannelMembers :execrows
DELETE FROM channel_members
WHERE user_id = $1
  AND channel_id IN (SELECT id FROM channels WHERE community_id = $2)
`

type DeleteCommunityChannelMembersParams struct {
	UserID      id.ID
	CommunityID *id.ID
}

// Fix wave C3: a kick, ban or leave drops the user from every channel of the community, in the
// transaction that removes the membership. A DM has no community and is never matched.
func (q *Queries) DeleteCommunityChannelMembers(ctx context.Context, arg DeleteCommunityChannelMembersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommunityChannelMembers, arg.UserID, arg.CommunityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM members WHERE community_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMember, arg.CommunityID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMemberRole = `-- name: DeleteMemberRole :execrows
DELETE FROM member_roles WHERE community_id = $1 AND user_id = $2 AND role_id = $3
`

type DeleteMemberRoleParams struct {
	CommunityID id.ID
	UserID      id.ID
	RoleID      id.ID
}

func (q *Queries) DeleteMemberRole(ctx context.Context, arg DeleteMemberRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemberRole, arg.CommunityID, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOverwrite = `-- name: DeleteOverwrite :execrows
DELETE FROM channel_overwrites WHERE channel_id = $1 AND target_kind = $2 AND target_id = $3
`

type DeleteOverwriteParams struct {
	ChannelID  id.ID
	TargetKind int64
	TargetID   id.ID
}

func (q *Queries) DeleteOverwrite(ctx context.Context, arg DeleteOverwriteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOverwrite, arg.ChannelID, arg.TargetKind, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND community_id = $2
`

type DeleteRoleParams struct {
	ID          id.ID
	CommunityID id.ID
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRole, arg.ID, arg.CommunityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserOverwrites = `-- name: DeleteUserOverwrites :execrows
DELETE FROM channel_overwrites
WHERE target_kind = 1 AND target_id = $1
  AND channel_id IN (SELECT id FROM channels WHERE community_id = $2)
`

type DeleteUserOverwritesParams struct {
	UserID      id.ID
	CommunityID *id.ID
}

// Fix wave I2: a kick, ban or leave drops the user's own (kind 1) overwrites in every channel of
// the community, in the transaction that removes the membership.
func (q *Queries) DeleteUserOverwrites(ctx context.Context, arg DeleteUserOverwritesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserOverwrites, arg.UserID, arg.CommunityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const endAllVoiceSessionRows = `-- name: EndAllVoiceSessionRows :exec
UPDATE voice_sessions SET ended = $1::bigint WHERE ended IS NULL
`

type EndAllVoiceSessionRowsParams struct {
	At int64
}

// Invariant 11's "Live calls end", the voice_sessions half of store.MLS.EndAllVoiceSessions
// (P2-D19): the call-group half is mls.sql's EndAllVoiceSessions.
func (q *Queries) EndAllVoiceSessionRows(ctx context.Context, arg EndAllVoiceSessionRowsParams) error {
	_, err := q.db.ExecContext(ctx, endAllVoiceSessionRows, arg.At)
	return err
}

const endVoiceSession = `-- name: EndVoiceSession :execrows
UPDATE voice_sessions SET ended = $1::bigint
WHERE call_id = $2 AND ended IS NULL
`

type EndVoiceSessionParams struct {
	At     int64
	CallID id.ID
}

func (q *Queries) EndVoiceSession(ctx context.Context, arg EndVoiceSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endVoiceSession, arg.At, arg.CallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBan = `-- name: GetBan :one
SELECT community_id, user_id, reason, by_user, created, expires
FROM bans WHERE community_id = $1 AND user_id = $2
`

type GetBanParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) GetBan(ctx context.Context, arg GetBanParams) (Bans, error) {
	row := q.db.QueryRowContext(ctx, getBan, arg.CommunityID, arg.UserID)
	var i Bans
	err := row.Scan(
		&i.CommunityID,
		&i.UserID,
		&i.Reason,
		&i.ByUser,
		&i.Created,
		&i.Expires,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, community_id, kind, mode, visibility, parent_id, name, topic, position,
       settings_json, host_policy_version, slowmode_seconds, seq, created, deleted_at
FROM channels WHERE id = $1 AND deleted_at IS NULL
`

type GetChannelParams struct {
	ID id.ID
}

func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (Channels, error) {
	row := q.db.QueryRowContext(ctx, getChannel, arg.ID)
	var i Channels
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Kind,
		&i.Mode,
		&i.Visibility,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.SettingsJson,
		&i.HostPolicyVersion,
		&i.SlowmodeSeconds,
		&i.Seq,
		&i.Created,
		&i.DeletedAt,
	)
	return i, err
}

const getCommunity = `-- name: GetCommunity :one
SELECT id, owner, name, icon_blob, policy_json, policy_version,
       min_account_age_seconds, require_mod_2fa, created, deleted_at
FROM communities
WHERE id = $1 AND deleted_at IS NULL
`

type GetCommunityParams struct {
	ID id.ID
}

func (q *Queries) GetCommunity(ctx context.Context, arg GetCommunityParams) (Communities, error) {
	row := q.db.QueryRowContext(ctx, getCommunity, arg.ID)
	var i Communities
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.IconBlob,
		&i.PolicyJson,
		&i.PolicyVersion,
		&i.MinAccountAgeSeconds,
		&i.RequireMod2fa,
		&i.Created,
		&i.DeletedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT community_id, user_id, joined, nick
FROM members WHERE community_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Members, error) {
	row := q.db.QueryRowContext(ctx, getMember, arg.CommunityID, arg.UserID)
	var i Members
	err := row.Scan(
		&i.CommunityID,
		&i.UserID,
		&i.Joined,
		&i.Nick,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, community_id, name, color, position, allow, deny, hoist, mentionable, created
FROM roles WHERE id = $1
`

type GetRoleParams struct {
	ID id.ID
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Roles, error) {
	row := q.db.QueryRowContext(ctx, getRole, arg.ID)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.Allow,
		&i.Deny,
		&i.Hoist,
		&i.Mentionable,
		&i.Created,
	)
	return i, err
}

const getVoiceSession = `-- name: GetVoiceSession :one
SELECT call_id, channel_id, group_id, livekit_room, started, ended
FROM voice_sessions WHERE call_id = $1
`

type GetVoiceSessionParams struct {
	CallID id.ID
}

func (q *Queries) GetVoiceSession(ctx context.Context, arg GetVoiceSessionParams) (VoiceSessions, error) {
	row := q.db.QueryRowContext(ctx, getVoiceSession, arg.CallID)
	var i VoiceSessions
	err := row.Scan(
		&i.CallID,
		&i.ChannelID,
		&i.GroupID,
		&i.LivekitRoom,
		&i.Started,
		&i.Ended,
	)
	return i, err
}

const listBans = `-- name: ListBans :many
SELECT community_id, user_id, reason, by_user, created, expires
FROM bans WHERE community_id = $1 ORDER BY created DESC, user_id
`

type ListBansParams struct {
	CommunityID id.ID
}

func (q *Queries) ListBans(ctx context.Context, arg ListBansParams) ([]Bans, error) {
	rows, err := q.db.QueryContext(ctx, listBans, arg.CommunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bans{}
	for rows.Next() {
		var i Bans
		if err := rows.Scan(
			&i.CommunityID,
			&i.UserID,
			&i.Reason,
			&i.ByUser,
			&i.Created,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMembers = `-- name: ListChannelMembers :many
SELECT user_id FROM channel_members WHERE channel_id = $1 ORDER BY user_id
`

type ListChannelMembersParams struct {
	ChannelID id.ID
}

func (q *Queries) ListChannelMembers(ctx context.Context, arg ListChannelMembersParams) ([]id.ID, error) {
	rows, err := q.db.QueryContext(ctx, listChannelMembers, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []id.ID{}
	for rows.Next() {
		var user_id id.ID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, community_id, kind, mode, visibility, parent_id, name, topic, position,
       settings_json, host_policy_version, slowmode_seconds, seq, created, deleted_at
FROM channels
WHERE community_id = $1 AND deleted_at IS NULL
ORDER BY position, id
`

type ListChannelsParams struct {
	CommunityID *id.ID
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channels, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, arg.CommunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channels{}
	for rows.Next() {
		var i Channels
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Kind,
			&i.Mode,
			&i.Visibility,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.SettingsJson,
			&i.HostPolicyVersion,
			&i.SlowmodeSeconds,
			&i.Seq,
			&i.Created,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForUser = `-- name: ListChannelsForUser :many
SELECT c.id, c.community_id, c.kind, c.mode, c.visibility, c.parent_id, c.name, c.topic,
       c.position, c.settings_json, c.host_policy_version, c.slowmode_seconds, c.seq,
       c.created, c.deleted_at
FROM channels c
JOIN channel_members m ON m.channel_id = c.id
WHERE m.user_id = $1 AND c.kind IN (3, 4) AND c.deleted_at IS NULL
ORDER BY c.created DESC, c.id
`

type ListChannelsForUserParams struct {
	UserID id.ID
}

// P2-D11: GET /v1/dms. The live DMs and group DMs (kinds 3 and 4) the user is a
// participant of, newest first, ties broken by id.
func (q *Queries) ListChannelsForUser(ctx context.Context, arg ListChannelsForUserParams) ([]Channels, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsForUser, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channels{}
	for rows.Next() {
		var i Channels
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Kind,
			&i.Mode,
			&i.Visibility,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.SettingsJson,
			&i.HostPolicyVersion,
			&i.SlowmodeSeconds,
			&i.Seq,
			&i.Created,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunities = `-- name: ListCommunities :many
SELECT id, owner, name, icon_blob, policy_json, policy_version,
       min_account_age_seconds, require_mod_2fa, created, deleted_at
FROM communities
WHERE id > $1 AND deleted_at IS NULL
ORDER BY id
LIMIT $2::bigint
`

type ListCommunitiesParams struct {
	ID      id.ID
	MaxRows int64
}

func (q *Queries) ListCommunities(ctx context.Context, arg ListCommunitiesParams) ([]Communities, error) {
	rows, err := q.db.QueryContext(ctx, listCommunities, arg.ID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Communities{}
	for rows.Next() {
		var i Communities
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.IconBlob,
			&i.PolicyJson,
			&i.PolicyVersion,
			&i.MinAccountAgeSeconds,
			&i.RequireMod2fa,
			&i.Created,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveVoiceSessions = `-- name: ListLiveVoiceSessions :many
SELECT call_id, channel_id, group_id, livekit_room, started, ended
FROM voice_sessions WHERE channel_id = $1 AND ended IS NULL
ORDER BY started, call_id
`

type ListLiveVoiceSessionsParams struct {
	ChannelID id.ID
}

func (q *Queries) ListLiveVoiceSessions(ctx context.Context, arg ListLiveVoiceSessionsParams) ([]VoiceSessions, error) {
	rows, err := q.db.QueryContext(ctx, listLiveVoiceSessions, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceSessions{}
	for rows.Next() {
		var i VoiceSessions
		if err := rows.Scan(
			&i.CallID,
			&i.ChannelID,
			&i.GroupID,
			&i.LivekitRoom,
			&i.Started,
			&i.Ended,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRoles = `-- name: ListMemberRoles :many
SELECT role_id FROM member_roles WHERE community_id = $1 AND user_id = $2 ORDER BY role_id
`

type ListMemberRolesParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) ListMemberRoles(ctx context.Context, arg ListMemberRolesParams) ([]id.ID, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRoles, arg.CommunityID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []id.ID{}
	for rows.Next() {
		var role_id id.ID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersOfCommunity = `-- name: ListMembersOfCommunity :many
SELECT community_id, user_id, joined, nick
FROM members
WHERE community_id = $1 AND user_id > $2
ORDER BY user_id
LIMIT $3::bigint
`

type ListMembersOfCommunityParams struct {
	CommunityID id.ID
	UserID      id.ID
	MaxRows     int64
}

func (q *Queries) ListMembersOfCommunity(ctx context.Context, arg ListMembersOfCommunityParams) ([]Members, error) {
	rows, err := q.db.QueryContext(ctx, listMembersOfCommunity, arg.CommunityID, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Members{}
	for rows.Next() {
		var i Members
		if err := rows.Scan(
			&i.CommunityID,
			&i.UserID,
			&i.Joined,
			&i.Nick,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverwrites = `-- name: ListOverwrites :many
SELECT channel_id, target_kind, target_id, allow, deny
FROM channel_overwrites WHERE channel_id = $1 ORDER BY target_kind, target_id
`

type ListOverwritesParams struct {
	ChannelID id.ID
}

func (q *Queries) ListOverwrites(ctx context.Context, arg ListOverwritesParams) ([]ChannelOverwrites, error) {
	rows, err := q.db.QueryContext(ctx, listOverwrites, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelOverwrites{}
	for rows.Next() {
		var i ChannelOverwrites
		if err := rows.Scan(
			&i.ChannelID,
			&i.TargetKind,
			&i.TargetID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, community_id, name, color, position, allow, deny, hoist, mentionable, created
FROM roles WHERE community_id = $1 ORDER BY position, id
`

type ListRolesParams struct {
	CommunityID id.ID
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Roles, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, arg.CommunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Roles{}
	for rows.Next() {
		var i Roles
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.Allow,
			&i.Deny,
			&i.Hoist,
			&i.Mentionable,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCommunity = `-- name: LockCommunity :one
SELECT id FROM communities WHERE id = $1 AND deleted_at IS NULL FOR NO KEY UPDATE
`

type LockCommunityParams struct {
	ID id.ID
}

// The join and the ban both take this lock before they read or write the
// membership, so a join's ban check and its member insert cannot interleave with
// a ban under READ COMMITTED. FOR NO KEY UPDATE: two lockers conflict, while the
// FOR KEY SHARE a foreign-key check on members or channels takes does not.
func (q *Queries) LockCommunity(ctx context.Context, arg LockCommunityParams) (id.ID, error) {
	row := q.db.QueryRowContext(ctx, lockCommunity, arg.ID)
	var id id.ID
	err := row.Scan(&id)
	return id, err
}

const nextChannelSeq = `-- name: NextChannelSeq :one
UPDATE channels SET seq = seq + 1 WHERE id = $1 AND deleted_at IS NULL RETURNING seq
`

type NextChannelSeqParams struct {
	ID id.ID
}

func (q *Queries) NextChannelSeq(ctx context.Context, arg NextChannelSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextChannelSeq, arg.ID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const putBan = `-- name: PutBan :exec

INSERT INTO bans (community_id, user_id, reason, by_user, created, expires)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (community_id, user_id) DO UPDATE SET
  reason = excluded.reason, by_user = excluded.by_user,
  created = excluded.created, expires = excluded.expires
`

type PutBanParams struct {
	CommunityID id.ID
	UserID      id.ID
	Reason      string
	ByUser      id.ID
	Created     int64
	Expires     sql.NullInt64
}

// Bans (Plan 2 task 4, 00007_bans.sql).
func (q *Queries) PutBan(ctx context.Context, arg PutBanParams) error {
	_, err := q.db.ExecContext(ctx, putBan,
		arg.CommunityID,
		arg.UserID,
		arg.Reason,
		arg.ByUser,
		arg.Created,
		arg.Expires,
	)
	return err
}

const putChannelMember = `-- name: PutChannelMember :exec

INSERT INTO channel_members (channel_id, user_id, added)
VALUES ($1, $2, $3) ON CONFLICT (channel_id, user_id) DO NOTHING
`

type PutChannelMemberParams struct {
	ChannelID id.ID
	UserID    id.ID
	Added     int64
}

// Channel members (Plan 2 task 6, 00008_channel_members.sql).
func (q *Queries) PutChannelMember(ctx context.Context, arg PutChannelMemberParams) error {
	_, err := q.db.ExecContext(ctx, putChannelMember, arg.ChannelID, arg.UserID, arg.Added)
	return err
}

const putMember = `-- name: PutMember :exec
INSERT INTO members (community_id, user_id, joined, nick)
VALUES ($1, $2, $3, $4)
ON CONFLICT (community_id, user_id) DO UPDATE SET nick = excluded.nick
`

type PutMemberParams struct {
	CommunityID id.ID
	UserID      id.ID
	Joined      int64
	Nick        string
}

func (q *Queries) PutMember(ctx context.Context, arg PutMemberParams) error {
	_, err := q.db.ExecContext(ctx, putMember,
		arg.CommunityID,
		arg.UserID,
		arg.Joined,
		arg.Nick,
	)
	return err
}

const putMemberRole = `-- name: PutMemberRole :exec
INSERT INTO member_roles (community_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (community_id, user_id, role_id) DO NOTHING
`

type PutMemberRoleParams struct {
	CommunityID id.ID
	UserID      id.ID
	RoleID      id.ID
}

func (q *Queries) PutMemberRole(ctx context.Context, arg PutMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, putMemberRole, arg.CommunityID, arg.UserID, arg.RoleID)
	return err
}

const putOverwrite = `-- name: PutOverwrite :exec

INSERT INTO channel_overwrites (channel_id, target_kind, target_id, allow, deny)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (channel_id, target_kind, target_id) DO UPDATE SET
  allow = excluded.allow, deny = excluded.deny
`

type PutOverwriteParams struct {
	ChannelID  id.ID
	TargetKind int64
	TargetID   id.ID
	Allow      int64
	Deny       int64
}

// Channel overwrites (Plan 2 task 3, 00006_overwrites.sql).
func (q *Queries) PutOverwrite(ctx context.Context, arg PutOverwriteParams) error {
	_, err := q.db.ExecContext(ctx, putOverwrite,
		arg.ChannelID,
		arg.TargetKind,
		arg.TargetID,
		arg.Allow,
		arg.Deny,
	)
	return err
}

const putRole = `-- name: PutRole :exec
INSERT INTO roles (id, community_id, name, color, position, allow, deny, hoist, mentionable, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name, color = excluded.color, position = excluded.position,
  allow = excluded.allow, deny = excluded.deny, hoist = excluded.hoist,
  mentionable = excluded.mentionable
`

type PutRoleParams struct {
	ID          id.ID
	CommunityID id.ID
	Name        string
	Color       int64
	Position    int64
	Allow       int64
	Deny        int64
	Hoist       int64
	Mentionable int64
	Created     int64
}

func (q *Queries) PutRole(ctx context.Context, arg PutRoleParams) error {
	_, err := q.db.ExecContext(ctx, putRole,
		arg.ID,
		arg.CommunityID,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.Allow,
		arg.Deny,
		arg.Hoist,
		arg.Mentionable,
		arg.Created,
	)
	return err
}

const putVoiceSession = `-- name: PutVoiceSession :exec

INSERT INTO voice_sessions (call_id, channel_id, group_id, livekit_room, started, ended)
VALUES ($1, $2, $3, $4, $5, NULL)
ON CONFLICT (call_id) DO UPDATE SET
  channel_id = excluded.channel_id, group_id = excluded.group_id,
  livekit_room = excluded.livekit_room, started = excluded.started, ended = NULL
WHERE voice_sessions.ended IS NOT NULL
`

type PutVoiceSessionParams struct {
	CallID      id.ID
	ChannelID   id.ID
	GroupID     *id.ID
	LivekitRoom string
	Started     int64
}

// Voice sessions (Plan 2 task 16, P2-D22, 00011_voice.sql).
// A call is keyed by its call group's call id (R9), so the next call of the same group reopens
// the ended row: the room, the group and the start are rewritten and ended is cleared. A live
// row is left exactly as it is, so two devices starting the same call at once both land in the
// one room the first wrote; the caller reads the row back to learn which.
func (q *Queries) PutVoiceSession(ctx context.Context, arg PutVoiceSessionParams) error {
	_, err := q.db.ExecContext(ctx, putVoiceSession,
		arg.CallID,
		arg.ChannelID,
		arg.GroupID,
		arg.LivekitRoom,
		arg.Started,
	)
	return err
}

const softDeleteCommunity = `-- name: SoftDeleteCommunity :execrows
UPDATE communities SET deleted_at = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteCommunityParams struct {
	DeletedAt sql.NullInt64
	ID        id.ID
}

func (q *Queries) SoftDeleteCommunity(ctx context.Context, arg SoftDeleteCommunityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteCommunity, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateChannel = `-- name: UpdateChannel :execrows
UPDATE channels
SET mode = $1, visibility = $2, parent_id = $3, name = $4, topic = $5, position = $6,
    settings_json = $7, host_policy_version = $8, slowmode_seconds = $9
WHERE id = $10 AND deleted_at IS NULL
`

type UpdateChannelParams struct {
	Mode              int64
	Visibility        int64
	ParentID          *id.ID
	Name              string
	Topic             string
	Position          int64
	SettingsJson      string
	HostPolicyVersion int64
	SlowmodeSeconds   int64
	ID                id.ID
}

// kind, community_id, seq and created are not written: a channel's kind and home
// are immutable, and seq moves only through NextChannelSeq.
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChannel,
		arg.Mode,
		arg.Visibility,
		arg.ParentID,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.SettingsJson,
		arg.HostPolicyVersion,
		arg.SlowmodeSeconds,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCommunityMeta = `-- name: UpdateCommunityMeta :execrows
UPDATE communities
SET name = $1, min_account_age_seconds = $2, require_mod_2fa = $3
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateCommunityMetaParams struct {
	Name                 string
	MinAccountAgeSeconds int64
	RequireMod2fa        int64
	ID                   id.ID
}

func (q *Queries) UpdateCommunityMeta(ctx context.Context, arg UpdateCommunityMetaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommunityMeta,
		arg.Name,
		arg.MinAccountAgeSeconds,
		arg.RequireMod2fa,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCommunityPolicy = `-- name: UpdateCommunityPolicy :execrows
UPDATE communities
SET policy_json = $1, policy_version = $2
WHERE id = $3 AND deleted_at IS NULL
  AND policy_version < $2::bigint
`

type UpdateCommunityPolicyParams struct {
	PolicyJson    string
	PolicyVersion int64
	ID            id.ID
}

// The version is MONOTONE: two writers that read the same version both compute
// the same successor, and the second must not land a different policy under a
// number clients already hold. Zero rows is either an unknown community or a
// lost race; the adapter tells the two apart.
func (q *Queries) UpdateCommunityPolicy(ctx context.Context, arg UpdateCommunityPolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommunityPolicy, arg.PolicyJson, arg.PolicyVersion, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
