// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlitedb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, display, kind, umk_pub, ssk_pub, sig_umk_ssk, flags, age_bracket, created, disabled_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID         id.ID
	Username   string
	Display    string
	Kind       int64
	UmkPub     []byte
	SskPub     []byte
	SigUmkSsk  []byte
	Flags      int64
	AgeBracket int64
	Created    int64
	DisabledAt sql.NullInt64
	DeletedAt  sql.NullInt64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Display,
		arg.Kind,
		arg.UmkPub,
		arg.SskPub,
		arg.SigUmkSsk,
		arg.Flags,
		arg.AgeBracket,
		arg.Created,
		arg.DisabledAt,
		arg.DeletedAt,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, display, kind, umk_pub, ssk_pub, sig_umk_ssk, flags, age_bracket, created, disabled_at, deleted_at FROM users WHERE id = ?
`

type GetUserParams struct {
	ID id.ID
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.ID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Display,
		&i.Kind,
		&i.UmkPub,
		&i.SskPub,
		&i.SigUmkSsk,
		&i.Flags,
		&i.AgeBracket,
		&i.Created,
		&i.DisabledAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display, kind, umk_pub, ssk_pub, sig_umk_ssk, flags, age_bracket, created, disabled_at, deleted_at FROM users WHERE username = ?
`

type GetUserByUsernameParams struct {
	Username string
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, arg.Username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Display,
		&i.Kind,
		&i.UmkPub,
		&i.SskPub,
		&i.SigUmkSsk,
		&i.Flags,
		&i.AgeBracket,
		&i.Created,
		&i.DisabledAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display, kind, umk_pub, ssk_pub, sig_umk_ssk, flags, age_bracket, created, disabled_at, deleted_at FROM users WHERE id > ? ORDER BY id LIMIT ?2
`

type ListUsersParams struct {
	ID      id.ID
	MaxRows int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.ID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Display,
			&i.Kind,
			&i.UmkPub,
			&i.SskPub,
			&i.SigUmkSsk,
			&i.Flags,
			&i.AgeBracket,
			&i.Created,
			&i.DisabledAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users SET disabled_at = ? WHERE id = ?
`

type SetUserDisabledParams struct {
	DisabledAt sql.NullInt64
	ID         id.ID
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setUserDisabled, arg.DisabledAt, arg.ID)
	return err
}

const tombstoneUser = `-- name: TombstoneUser :exec
UPDATE users SET deleted_at = ?, display = '', umk_pub = zeroblob(32), ssk_pub = zeroblob(32),
                 sig_umk_ssk = zeroblob(64), flags = 0
WHERE id = ?
`

type TombstoneUserParams struct {
	DeletedAt sql.NullInt64
	ID        id.ID
}

func (q *Queries) TombstoneUser(ctx context.Context, arg TombstoneUserParams) error {
	_, err := q.db.ExecContext(ctx, tombstoneUser, arg.DeletedAt, arg.ID)
	return err
}
