// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package sqlitedb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const clearBlobUnreferenced = `-- name: ClearBlobUnreferenced :exec
UPDATE blobs SET unref_since = NULL WHERE blobs.blob_id = ?
`

type ClearBlobUnreferencedParams struct {
	BlobID []byte
}

func (q *Queries) ClearBlobUnreferenced(ctx context.Context, arg ClearBlobUnreferencedParams) error {
	_, err := q.db.ExecContext(ctx, clearBlobUnreferenced, arg.BlobID)
	return err
}

const countBlobRefs = `-- name: CountBlobRefs :one
SELECT COUNT(*) FROM blob_refs WHERE blob_id = ?
`

type CountBlobRefsParams struct {
	BlobID []byte
}

func (q *Queries) CountBlobRefs(ctx context.Context, arg CountBlobRefsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlobRefs, arg.BlobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlob = `-- name: DeleteBlob :execrows
DELETE FROM blobs WHERE blob_id = ?
`

type DeleteBlobParams struct {
	BlobID []byte
}

func (q *Queries) DeleteBlob(ctx context.Context, arg DeleteBlobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBlob, arg.BlobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBlobRef = `-- name: DeleteBlobRef :exec
DELETE FROM blob_refs WHERE blob_id = ? AND channel_id = ?
`

type DeleteBlobRefParams struct {
	BlobID    []byte
	ChannelID id.ID
}

func (q *Queries) DeleteBlobRef(ctx context.Context, arg DeleteBlobRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlobRef, arg.BlobID, arg.ChannelID)
	return err
}

const getBlob = `-- name: GetBlob :one
SELECT blob_id, size, storage_ref, created, unref_since FROM blobs WHERE blob_id = ?
`

type GetBlobParams struct {
	BlobID []byte
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (Blobs, error) {
	row := q.db.QueryRowContext(ctx, getBlob, arg.BlobID)
	var i Blobs
	err := row.Scan(
		&i.BlobID,
		&i.Size,
		&i.StorageRef,
		&i.Created,
		&i.UnrefSince,
	)
	return i, err
}

const getBlobRef = `-- name: GetBlobRef :one
SELECT blob_id, channel_id, uploader_device, mime, created
FROM blob_refs WHERE blob_id = ? AND channel_id = ?
`

type GetBlobRefParams struct {
	BlobID    []byte
	ChannelID id.ID
}

func (q *Queries) GetBlobRef(ctx context.Context, arg GetBlobRefParams) (BlobRefs, error) {
	row := q.db.QueryRowContext(ctx, getBlobRef, arg.BlobID, arg.ChannelID)
	var i BlobRefs
	err := row.Scan(
		&i.BlobID,
		&i.ChannelID,
		&i.UploaderDevice,
		&i.Mime,
		&i.Created,
	)
	return i, err
}

const getBlobTombstone = `-- name: GetBlobTombstone :one
SELECT COUNT(*) FROM blob_tombstones WHERE blob_id = ?
`

type GetBlobTombstoneParams struct {
	BlobID []byte
}

// COUNT, not EXISTS: EXISTS is int64 on SQLite and bool on Postgres, and the two Querier
// interfaces must stay identical.
func (q *Queries) GetBlobTombstone(ctx context.Context, arg GetBlobTombstoneParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlobTombstone, arg.BlobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listBackups = `-- name: ListBackups :many
SELECT user_id, kind, device_id, chunk_seq, blob_id, manifest_sig, created
FROM backups WHERE user_id = ? AND kind = ?
ORDER BY device_id, chunk_seq
`

type ListBackupsParams struct {
	UserID id.ID
	Kind   int64
}

func (q *Queries) ListBackups(ctx context.Context, arg ListBackupsParams) ([]Backups, error) {
	rows, err := q.db.QueryContext(ctx, listBackups, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backups{}
	for rows.Next() {
		var i Backups
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.DeviceID,
			&i.ChunkSeq,
			&i.BlobID,
			&i.ManifestSig,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectableBlobs = `-- name: ListCollectableBlobs :many
SELECT blobs.blob_id, blobs.size, blobs.storage_ref, blobs.created, blobs.unref_since FROM blobs
WHERE blobs.unref_since IS NOT NULL AND blobs.unref_since < CAST(?1 AS INTEGER)
  AND NOT EXISTS (SELECT 1 FROM blob_refs WHERE blob_refs.blob_id = blobs.blob_id)
ORDER BY blobs.unref_since
LIMIT ?2
`

type ListCollectableBlobsParams struct {
	Before  int64
	MaxRows int64
}

// The CAST keeps the parameter an int64: without it sqlc infers *int64 from the nullable
// unref_since, and a nil cutoff would compare against NULL and collect nothing (gap-47 section 19.4).
func (q *Queries) ListCollectableBlobs(ctx context.Context, arg ListCollectableBlobsParams) ([]Blobs, error) {
	rows, err := q.db.QueryContext(ctx, listCollectableBlobs, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blobs{}
	for rows.Next() {
		var i Blobs
		if err := rows.Scan(
			&i.BlobID,
			&i.Size,
			&i.StorageRef,
			&i.Created,
			&i.UnrefSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBlobUnreferenced = `-- name: MarkBlobUnreferenced :exec
UPDATE blobs SET unref_since = ?1
WHERE blobs.blob_id = ?2
  AND blobs.unref_since IS NULL
  AND NOT EXISTS (SELECT 1 FROM blob_refs WHERE blob_refs.blob_id = blobs.blob_id)
`

type MarkBlobUnreferencedParams struct {
	At     sql.NullInt64
	BlobID []byte
}

// Sets the mark only when no reference is left, and only when it is not already set, so a
// repeated delete cannot push collection back.
func (q *Queries) MarkBlobUnreferenced(ctx context.Context, arg MarkBlobUnreferencedParams) error {
	_, err := q.db.ExecContext(ctx, markBlobUnreferenced, arg.At, arg.BlobID)
	return err
}

const putBackup = `-- name: PutBackup :exec
INSERT INTO backups (user_id, kind, device_id, chunk_seq, blob_id, manifest_sig, created)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, kind, device_id, chunk_seq) DO UPDATE SET
  blob_id = excluded.blob_id, manifest_sig = excluded.manifest_sig, created = excluded.created
`

type PutBackupParams struct {
	UserID      id.ID
	Kind        int64
	DeviceID    id.ID
	ChunkSeq    int64
	BlobID      []byte
	ManifestSig []byte
	Created     int64
}

// One row per (user, kind, device, chunk); a re-upload of the same chunk replaces it.
func (q *Queries) PutBackup(ctx context.Context, arg PutBackupParams) error {
	_, err := q.db.ExecContext(ctx, putBackup,
		arg.UserID,
		arg.Kind,
		arg.DeviceID,
		arg.ChunkSeq,
		arg.BlobID,
		arg.ManifestSig,
		arg.Created,
	)
	return err
}

const putBlob = `-- name: PutBlob :exec

INSERT INTO blobs (blob_id, size, storage_ref, created, unref_since)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (blob_id) DO NOTHING
`

type PutBlobParams struct {
	BlobID     []byte
	Size       int64
	StorageRef string
	Created    int64
	UnrefSince sql.NullInt64
}

// Blobs, blob references and tombstones (Plan 2 task 10, 00010_blobs.sql). Every column in a
// statement with a subquery is qualified: sqlc's analyser calls a bare blob_id ambiguous as soon
// as a second table is in scope (gap-47 section 19.4, C11).
// Content addressing makes a second insert of the same id the same object, so it is a no-op
// rather than a conflict: two uploads of the same bytes may race to here.
func (q *Queries) PutBlob(ctx context.Context, arg PutBlobParams) error {
	_, err := q.db.ExecContext(ctx, putBlob,
		arg.BlobID,
		arg.Size,
		arg.StorageRef,
		arg.Created,
		arg.UnrefSince,
	)
	return err
}

const putBlobRef = `-- name: PutBlobRef :exec
INSERT INTO blob_refs (blob_id, channel_id, uploader_device, mime, created)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (blob_id, channel_id) DO NOTHING
`

type PutBlobRefParams struct {
	BlobID         []byte
	ChannelID      id.ID
	UploaderDevice id.ID
	Mime           string
	Created        int64
}

// One reference per (blob, channel); a repeat keeps the first uploader.
func (q *Queries) PutBlobRef(ctx context.Context, arg PutBlobRefParams) error {
	_, err := q.db.ExecContext(ctx, putBlobRef,
		arg.BlobID,
		arg.ChannelID,
		arg.UploaderDevice,
		arg.Mime,
		arg.Created,
	)
	return err
}

const putBlobTombstone = `-- name: PutBlobTombstone :exec
INSERT INTO blob_tombstones (blob_id, reason, by_user, created)
VALUES (?, ?, ?, ?)
ON CONFLICT (blob_id) DO NOTHING
`

type PutBlobTombstoneParams struct {
	BlobID  []byte
	Reason  string
	ByUser  id.ID
	Created int64
}

// The first purge's record stands.
func (q *Queries) PutBlobTombstone(ctx context.Context, arg PutBlobTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, putBlobTombstone,
		arg.BlobID,
		arg.Reason,
		arg.ByUser,
		arg.Created,
	)
	return err
}

const userBlobBytes = `-- name: UserBlobBytes :one
SELECT CAST(COALESCE(SUM(b.size), 0) AS INTEGER) FROM blobs b
WHERE b.blob_id IN (
  SELECT DISTINCT r.blob_id FROM blob_refs r
  JOIN devices d ON d.id = r.uploader_device
  WHERE d.user_id = ?1
)
`

type UserBlobBytesParams struct {
	UserID id.ID
}

// The quota counts each distinct blob a user uploaded once, however many
// channels they published it into.
func (q *Queries) UserBlobBytes(ctx context.Context, arg UserBlobBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userBlobBytes, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
