// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlitedb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, code_hash, community_id, created_by, grants_admin, max_uses, used_count, created, expires_at, revoked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInviteParams struct {
	ID          id.ID
	CodeHash    []byte
	CommunityID *id.ID
	CreatedBy   *id.ID
	GrantsAdmin int64
	MaxUses     int64
	UsedCount   int64
	Created     int64
	ExpiresAt   int64
	RevokedAt   sql.NullInt64
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.CodeHash,
		arg.CommunityID,
		arg.CreatedBy,
		arg.GrantsAdmin,
		arg.MaxUses,
		arg.UsedCount,
		arg.Created,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}

const getInviteByHash = `-- name: GetInviteByHash :one
SELECT id, code_hash, community_id, created_by, grants_admin, max_uses, used_count, created, expires_at, revoked_at FROM invites WHERE code_hash = ?
`

type GetInviteByHashParams struct {
	CodeHash []byte
}

func (q *Queries) GetInviteByHash(ctx context.Context, arg GetInviteByHashParams) (Invites, error) {
	row := q.db.QueryRowContext(ctx, getInviteByHash, arg.CodeHash)
	var i Invites
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CommunityID,
		&i.CreatedBy,
		&i.GrantsAdmin,
		&i.MaxUses,
		&i.UsedCount,
		&i.Created,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, code_hash, community_id, created_by, grants_admin, max_uses, used_count, created, expires_at, revoked_at FROM invites ORDER BY created DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invites, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invites{}
	for rows.Next() {
		var i Invites
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.CommunityID,
			&i.CreatedBy,
			&i.GrantsAdmin,
			&i.MaxUses,
			&i.UsedCount,
			&i.Created,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitesByCommunity = `-- name: ListInvitesByCommunity :many
SELECT id, code_hash, community_id, created_by, grants_admin, max_uses, used_count, created, expires_at, revoked_at FROM invites WHERE community_id = ? ORDER BY created DESC
`

type ListInvitesByCommunityParams struct {
	CommunityID *id.ID
}

func (q *Queries) ListInvitesByCommunity(ctx context.Context, arg ListInvitesByCommunityParams) ([]Invites, error) {
	rows, err := q.db.QueryContext(ctx, listInvitesByCommunity, arg.CommunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invites{}
	for rows.Next() {
		var i Invites
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.CommunityID,
			&i.CreatedBy,
			&i.GrantsAdmin,
			&i.MaxUses,
			&i.UsedCount,
			&i.Created,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvite = `-- name: RedeemInvite :one
UPDATE invites SET used_count = used_count + 1
WHERE code_hash = ? AND used_count < max_uses AND revoked_at IS NULL AND expires_at > ?
RETURNING id, code_hash, community_id, created_by, grants_admin, max_uses, used_count, created, expires_at, revoked_at
`

type RedeemInviteParams struct {
	CodeHash  []byte
	ExpiresAt int64
}

func (q *Queries) RedeemInvite(ctx context.Context, arg RedeemInviteParams) (Invites, error) {
	row := q.db.QueryRowContext(ctx, redeemInvite, arg.CodeHash, arg.ExpiresAt)
	var i Invites
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CommunityID,
		&i.CreatedBy,
		&i.GrantsAdmin,
		&i.MaxUses,
		&i.UsedCount,
		&i.Created,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites SET revoked_at = ? WHERE id = ?
`

type RevokeInviteParams struct {
	RevokedAt sql.NullInt64
	ID        id.ID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.ExecContext(ctx, revokeInvite, arg.RevokedAt, arg.ID)
	return err
}
