// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mls.sql

package sqlitedb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const appendHandshake = `-- name: AppendHandshake :exec
INSERT INTO mls_handshakes (group_id, seq, epoch, kind, sender_leaf, sender_device, blob, created)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendHandshakeParams struct {
	GroupID      id.ID
	Seq          int64
	Epoch        int64
	Kind         int64
	SenderLeaf   sql.NullInt64
	SenderDevice []byte
	Blob         []byte
	Created      int64
}

func (q *Queries) AppendHandshake(ctx context.Context, arg AppendHandshakeParams) error {
	_, err := q.db.ExecContext(ctx, appendHandshake,
		arg.GroupID,
		arg.Seq,
		arg.Epoch,
		arg.Kind,
		arg.SenderLeaf,
		arg.SenderDevice,
		arg.Blob,
		arg.Created,
	)
	return err
}

const bumpGroupSeq = `-- name: BumpGroupSeq :one
UPDATE mls_groups SET seq = seq + 1 WHERE group_id = ? RETURNING seq
`

type BumpGroupSeqParams struct {
	GroupID id.ID
}

func (q *Queries) BumpGroupSeq(ctx context.Context, arg BumpGroupSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpGroupSeq, arg.GroupID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const clearEpochUnknown = `-- name: ClearEpochUnknown :exec
UPDATE mls_groups SET epoch_unknown = 0, heal_deadline = NULL WHERE group_id = ?
`

type ClearEpochUnknownParams struct {
	GroupID id.ID
}

// An adopted heal. The deadline goes with the flag: closeUnhealedGroups reads the pair, and a
// healed group that kept its deadline would be one restart away from looking overdue again.
func (q *Queries) ClearEpochUnknown(ctx context.Context, arg ClearEpochUnknownParams) error {
	_, err := q.db.ExecContext(ctx, clearEpochUnknown, arg.GroupID)
	return err
}

const closeGroup = `-- name: CloseGroup :exec
UPDATE mls_groups SET closed_at = ? WHERE group_id = ?
`

type CloseGroupParams struct {
	ClosedAt sql.NullInt64
	GroupID  id.ID
}

func (q *Queries) CloseGroup(ctx context.Context, arg CloseGroupParams) error {
	_, err := q.db.ExecContext(ctx, closeGroup, arg.ClosedAt, arg.GroupID)
	return err
}

const countForkReporters = `-- name: CountForkReporters :one
SELECT count(*) FROM fork_reports WHERE group_id = ? AND seq = ?
`

type CountForkReportersParams struct {
	GroupID id.ID
	Seq     int64
}

func (q *Queries) CountForkReporters(ctx context.Context, arg CountForkReportersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countForkReporters, arg.GroupID, arg.Seq)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKeyPackages = `-- name: CountKeyPackages :one
SELECT count(*) FROM key_packages
WHERE device_id = ? AND consumed_at IS NULL AND last_resort = 0 AND expires > ?
`

type CountKeyPackagesParams struct {
	DeviceID id.ID
	Expires  int64
}

func (q *Queries) CountKeyPackages(ctx context.Context, arg CountKeyPackagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKeyPackages, arg.DeviceID, arg.Expires)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO mls_groups (group_id, binding, kind, community_id, target_id, call_id, ciphersuite,
                        epoch, seq, group_info_blob, tree_hash, public_group_state,
                        external_sender_key_id, e2ee_version, media_version, policy_version,
                        epoch_unknown, heal_deadline, created, closed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGroupParams struct {
	GroupID             id.ID
	Binding             []byte
	Kind                int64
	CommunityID         *id.ID
	TargetID            id.ID
	CallID              *id.ID
	Ciphersuite         int64
	Epoch               int64
	Seq                 int64
	GroupInfoBlob       []byte
	TreeHash            []byte
	PublicGroupState    []byte
	ExternalSenderKeyID id.ID
	E2eeVersion         int64
	MediaVersion        int64
	PolicyVersion       int64
	EpochUnknown        int64
	HealDeadline        sql.NullInt64
	Created             int64
	ClosedAt            sql.NullInt64
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup,
		arg.GroupID,
		arg.Binding,
		arg.Kind,
		arg.CommunityID,
		arg.TargetID,
		arg.CallID,
		arg.Ciphersuite,
		arg.Epoch,
		arg.Seq,
		arg.GroupInfoBlob,
		arg.TreeHash,
		arg.PublicGroupState,
		arg.ExternalSenderKeyID,
		arg.E2eeVersion,
		arg.MediaVersion,
		arg.PolicyVersion,
		arg.EpochUnknown,
		arg.HealDeadline,
		arg.Created,
		arg.ClosedAt,
	)
	return err
}

const deleteMembers = `-- name: DeleteMembers :exec
DELETE FROM mls_members WHERE group_id = ?
`

type DeleteMembersParams struct {
	GroupID id.ID
}

func (q *Queries) DeleteMembers(ctx context.Context, arg DeleteMembersParams) error {
	_, err := q.db.ExecContext(ctx, deleteMembers, arg.GroupID)
	return err
}

const deleteOtherLastResortKeyPackages = `-- name: DeleteOtherLastResortKeyPackages :exec
DELETE FROM key_packages
WHERE device_id = ? AND last_resort = 1 AND kp_ref <> ?
`

type DeleteOtherLastResortKeyPackagesParams struct {
	DeviceID id.ID
	KpRef    []byte
}

func (q *Queries) DeleteOtherLastResortKeyPackages(ctx context.Context, arg DeleteOtherLastResortKeyPackagesParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherLastResortKeyPackages, arg.DeviceID, arg.KpRef)
	return err
}

const deleteProposal = `-- name: DeleteProposal :exec
DELETE FROM mls_pending_proposals WHERE group_id = ? AND ref = ?
`

type DeleteProposalParams struct {
	GroupID id.ID
	Ref     []byte
}

func (q *Queries) DeleteProposal(ctx context.Context, arg DeleteProposalParams) error {
	_, err := q.db.ExecContext(ctx, deleteProposal, arg.GroupID, arg.Ref)
	return err
}

const deleteWelcome = `-- name: DeleteWelcome :exec
UPDATE mls_welcomes SET delivered_at = ? WHERE device_id = ? AND welcome_id = ?
`

type DeleteWelcomeParams struct {
	DeliveredAt sql.NullInt64
	DeviceID    id.ID
	WelcomeID   int64
}

func (q *Queries) DeleteWelcome(ctx context.Context, arg DeleteWelcomeParams) error {
	_, err := q.db.ExecContext(ctx, deleteWelcome, arg.DeliveredAt, arg.DeviceID, arg.WelcomeID)
	return err
}

const endAllVoiceSessions = `-- name: EndAllVoiceSessions :exec
UPDATE mls_groups SET closed_at = CAST(?1 AS INTEGER)
WHERE call_id IS NOT NULL AND closed_at IS NULL
`

type EndAllVoiceSessionsParams struct {
	At int64
}

// Invariant 11's "Live calls end." A live call IS its call group (R9 puts the call id in the
// companion column), and `voice_sessions` is Plan 2's table -- so on a Plan-1 database the whole
// of "end every live call" is closing the call groups. Plan 2 task 1 extends the same statement
// to `voice_sessions` rather than declaring a second method (deviation B13, P2-D19).
func (q *Queries) EndAllVoiceSessions(ctx context.Context, arg EndAllVoiceSessionsParams) error {
	_, err := q.db.ExecContext(ctx, endAllVoiceSessions, arg.At)
	return err
}

const getCommitAtEpoch = `-- name: GetCommitAtEpoch :one
SELECT group_id, seq, epoch, kind, sender_leaf, sender_device, blob, created FROM mls_handshakes
WHERE group_id = ? AND epoch = ? AND kind IN (1, 2)
ORDER BY seq LIMIT 1
`

type GetCommitAtEpochParams struct {
	GroupID id.ID
	Epoch   int64
}

func (q *Queries) GetCommitAtEpoch(ctx context.Context, arg GetCommitAtEpochParams) (MlsHandshakes, error) {
	row := q.db.QueryRowContext(ctx, getCommitAtEpoch, arg.GroupID, arg.Epoch)
	var i MlsHandshakes
	err := row.Scan(
		&i.GroupID,
		&i.Seq,
		&i.Epoch,
		&i.Kind,
		&i.SenderLeaf,
		&i.SenderDevice,
		&i.Blob,
		&i.Created,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT group_id, binding, kind, community_id, target_id, call_id, ciphersuite, epoch, seq, group_info_blob, tree_hash, public_group_state, external_sender_key_id, e2ee_version, media_version, policy_version, epoch_unknown, heal_deadline, created, closed_at, pruned_below FROM mls_groups WHERE group_id = ?
`

type GetGroupParams struct {
	GroupID id.ID
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (MlsGroups, error) {
	row := q.db.QueryRowContext(ctx, getGroup, arg.GroupID)
	var i MlsGroups
	err := row.Scan(
		&i.GroupID,
		&i.Binding,
		&i.Kind,
		&i.CommunityID,
		&i.TargetID,
		&i.CallID,
		&i.Ciphersuite,
		&i.Epoch,
		&i.Seq,
		&i.GroupInfoBlob,
		&i.TreeHash,
		&i.PublicGroupState,
		&i.ExternalSenderKeyID,
		&i.E2eeVersion,
		&i.MediaVersion,
		&i.PolicyVersion,
		&i.EpochUnknown,
		&i.HealDeadline,
		&i.Created,
		&i.ClosedAt,
		&i.PrunedBelow,
	)
	return i, err
}

const getLastResortKeyPackage = `-- name: GetLastResortKeyPackage :one
SELECT device_id, kp_ref, blob, last_resort, expires, created, consumed_at FROM key_packages
WHERE device_id = ? AND consumed_at IS NULL AND last_resort = 1 AND expires > ?
ORDER BY expires DESC, kp_ref LIMIT 1
`

type GetLastResortKeyPackageParams struct {
	DeviceID id.ID
	Expires  int64
}

func (q *Queries) GetLastResortKeyPackage(ctx context.Context, arg GetLastResortKeyPackageParams) (KeyPackages, error) {
	row := q.db.QueryRowContext(ctx, getLastResortKeyPackage, arg.DeviceID, arg.Expires)
	var i KeyPackages
	err := row.Scan(
		&i.DeviceID,
		&i.KpRef,
		&i.Blob,
		&i.LastResort,
		&i.Expires,
		&i.Created,
		&i.ConsumedAt,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one
SELECT group_id, ref, epoch, kind, target_leaf, target_device, key_package, origin, action_id, issued_at, ttl, void_at FROM mls_pending_proposals WHERE group_id = ? AND ref = ?
`

type GetProposalParams struct {
	GroupID id.ID
	Ref     []byte
}

func (q *Queries) GetProposal(ctx context.Context, arg GetProposalParams) (MlsPendingProposals, error) {
	row := q.db.QueryRowContext(ctx, getProposal, arg.GroupID, arg.Ref)
	var i MlsPendingProposals
	err := row.Scan(
		&i.GroupID,
		&i.Ref,
		&i.Epoch,
		&i.Kind,
		&i.TargetLeaf,
		&i.TargetDevice,
		&i.KeyPackage,
		&i.Origin,
		&i.ActionID,
		&i.IssuedAt,
		&i.Ttl,
		&i.VoidAt,
	)
	return i, err
}

const groupsForDevice = `-- name: GroupsForDevice :many
SELECT DISTINCT group_id FROM mls_members WHERE device_id = ? AND removed_epoch IS NULL
ORDER BY group_id
`

type GroupsForDeviceParams struct {
	DeviceID id.ID
}

func (q *Queries) GroupsForDevice(ctx context.Context, arg GroupsForDeviceParams) ([]id.ID, error) {
	rows, err := q.db.QueryContext(ctx, groupsForDevice, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []id.ID{}
	for rows.Next() {
		var group_id id.ID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProposals = `-- name: ListAllProposals :many
SELECT group_id, ref, epoch, kind, target_leaf, target_device, key_package, origin, action_id, issued_at, ttl, void_at FROM mls_pending_proposals WHERE group_id = ? AND epoch = ?
ORDER BY issued_at, ref
`

type ListAllProposalsParams struct {
	GroupID id.ID
	Epoch   int64
}

func (q *Queries) ListAllProposals(ctx context.Context, arg ListAllProposalsParams) ([]MlsPendingProposals, error) {
	rows, err := q.db.QueryContext(ctx, listAllProposals, arg.GroupID, arg.Epoch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlsPendingProposals{}
	for rows.Next() {
		var i MlsPendingProposals
		if err := rows.Scan(
			&i.GroupID,
			&i.Ref,
			&i.Epoch,
			&i.Kind,
			&i.TargetLeaf,
			&i.TargetDevice,
			&i.KeyPackage,
			&i.Origin,
			&i.ActionID,
			&i.IssuedAt,
			&i.Ttl,
			&i.VoidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForRetention = `-- name: ListGroupsForRetention :many
SELECT group_id, binding, kind, community_id, target_id, call_id, ciphersuite, epoch, seq, group_info_blob, tree_hash, public_group_state, external_sender_key_id, e2ee_version, media_version, policy_version, epoch_unknown, heal_deadline, created, closed_at, pruned_below FROM mls_groups WHERE group_id > ?
ORDER BY group_id LIMIT ?2
`

type ListGroupsForRetentionParams struct {
	GroupID id.ID
	MaxRows int64
}

// The retention walk, and deliberately NOT `ListOpenGroups`: invariant 10 caps application
// ciphertext at thirty days for every group, and a group invariant 11 closed is still ciphertext
// on the disk. Filtering on `closed_at IS NULL` here would mean a closed group's blobs are never
// swept again by either half of retention -- neither the delivery floor nor archival `expires` --
// and no other path reclaims them, so the promise inverts into "kept forever" at exactly the
// moment the group stops being useful.
func (q *Queries) ListGroupsForRetention(ctx context.Context, arg ListGroupsForRetentionParams) ([]MlsGroups, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForRetention, arg.GroupID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlsGroups{}
	for rows.Next() {
		var i MlsGroups
		if err := rows.Scan(
			&i.GroupID,
			&i.Binding,
			&i.Kind,
			&i.CommunityID,
			&i.TargetID,
			&i.CallID,
			&i.Ciphersuite,
			&i.Epoch,
			&i.Seq,
			&i.GroupInfoBlob,
			&i.TreeHash,
			&i.PublicGroupState,
			&i.ExternalSenderKeyID,
			&i.E2eeVersion,
			&i.MediaVersion,
			&i.PolicyVersion,
			&i.EpochUnknown,
			&i.HealDeadline,
			&i.Created,
			&i.ClosedAt,
			&i.PrunedBelow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandshakes = `-- name: ListHandshakes :many
SELECT group_id, seq, epoch, kind, sender_leaf, sender_device, blob, created FROM mls_handshakes WHERE group_id = ? AND seq >= ?
ORDER BY seq LIMIT ?3
`

type ListHandshakesParams struct {
	GroupID id.ID
	Seq     int64
	MaxRows int64
}

func (q *Queries) ListHandshakes(ctx context.Context, arg ListHandshakesParams) ([]MlsHandshakes, error) {
	rows, err := q.db.QueryContext(ctx, listHandshakes, arg.GroupID, arg.Seq, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlsHandshakes{}
	for rows.Next() {
		var i MlsHandshakes
		if err := rows.Scan(
			&i.GroupID,
			&i.Seq,
			&i.Epoch,
			&i.Kind,
			&i.SenderLeaf,
			&i.SenderDevice,
			&i.Blob,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveProposals = `-- name: ListLiveProposals :many
SELECT group_id, ref, epoch, kind, target_leaf, target_device, key_package, origin, action_id, issued_at, ttl, void_at FROM mls_pending_proposals WHERE group_id = ? AND epoch = ? AND void_at IS NULL
ORDER BY issued_at, ref
`

type ListLiveProposalsParams struct {
	GroupID id.ID
	Epoch   int64
}

func (q *Queries) ListLiveProposals(ctx context.Context, arg ListLiveProposalsParams) ([]MlsPendingProposals, error) {
	rows, err := q.db.QueryContext(ctx, listLiveProposals, arg.GroupID, arg.Epoch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlsPendingProposals{}
	for rows.Next() {
		var i MlsPendingProposals
		if err := rows.Scan(
			&i.GroupID,
			&i.Ref,
			&i.Epoch,
			&i.Kind,
			&i.TargetLeaf,
			&i.TargetDevice,
			&i.KeyPackage,
			&i.Origin,
			&i.ActionID,
			&i.IssuedAt,
			&i.Ttl,
			&i.VoidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT group_id, leaf_index, user_id, device_id, signature_key, added_epoch, removed_epoch FROM mls_members WHERE group_id = ? AND removed_epoch IS NULL ORDER BY leaf_index
`

type ListMembersParams struct {
	GroupID id.ID
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]MlsMembers, error) {
	rows, err := q.db.QueryContext(ctx, listMembers, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlsMembers{}
	for rows.Next() {
		var i MlsMembers
		if err := rows.Scan(
			&i.GroupID,
			&i.LeafIndex,
			&i.UserID,
			&i.DeviceID,
			&i.SignatureKey,
			&i.AddedEpoch,
			&i.RemovedEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenGroups = `-- name: ListOpenGroups :many
SELECT group_id, binding, kind, community_id, target_id, call_id, ciphersuite, epoch, seq, group_info_blob, tree_hash, public_group_state, external_sender_key_id, e2ee_version, media_version, policy_version, epoch_unknown, heal_deadline, created, closed_at, pruned_below FROM mls_groups WHERE closed_at IS NULL AND group_id > ?
ORDER BY group_id LIMIT ?2
`

type ListOpenGroupsParams struct {
	GroupID id.ID
	MaxRows int64
}

func (q *Queries) ListOpenGroups(ctx context.Context, arg ListOpenGroupsParams) ([]MlsGroups, error) {
	rows, err := q.db.QueryContext(ctx, listOpenGroups, arg.GroupID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlsGroups{}
	for rows.Next() {
		var i MlsGroups
		if err := rows.Scan(
			&i.GroupID,
			&i.Binding,
			&i.Kind,
			&i.CommunityID,
			&i.TargetID,
			&i.CallID,
			&i.Ciphersuite,
			&i.Epoch,
			&i.Seq,
			&i.GroupInfoBlob,
			&i.TreeHash,
			&i.PublicGroupState,
			&i.ExternalSenderKeyID,
			&i.E2eeVersion,
			&i.MediaVersion,
			&i.PolicyVersion,
			&i.EpochUnknown,
			&i.HealDeadline,
			&i.Created,
			&i.ClosedAt,
			&i.PrunedBelow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWelcomes = `-- name: ListWelcomes :many
SELECT mls_welcomes.welcome_id, mls_welcomes.device_id, mls_welcomes.group_id, mls_welcomes.epoch,
       mls_welcomes.commit_seq, mls_welcomes.blob_sha256, mls_welcomes.created,
       mls_welcomes.expires, mls_welcomes.delivered_at, mls_welcome_payloads.blob,
       mls_epoch_trees.ratchet_tree, mls_epoch_trees.tree_hash
FROM mls_welcomes
JOIN mls_welcome_payloads ON mls_welcome_payloads.blob_sha256 = mls_welcomes.blob_sha256
LEFT JOIN mls_epoch_trees ON mls_epoch_trees.group_id = mls_welcomes.group_id
                         AND mls_epoch_trees.epoch = mls_welcomes.epoch
WHERE mls_welcomes.device_id = ? AND mls_welcomes.delivered_at IS NULL
      AND mls_welcomes.welcome_id > ?
ORDER BY mls_welcomes.welcome_id LIMIT ?3
`

type ListWelcomesParams struct {
	DeviceID  id.ID
	WelcomeID int64
	MaxRows   int64
}

type ListWelcomesRow struct {
	WelcomeID   int64
	DeviceID    id.ID
	GroupID     id.ID
	Epoch       int64
	CommitSeq   int64
	BlobSha256  []byte
	Created     int64
	Expires     int64
	DeliveredAt sql.NullInt64
	Blob        []byte
	RatchetTree []byte
	TreeHash    []byte
}

func (q *Queries) ListWelcomes(ctx context.Context, arg ListWelcomesParams) ([]ListWelcomesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWelcomes, arg.DeviceID, arg.WelcomeID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWelcomesRow{}
	for rows.Next() {
		var i ListWelcomesRow
		if err := rows.Scan(
			&i.WelcomeID,
			&i.DeviceID,
			&i.GroupID,
			&i.Epoch,
			&i.CommitSeq,
			&i.BlobSha256,
			&i.Created,
			&i.Expires,
			&i.DeliveredAt,
			&i.Blob,
			&i.RatchetTree,
			&i.TreeHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllGroupsEpochUnknown = `-- name: MarkAllGroupsEpochUnknown :exec
UPDATE mls_groups SET epoch_unknown = 1, heal_deadline = CAST(?1 AS INTEGER)
WHERE closed_at IS NULL
`

type MarkAllGroupsEpochUnknownParams struct {
	HealDeadline int64
}

// Invariant 11's first half, as ONE statement rather than a paged loop: a restore runs once and
// correctness, not latency, governs it, while a loop that stopped at a fixed batch would leave
// every group past the batch serving state the restored database no longer matches. Closed groups
// are skipped -- a closed group has nothing left to heal.
func (q *Queries) MarkAllGroupsEpochUnknown(ctx context.Context, arg MarkAllGroupsEpochUnknownParams) error {
	_, err := q.db.ExecContext(ctx, markAllGroupsEpochUnknown, arg.HealDeadline)
	return err
}

const oldestHandshakeSeq = `-- name: OldestHandshakeSeq :one
SELECT seq FROM mls_handshakes WHERE group_id = ? ORDER BY seq LIMIT 1
`

type OldestHandshakeSeqParams struct {
	GroupID id.ID
}

func (q *Queries) OldestHandshakeSeq(ctx context.Context, arg OldestHandshakeSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, oldestHandshakeSeq, arg.GroupID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const pruneHandshakes = `-- name: PruneHandshakes :execrows
DELETE FROM mls_handshakes WHERE created < ?
`

type PruneHandshakesParams struct {
	Created int64
}

func (q *Queries) PruneHandshakes(ctx context.Context, arg PruneHandshakesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneHandshakes, arg.Created)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneWelcomes = `-- name: PruneWelcomes :execrows
DELETE FROM mls_welcomes WHERE expires < ?
`

type PruneWelcomesParams struct {
	Expires int64
}

func (q *Queries) PruneWelcomes(ctx context.Context, arg PruneWelcomesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneWelcomes, arg.Expires)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeAllKeyPackages = `-- name: PurgeAllKeyPackages :execrows
DELETE FROM key_packages
`

func (q *Queries) PurgeAllKeyPackages(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAllKeyPackages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeKeyPackagesKeepingLastResort = `-- name: PurgeKeyPackagesKeepingLastResort :execrows
DELETE FROM key_packages WHERE last_resort = 0
`

func (q *Queries) PurgeKeyPackagesKeepingLastResort(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeKeyPackagesKeepingLastResort)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const putEpochTree = `-- name: PutEpochTree :exec
INSERT INTO mls_epoch_trees (group_id, epoch, ratchet_tree, tree_hash, created)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (group_id, epoch) DO NOTHING
`

type PutEpochTreeParams struct {
	GroupID     id.ID
	Epoch       int64
	RatchetTree []byte
	TreeHash    []byte
	Created     int64
}

func (q *Queries) PutEpochTree(ctx context.Context, arg PutEpochTreeParams) error {
	_, err := q.db.ExecContext(ctx, putEpochTree,
		arg.GroupID,
		arg.Epoch,
		arg.RatchetTree,
		arg.TreeHash,
		arg.Created,
	)
	return err
}

const putForkReport = `-- name: PutForkReport :exec
INSERT INTO fork_reports (group_id, seq, reporter_device, epoch, reason, created)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (group_id, seq, reporter_device) DO NOTHING
`

type PutForkReportParams struct {
	GroupID        id.ID
	Seq            int64
	ReporterDevice id.ID
	Epoch          int64
	Reason         string
	Created        int64
}

func (q *Queries) PutForkReport(ctx context.Context, arg PutForkReportParams) error {
	_, err := q.db.ExecContext(ctx, putForkReport,
		arg.GroupID,
		arg.Seq,
		arg.ReporterDevice,
		arg.Epoch,
		arg.Reason,
		arg.Created,
	)
	return err
}

const putGroupState = `-- name: PutGroupState :exec
UPDATE mls_groups
SET epoch = ?, public_group_state = ?, group_info_blob = ?, tree_hash = ?, epoch_unknown = 0
WHERE group_id = ?
`

type PutGroupStateParams struct {
	Epoch            int64
	PublicGroupState []byte
	GroupInfoBlob    []byte
	TreeHash         []byte
	GroupID          id.ID
}

func (q *Queries) PutGroupState(ctx context.Context, arg PutGroupStateParams) error {
	_, err := q.db.ExecContext(ctx, putGroupState,
		arg.Epoch,
		arg.PublicGroupState,
		arg.GroupInfoBlob,
		arg.TreeHash,
		arg.GroupID,
	)
	return err
}

const putKeyPackage = `-- name: PutKeyPackage :exec
INSERT INTO key_packages (device_id, kp_ref, blob, last_resort, expires, created, consumed_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (device_id, kp_ref) DO NOTHING
`

type PutKeyPackageParams struct {
	DeviceID   id.ID
	KpRef      []byte
	Blob       []byte
	LastResort int64
	Expires    int64
	Created    int64
	ConsumedAt sql.NullInt64
}

func (q *Queries) PutKeyPackage(ctx context.Context, arg PutKeyPackageParams) error {
	_, err := q.db.ExecContext(ctx, putKeyPackage,
		arg.DeviceID,
		arg.KpRef,
		arg.Blob,
		arg.LastResort,
		arg.Expires,
		arg.Created,
		arg.ConsumedAt,
	)
	return err
}

const putMemberLeaf = `-- name: PutMemberLeaf :exec
INSERT INTO mls_members (group_id, leaf_index, user_id, device_id, signature_key, added_epoch,
                         removed_epoch)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type PutMemberLeafParams struct {
	GroupID      id.ID
	LeafIndex    int64
	UserID       id.ID
	DeviceID     id.ID
	SignatureKey []byte
	AddedEpoch   int64
	RemovedEpoch sql.NullInt64
}

func (q *Queries) PutMemberLeaf(ctx context.Context, arg PutMemberLeafParams) error {
	_, err := q.db.ExecContext(ctx, putMemberLeaf,
		arg.GroupID,
		arg.LeafIndex,
		arg.UserID,
		arg.DeviceID,
		arg.SignatureKey,
		arg.AddedEpoch,
		arg.RemovedEpoch,
	)
	return err
}

const putProposal = `-- name: PutProposal :exec
INSERT INTO mls_pending_proposals (group_id, ref, epoch, kind, target_leaf, target_device,
                                   key_package, origin, action_id, issued_at, ttl, void_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type PutProposalParams struct {
	GroupID      id.ID
	Ref          []byte
	Epoch        int64
	Kind         int64
	TargetLeaf   sql.NullInt64
	TargetDevice []byte
	KeyPackage   []byte
	Origin       int64
	ActionID     id.ID
	IssuedAt     int64
	Ttl          int64
	VoidAt       sql.NullInt64
}

func (q *Queries) PutProposal(ctx context.Context, arg PutProposalParams) error {
	_, err := q.db.ExecContext(ctx, putProposal,
		arg.GroupID,
		arg.Ref,
		arg.Epoch,
		arg.Kind,
		arg.TargetLeaf,
		arg.TargetDevice,
		arg.KeyPackage,
		arg.Origin,
		arg.ActionID,
		arg.IssuedAt,
		arg.Ttl,
		arg.VoidAt,
	)
	return err
}

const putWelcome = `-- name: PutWelcome :exec
INSERT INTO mls_welcomes (device_id, group_id, epoch, commit_seq, blob_sha256, created, expires,
                          delivered_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (device_id, blob_sha256) DO NOTHING
`

type PutWelcomeParams struct {
	DeviceID    id.ID
	GroupID     id.ID
	Epoch       int64
	CommitSeq   int64
	BlobSha256  []byte
	Created     int64
	Expires     int64
	DeliveredAt sql.NullInt64
}

func (q *Queries) PutWelcome(ctx context.Context, arg PutWelcomeParams) error {
	_, err := q.db.ExecContext(ctx, putWelcome,
		arg.DeviceID,
		arg.GroupID,
		arg.Epoch,
		arg.CommitSeq,
		arg.BlobSha256,
		arg.Created,
		arg.Expires,
		arg.DeliveredAt,
	)
	return err
}

const putWelcomePayload = `-- name: PutWelcomePayload :exec
INSERT INTO mls_welcome_payloads (blob_sha256, group_id, epoch, blob, created)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (blob_sha256) DO NOTHING
`

type PutWelcomePayloadParams struct {
	BlobSha256 []byte
	GroupID    id.ID
	Epoch      int64
	Blob       []byte
	Created    int64
}

func (q *Queries) PutWelcomePayload(ctx context.Context, arg PutWelcomePayloadParams) error {
	_, err := q.db.ExecContext(ctx, putWelcomePayload,
		arg.BlobSha256,
		arg.GroupID,
		arg.Epoch,
		arg.Blob,
		arg.Created,
	)
	return err
}

const quarantineDevice = `-- name: QuarantineDevice :exec
UPDATE devices SET quarantined_at = ?, quarantine_reason = ? WHERE id = ?
`

type QuarantineDeviceParams struct {
	QuarantinedAt    sql.NullInt64
	QuarantineReason string
	ID               id.ID
}

func (q *Queries) QuarantineDevice(ctx context.Context, arg QuarantineDeviceParams) error {
	_, err := q.db.ExecContext(ctx, quarantineDevice, arg.QuarantinedAt, arg.QuarantineReason, arg.ID)
	return err
}

const setGroupHealing = `-- name: SetGroupHealing :exec
UPDATE mls_groups SET epoch_unknown = ?, heal_deadline = ? WHERE group_id = ?
`

type SetGroupHealingParams struct {
	EpochUnknown int64
	HealDeadline sql.NullInt64
	GroupID      id.ID
}

func (q *Queries) SetGroupHealing(ctx context.Context, arg SetGroupHealingParams) error {
	_, err := q.db.ExecContext(ctx, setGroupHealing, arg.EpochUnknown, arg.HealDeadline, arg.GroupID)
	return err
}

const takeKeyPackage = `-- name: TakeKeyPackage :one
UPDATE key_packages SET consumed_at = ?1
WHERE key_packages.device_id = ?2 AND key_packages.kp_ref = (
  SELECT kp.kp_ref FROM key_packages kp
  WHERE kp.device_id = ?2 AND kp.consumed_at IS NULL AND kp.last_resort = 0
        AND kp.expires > ?1
  ORDER BY kp.expires, kp.kp_ref LIMIT 1)
RETURNING device_id, kp_ref, blob, last_resort, expires, created, consumed_at
`

type TakeKeyPackageParams struct {
	Now      sql.NullInt64
	DeviceID id.ID
}

func (q *Queries) TakeKeyPackage(ctx context.Context, arg TakeKeyPackageParams) (KeyPackages, error) {
	row := q.db.QueryRowContext(ctx, takeKeyPackage, arg.Now, arg.DeviceID)
	var i KeyPackages
	err := row.Scan(
		&i.DeviceID,
		&i.KpRef,
		&i.Blob,
		&i.LastResort,
		&i.Expires,
		&i.Created,
		&i.ConsumedAt,
	)
	return i, err
}

const voidProposal = `-- name: VoidProposal :exec
UPDATE mls_pending_proposals SET void_at = ? WHERE group_id = ? AND ref = ?
`

type VoidProposalParams struct {
	VoidAt  sql.NullInt64
	GroupID id.ID
	Ref     []byte
}

func (q *Queries) VoidProposal(ctx context.Context, arg VoidProposalParams) error {
	_, err := q.db.ExecContext(ctx, voidProposal, arg.VoidAt, arg.GroupID, arg.Ref)
	return err
}
