// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readable.sql

package sqlitedb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const deleteReadableMessage = `-- name: DeleteReadableMessage :execrows
UPDATE readable_messages SET envelope = x'', body = '', deleted = ?
WHERE channel_id = ? AND seq = ? AND deleted IS NULL
`

type DeleteReadableMessageParams struct {
	Deleted   sql.NullInt64
	ChannelID id.ID
	Seq       int64
}

// A zero-length envelope, not an empty CBOR array: the column holds CBOR and a delete leaves none.
// The body is emptied so the row leaves the FTS index through the _au trigger, while the franking
// tuple (franking_tag, franking_key_id, sender, created) survives for the report path.
func (q *Queries) DeleteReadableMessage(ctx context.Context, arg DeleteReadableMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReadableMessage, arg.Deleted, arg.ChannelID, arg.Seq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editReadableMessage = `-- name: EditReadableMessage :execrows
UPDATE readable_messages SET envelope = ?, body = ?, edited = ?
WHERE channel_id = ? AND seq = ? AND deleted IS NULL
`

type EditReadableMessageParams struct {
	Envelope  []byte
	Body      string
	Edited    sql.NullInt64
	ChannelID id.ID
	Seq       int64
}

// A deleted message is not edited: its envelope and body are gone for good.
func (q *Queries) EditReadableMessage(ctx context.Context, arg EditReadableMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editReadableMessage,
		arg.Envelope,
		arg.Body,
		arg.Edited,
		arg.ChannelID,
		arg.Seq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReadState = `-- name: GetReadState :one
SELECT last_read_seq FROM read_state WHERE user_id = ? AND channel_id = ?
`

type GetReadStateParams struct {
	UserID    id.ID
	ChannelID id.ID
}

func (q *Queries) GetReadState(ctx context.Context, arg GetReadStateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReadState, arg.UserID, arg.ChannelID)
	var last_read_seq int64
	err := row.Scan(&last_read_seq)
	return last_read_seq, err
}

const lastReadableMessageAt = `-- name: LastReadableMessageAt :one
SELECT created FROM readable_messages
WHERE channel_id = ? AND sender = ?
ORDER BY created DESC LIMIT 1
`

type LastReadableMessageAtParams struct {
	ChannelID id.ID
	Sender    id.ID
}

// The slowmode gate's read. A deleted message still counts: deleting the last message must not
// reset the gate, or delete-and-repost would bypass slowmode.
func (q *Queries) LastReadableMessageAt(ctx context.Context, arg LastReadableMessageAtParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastReadableMessageAt, arg.ChannelID, arg.Sender)
	var created int64
	err := row.Scan(&created)
	return created, err
}

const listReadableAudience = `-- name: ListReadableAudience :many
SELECT cm.user_id
FROM channel_members cm
JOIN channels c ON c.id = cm.channel_id
JOIN members m ON m.community_id = c.community_id AND m.user_id = cm.user_id
WHERE cm.channel_id = ? AND c.deleted_at IS NULL
ORDER BY cm.user_id
`

type ListReadableAudienceParams struct {
	ChannelID id.ID
}

// Who message.plain reaches: the channel's materialised members (task 7's channel_members, which
// holds exactly the users the resolver grants view_channel) who are still members of its
// community, so a kicked, banned or departed user drops out before any re-materialisation.
func (q *Queries) ListReadableAudience(ctx context.Context, arg ListReadableAudienceParams) ([]id.ID, error) {
	rows, err := q.db.QueryContext(ctx, listReadableAudience, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []id.ID{}
	for rows.Next() {
		var user_id id.ID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadableMessages = `-- name: ListReadableMessages :many
SELECT id, channel_id, channel_hex, seq, sender, envelope, body, franking_tag, franking_key_id,
       mention_count, created, edited, deleted
FROM readable_messages
WHERE channel_id = ? AND seq >= ?
ORDER BY seq LIMIT ?3
`

type ListReadableMessagesParams struct {
	ChannelID id.ID
	Seq       int64
	MaxRows   int64
}

func (q *Queries) ListReadableMessages(ctx context.Context, arg ListReadableMessagesParams) ([]ReadableMessages, error) {
	rows, err := q.db.QueryContext(ctx, listReadableMessages, arg.ChannelID, arg.Seq, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadableMessages{}
	for rows.Next() {
		var i ReadableMessages
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ChannelHex,
			&i.Seq,
			&i.Sender,
			&i.Envelope,
			&i.Body,
			&i.FrankingTag,
			&i.FrankingKeyID,
			&i.MentionCount,
			&i.Created,
			&i.Edited,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putReadState = `-- name: PutReadState :exec
INSERT INTO read_state (user_id, channel_id, last_read_seq) VALUES (?, ?, ?)
ON CONFLICT (user_id, channel_id) DO UPDATE
SET last_read_seq = MAX(read_state.last_read_seq, excluded.last_read_seq)
`

type PutReadStateParams struct {
	UserID      id.ID
	ChannelID   id.ID
	LastReadSeq int64
}

// Monotone: a stale tab that reports an older position must not un-read the channel.
func (q *Queries) PutReadState(ctx context.Context, arg PutReadStateParams) error {
	_, err := q.db.ExecContext(ctx, putReadState, arg.UserID, arg.ChannelID, arg.LastReadSeq)
	return err
}

const putReadableMessage = `-- name: PutReadableMessage :one

INSERT INTO readable_messages (channel_id, channel_hex, seq, sender, envelope, body, franking_tag,
                               franking_key_id, mention_count, created, edited, deleted)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type PutReadableMessageParams struct {
	ChannelID     id.ID
	ChannelHex    string
	Seq           int64
	Sender        id.ID
	Envelope      []byte
	Body          string
	FrankingTag   []byte
	FrankingKeyID id.ID
	MentionCount  int64
	Created       int64
	Edited        sql.NullInt64
	Deleted       sql.NullInt64
}

// Server-readable channels (Plan 2 task 8, 00009_readable.sql). Search is NOT here: sqlc can type
// neither the FTS5 MATCH (a virtual table is not a value to it) nor the implicit rowid, so
// SearchReadable is hand-written database/sql in search.go (gap-69 section 5.1).
//
// Every read names its columns: the Postgres table carries body_tsv, which no query selects, and
// the two engines' Querier interfaces must stay identical (schema_test.go).
func (q *Queries) PutReadableMessage(ctx context.Context, arg PutReadableMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, putReadableMessage,
		arg.ChannelID,
		arg.ChannelHex,
		arg.Seq,
		arg.Sender,
		arg.Envelope,
		arg.Body,
		arg.FrankingTag,
		arg.FrankingKeyID,
		arg.MentionCount,
		arg.Created,
		arg.Edited,
		arg.Deleted,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
