// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: structure.sql

package sqlitedb

import (
	"context"
	"database/sql"

	id "github.com/jonasthim/dilla/internal/id"
)

const createCommunity = `-- name: CreateCommunity :exec
INSERT INTO communities (id, owner, name, icon_blob, policy_json, policy_version,
                         min_account_age_seconds, require_mod_2fa, created, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCommunityParams struct {
	ID                   id.ID
	Owner                id.ID
	Name                 string
	IconBlob             []byte
	PolicyJson           string
	PolicyVersion        int64
	MinAccountAgeSeconds int64
	RequireMod2fa        int64
	Created              int64
	DeletedAt            sql.NullInt64
}

func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) error {
	_, err := q.db.ExecContext(ctx, createCommunity,
		arg.ID,
		arg.Owner,
		arg.Name,
		arg.IconBlob,
		arg.PolicyJson,
		arg.PolicyVersion,
		arg.MinAccountAgeSeconds,
		arg.RequireMod2fa,
		arg.Created,
		arg.DeletedAt,
	)
	return err
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM members WHERE community_id = ? AND user_id = ?
`

type DeleteMemberParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMember, arg.CommunityID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMemberRole = `-- name: DeleteMemberRole :execrows
DELETE FROM member_roles WHERE community_id = ? AND user_id = ? AND role_id = ?
`

type DeleteMemberRoleParams struct {
	CommunityID id.ID
	UserID      id.ID
	RoleID      id.ID
}

func (q *Queries) DeleteMemberRole(ctx context.Context, arg DeleteMemberRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemberRole, arg.CommunityID, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCommunity = `-- name: GetCommunity :one
SELECT id, owner, name, icon_blob, policy_json, policy_version,
       min_account_age_seconds, require_mod_2fa, created, deleted_at
FROM communities
WHERE id = ? AND deleted_at IS NULL
`

type GetCommunityParams struct {
	ID id.ID
}

func (q *Queries) GetCommunity(ctx context.Context, arg GetCommunityParams) (Communities, error) {
	row := q.db.QueryRowContext(ctx, getCommunity, arg.ID)
	var i Communities
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.IconBlob,
		&i.PolicyJson,
		&i.PolicyVersion,
		&i.MinAccountAgeSeconds,
		&i.RequireMod2fa,
		&i.Created,
		&i.DeletedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT community_id, user_id, joined, nick
FROM members WHERE community_id = ? AND user_id = ?
`

type GetMemberParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Members, error) {
	row := q.db.QueryRowContext(ctx, getMember, arg.CommunityID, arg.UserID)
	var i Members
	err := row.Scan(
		&i.CommunityID,
		&i.UserID,
		&i.Joined,
		&i.Nick,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, community_id, name, color, position, allow, deny, hoist, mentionable, created
FROM roles WHERE id = ?
`

type GetRoleParams struct {
	ID id.ID
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Roles, error) {
	row := q.db.QueryRowContext(ctx, getRole, arg.ID)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.Allow,
		&i.Deny,
		&i.Hoist,
		&i.Mentionable,
		&i.Created,
	)
	return i, err
}

const listMemberRoles = `-- name: ListMemberRoles :many
SELECT role_id FROM member_roles WHERE community_id = ? AND user_id = ? ORDER BY role_id
`

type ListMemberRolesParams struct {
	CommunityID id.ID
	UserID      id.ID
}

func (q *Queries) ListMemberRoles(ctx context.Context, arg ListMemberRolesParams) ([]id.ID, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRoles, arg.CommunityID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []id.ID{}
	for rows.Next() {
		var role_id id.ID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersOfCommunity = `-- name: ListMembersOfCommunity :many
SELECT community_id, user_id, joined, nick
FROM members
WHERE community_id = ? AND user_id > ?
ORDER BY user_id
LIMIT ?3
`

type ListMembersOfCommunityParams struct {
	CommunityID id.ID
	UserID      id.ID
	MaxRows     int64
}

func (q *Queries) ListMembersOfCommunity(ctx context.Context, arg ListMembersOfCommunityParams) ([]Members, error) {
	rows, err := q.db.QueryContext(ctx, listMembersOfCommunity, arg.CommunityID, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Members{}
	for rows.Next() {
		var i Members
		if err := rows.Scan(
			&i.CommunityID,
			&i.UserID,
			&i.Joined,
			&i.Nick,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, community_id, name, color, position, allow, deny, hoist, mentionable, created
FROM roles WHERE community_id = ? ORDER BY position, id
`

type ListRolesParams struct {
	CommunityID id.ID
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Roles, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, arg.CommunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Roles{}
	for rows.Next() {
		var i Roles
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.Allow,
			&i.Deny,
			&i.Hoist,
			&i.Mentionable,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putMember = `-- name: PutMember :exec
INSERT INTO members (community_id, user_id, joined, nick)
VALUES (?, ?, ?, ?)
ON CONFLICT (community_id, user_id) DO UPDATE SET nick = excluded.nick
`

type PutMemberParams struct {
	CommunityID id.ID
	UserID      id.ID
	Joined      int64
	Nick        string
}

func (q *Queries) PutMember(ctx context.Context, arg PutMemberParams) error {
	_, err := q.db.ExecContext(ctx, putMember,
		arg.CommunityID,
		arg.UserID,
		arg.Joined,
		arg.Nick,
	)
	return err
}

const putMemberRole = `-- name: PutMemberRole :exec
INSERT INTO member_roles (community_id, user_id, role_id)
VALUES (?, ?, ?)
ON CONFLICT (community_id, user_id, role_id) DO NOTHING
`

type PutMemberRoleParams struct {
	CommunityID id.ID
	UserID      id.ID
	RoleID      id.ID
}

func (q *Queries) PutMemberRole(ctx context.Context, arg PutMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, putMemberRole, arg.CommunityID, arg.UserID, arg.RoleID)
	return err
}

const putRole = `-- name: PutRole :exec
INSERT INTO roles (id, community_id, name, color, position, allow, deny, hoist, mentionable, created)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name, color = excluded.color, position = excluded.position,
  allow = excluded.allow, deny = excluded.deny, hoist = excluded.hoist,
  mentionable = excluded.mentionable
`

type PutRoleParams struct {
	ID          id.ID
	CommunityID id.ID
	Name        string
	Color       int64
	Position    int64
	Allow       int64
	Deny        int64
	Hoist       int64
	Mentionable int64
	Created     int64
}

func (q *Queries) PutRole(ctx context.Context, arg PutRoleParams) error {
	_, err := q.db.ExecContext(ctx, putRole,
		arg.ID,
		arg.CommunityID,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.Allow,
		arg.Deny,
		arg.Hoist,
		arg.Mentionable,
		arg.Created,
	)
	return err
}

const softDeleteCommunity = `-- name: SoftDeleteCommunity :execrows
UPDATE communities SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteCommunityParams struct {
	DeletedAt sql.NullInt64
	ID        id.ID
}

func (q *Queries) SoftDeleteCommunity(ctx context.Context, arg SoftDeleteCommunityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteCommunity, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCommunityMeta = `-- name: UpdateCommunityMeta :execrows
UPDATE communities
SET name = ?, min_account_age_seconds = ?, require_mod_2fa = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateCommunityMetaParams struct {
	Name                 string
	MinAccountAgeSeconds int64
	RequireMod2fa        int64
	ID                   id.ID
}

func (q *Queries) UpdateCommunityMeta(ctx context.Context, arg UpdateCommunityMetaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommunityMeta,
		arg.Name,
		arg.MinAccountAgeSeconds,
		arg.RequireMod2fa,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCommunityPolicy = `-- name: UpdateCommunityPolicy :execrows
UPDATE communities
SET policy_json = ?1, policy_version = ?2
WHERE id = ?3 AND deleted_at IS NULL
  AND policy_version < CAST(?2 AS INTEGER)
`

type UpdateCommunityPolicyParams struct {
	PolicyJson    string
	PolicyVersion int64
	ID            id.ID
}

// The version is MONOTONE: two writers that read the same version both compute
// the same successor, and the second must not land a different policy under a
// number clients already hold. Zero rows is either an unknown community or a
// lost race; the adapter tells the two apart.
func (q *Queries) UpdateCommunityPolicy(ctx context.Context, arg UpdateCommunityPolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommunityPolicy, arg.PolicyJson, arg.PolicyVersion, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
