// Package sfu runs LiveKit v1.13.7 in dillad's own process.
//
// The rendered YAML is interfaces.md b.9, which survives config.NewConfig in strict mode,
// Config.ValidateKeys, Config.LoadTURNSecrets and routing.NewLocalNode (gap G22, probed
// 2026-09-30). The settings that fail silently rather than loudly:
//
//   - node_ip with use_external_ip: false makes RTCConfig.Validate skip resolveNodeIP. Omitting
//     node_ip sets NodeIPAutoGenerated, which puts LiveKit's public STUN list into the SFU's own
//     PeerConnection.
//   - enable_loopback_candidate: true is required on a loopback-only box: without it the UDP mux
//     gathers no host candidate at all, with no error.
//   - udp_port suppresses the 50000-60000 range Validate assigns outside development mode.
//   - allow_tcp_fallback: false. Unset means true, and with tcp_port 0 a client switched to TCP
//     after an ICE failure has no usable pair left (DEV-10).
//   - room.enabled_codecs replaces LiveKit's default list (yaml.v3 builds a new slice): Opus without
//     RED, PCMU or PCMA; VP8; H.264; VP9 profile 0 only behind the flag; never AV1 or H.265 (DEV-05).
//     H.264 carries no fmtp_line (MD-29): AddTrack checks the client's codec with
//     IsCodecEnabled(mime only) (pkg/rtc/participant.go:3063,3091, mediaengine.go:151-161), which no
//     fmtp-restricted entry passes, so a restricted H.264 falls back to VP8 for every publisher. Bare,
//     LiveKit registers 42e01f modes 0 and 1 and High 640032; packetization-mode 1 Constrained
//     Baseline is the publishers' rule (DEV-06: the worker's setCodecPreferences filter,
//     internal/media's single H.264 capability). The VP9 entry has the same flaw (follow-up card 7).
//   - rtc.stun_servers is a non-served sentinel when set: a non-empty list keeps LiveKit from
//     appending Google's and Twilio's STUN hosts to every join response; clients use the ICE servers
//     the calls route hands them, never LiveKit's list (DEV-51).
//   - webhook.api_key is the keys map's own key, from the same field, or InitializeServer fails with
//     ErrWebHookMissingAPIKey.
//   - turn.enabled: false is LiveKit's default and is written so the file reads against the spec.
//   - subscription_limit_audio/video are never rendered: they refuse a subscription statically,
//     they do not select the loudest six (DEV-04).
package sfu

import (
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/netip"
	"strconv"
	"strings"
)

// minSecretLength is LiveKit's own recommendation. LiveKit only logs about a shorter secret, so
// dilla enforces it.
const minSecretLength = 32

// WebhookPath is the one route dillad's webhook receiver serves (task 12).
const WebhookPath = "/livekit/webhook"

// h264Fmtp is the one H.264 registration dilla's publishers offer: packetization mode 1,
// Constrained Baseline (DEV-06). It is not rendered into enabled_codecs (MD-29): the tests use it.
const h264Fmtp = "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"

// webhookEvents is every event dillad's call lifecycle reads (b.6).
var webhookEvents = []string{
	"room_started", "room_finished", "participant_joined", "participant_left",
	"participant_connection_aborted", "track_published", "track_unpublished",
}

// Config is the in-process SFU configuration.
type Config struct {
	Port                    int    // 7880
	BindAddress             string // "127.0.0.1"
	NodeIP                  string // "127.0.0.1", explicit on purpose
	UDPPort                 int    // 7882
	TCPPort                 int    // 0
	EnableLoopbackCandidate bool   // true
	APIKey                  string // "dilla", livekit.api_key's default
	APISecret               string // >= 32 characters
	// AdvertiseInternalIP makes LiveKit offer its local host candidate beside node_ip's. It is
	// required for Firefox against a loopback node_ip (G35), and keeps relay pairing on-host.
	AdvertiseInternalIP bool
	// STUNServers is rtc.stun_servers ("host:port" each), the non-served sentinel.
	STUNServers []string
	// MaxParticipants is room.max_participants; 0 renders none.
	MaxParticipants uint32
	// AutoCreate is room.auto_create. It stays true until task 10 opens every room with CreateRoom
	// before minting a token for it (MD-16, DEV-44).
	AutoCreate bool
	// EmptyTimeout and DepartureTimeout are room.empty_timeout and room.departure_timeout, seconds:
	// a room nobody joined closes 300 s after creation, a room everybody left 20 s after the last
	// leave.
	EmptyTimeout, DepartureTimeout uint32
	// VP9 adds video/VP9 profile-id=0 to the enabled codecs (livekit.vp9, off by default — F4).
	VP9 bool
	// WebhookURL is where LiveKit posts its webhooks; "" renders no webhook block.
	WebhookURL string
	// LimitNumTracks and LimitBytesPerSec are LiveKit's node-wide join gates, rendered only when a
	// host sets them (DEV-26): one 25-voice call is about 600 downtracks.
	LimitNumTracks   int32
	LimitBytesPerSec float32
	// IPsExcludes is rtc.ips.excludes: the addresses LiveKit must not offer, such as a bridged
	// Docker network's 172.x range (F7).
	IPsExcludes []string
	// Log receives LiveKit's and pion's logs through NewLogBridge. It is not rendered; nil discards.
	Log *slog.Logger
}

// DefaultConfig returns the loopback configuration. APISecret is empty: the caller supplies one,
// and YAML refuses a short one.
func DefaultConfig() Config {
	return Config{
		Port:                    7880,
		BindAddress:             "127.0.0.1",
		NodeIP:                  "127.0.0.1",
		UDPPort:                 7882,
		TCPPort:                 0,
		EnableLoopbackCandidate: true,
		APIKey:                  "dilla",
		AdvertiseInternalIP:     true,
		AutoCreate:              true,
		EmptyTimeout:            300,
		DepartureTimeout:        20,
	}
}

// YAML renders the configuration. Every key exists on LiveKit v1.13.7's config structs, which
// strict mode requires; every value that comes from configuration is checked so it cannot leave its
// own line.
func (c Config) YAML() (string, error) {
	if c.APIKey == "" {
		return "", errors.New("sfu: api key is empty; ValidateKeys refuses an empty keys map")
	}
	if !plainYAMLWord(c.APIKey) {
		return "", fmt.Errorf("sfu: api key %q must be letters, digits, '-' and '_'", c.APIKey)
	}
	if len(c.APISecret) < minSecretLength {
		return "", fmt.Errorf("sfu: api secret is %d characters, want at least %d",
			len(c.APISecret), minSecretLength)
	}
	if c.BindAddress == "" || c.NodeIP == "" {
		return "", errors.New("sfu: bind address and node ip must both be set explicitly")
	}
	var b strings.Builder
	fmt.Fprintf(&b, "port: %d\n", c.Port)
	fmt.Fprintf(&b, "bind_addresses:\n  - %s\n", c.BindAddress)
	fmt.Fprintf(&b, "keys:\n  %s: %q\n", c.APIKey, c.APISecret)
	b.WriteString("rtc:\n")
	fmt.Fprintf(&b, "  node_ip: %s\n", c.NodeIP)
	b.WriteString("  use_external_ip: false\n")
	fmt.Fprintf(&b, "  enable_loopback_candidate: %t\n", c.EnableLoopbackCandidate)
	fmt.Fprintf(&b, "  udp_port: %d\n", c.UDPPort)
	fmt.Fprintf(&b, "  tcp_port: %d\n", c.TCPPort)
	if c.AdvertiseInternalIP {
		b.WriteString("  advertise_internal_ip: true\n")
	}
	if len(c.STUNServers) > 0 {
		b.WriteString("  stun_servers:\n")
		for _, s := range c.STUNServers {
			if err := validSTUNServer(s); err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "    - %q\n", s)
		}
	}
	b.WriteString("  use_ice_lite: false\n")
	b.WriteString("  allow_tcp_fallback: false\n")
	if len(c.IPsExcludes) > 0 {
		b.WriteString("  ips:\n    excludes:\n")
		for _, p := range c.IPsExcludes {
			if _, err := netip.ParsePrefix(p); err != nil {
				return "", fmt.Errorf("sfu: ips exclude %q is not a CIDR prefix", p)
			}
			fmt.Fprintf(&b, "      - %q\n", p)
		}
	}
	b.WriteString("audio:\n")
	b.WriteString("  active_level: 35\n  min_percentile: 40\n  update_interval: 400\n")
	b.WriteString("  smooth_intervals: 2\n  active_red_encoding: false\n")
	b.WriteString("room:\n")
	fmt.Fprintf(&b, "  auto_create: %t\n", c.AutoCreate)
	if c.MaxParticipants > 0 {
		fmt.Fprintf(&b, "  max_participants: %d\n", c.MaxParticipants)
	}
	fmt.Fprintf(&b, "  empty_timeout: %d\n", c.EmptyTimeout)
	fmt.Fprintf(&b, "  departure_timeout: %d\n", c.DepartureTimeout)
	b.WriteString("  enabled_codecs:\n")
	b.WriteString("    - mime: audio/opus\n")
	b.WriteString("    - mime: video/VP8\n")
	// H.264 is rendered bare (MD-29): an fmtp_line here makes AddTrack's IsCodecEnabled, which
	// checks the client's codec mime with an empty fmtp, call H.264 disabled and fall back to VP8.
	b.WriteString("    - mime: video/H264\n")
	if c.VP9 {
		b.WriteString("    - mime: video/VP9\n      fmtp_line: \"profile-id=0\"\n")
	}
	b.WriteString("    - mime: video/rtx\n")
	if c.LimitNumTracks > 0 || c.LimitBytesPerSec > 0 {
		b.WriteString("limit:\n")
		if c.LimitNumTracks > 0 {
			fmt.Fprintf(&b, "  num_tracks: %d\n", c.LimitNumTracks)
		}
		if c.LimitBytesPerSec > 0 {
			fmt.Fprintf(&b, "  bytes_per_sec: %s\n", strconv.FormatFloat(float64(c.LimitBytesPerSec), 'f', -1, 32))
		}
	}
	if c.WebhookURL != "" {
		if !strings.HasPrefix(c.WebhookURL, "http://") || strings.ContainsAny(c.WebhookURL, " \t\r\n\"'#") {
			return "", fmt.Errorf("sfu: webhook url %q is not a plain http:// URL", c.WebhookURL)
		}
		fmt.Fprintf(&b, "webhook:\n  api_key: %s\n  urls:\n    - %q\n", c.APIKey, c.WebhookURL)
		b.WriteString("  filter_params:\n    include_events:\n")
		for _, e := range webhookEvents {
			fmt.Fprintf(&b, "      - %s\n", e)
		}
	}
	b.WriteString("turn:\n  enabled: false\n")
	return b.String(), nil
}

// plainYAMLWord is true for a key that needs no quoting as a YAML mapping key and scalar.
func plainYAMLWord(s string) bool {
	for _, r := range s {
		switch {
		case r == '-', r == '_', r >= '0' && r <= '9', r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z':
		default:
			return false
		}
	}
	return s != ""
}

// validSTUNServer refuses an rtc.stun_servers entry that is not a plain "host:port": the value is
// written into YAML, and LiveKit expects that shape.
func validSTUNServer(s string) error {
	host, port, err := net.SplitHostPort(s)
	if err != nil || host == "" || port == "" || strings.ContainsAny(s, " \t\r\n\"'#") {
		return fmt.Errorf("sfu: stun server %q is not host:port", s)
	}
	return nil
}
