// Package sfu runs LiveKit v1.13.7 in dillad's own process on loopback.
//
// The config below is the minimum that survives, in order, config.NewConfig
// (strict mode), Config.ValidateKeys, Config.LoadTURNSecrets and
// routing.NewLocalNode, plus the one setting that fails silently rather than
// loudly:
//
//   - node_ip: 127.0.0.1 with use_external_ip: false makes RTCConfig.Validate
//     skip resolveNodeIP entirely. Omitting node_ip is worse than setting it:
//     resolveNodeIP still lands on 127.0.0.1 but sets NodeIPAutoGenerated, which
//     makes the SFU's own PeerConnection use LiveKit's default public STUN list.
//   - enable_loopback_candidate: true is not optional on a loopback-only box.
//     Without it CreateUDPMuxesFromPorts starts from includeLoopback=false, and
//     on a machine whose only interface is lo that yields an empty address list
//     -- no error, simply no UDP host candidates and no media.
//   - udp_port: 7882 suppresses the 50000-60000 ICE port range Validate would
//     otherwise assign outside development mode.
//   - rtc.turn_servers stays absent: LoadTURNSecrets requires credentials on
//     every entry.
//   - turn.enabled: false is written even though it is LiveKit's own default,
//     because R18 and the spec's "System architecture" item 4 name it. It is a
//     readability requirement, not a behavioural one.
package sfu

import (
	"errors"
	"fmt"
	"strings"
)

// minSecretLength is LiveKit's own recommendation. LiveKit only logs about a
// shorter secret, so dilla enforces it.
const minSecretLength = 32

// Config is the loopback SFU configuration.
type Config struct {
	Port                    int    // 7880
	BindAddress             string // "127.0.0.1"
	NodeIP                  string // "127.0.0.1", explicit on purpose
	UDPPort                 int    // 7882
	TCPPort                 int    // 0
	EnableLoopbackCandidate bool   // true
	APIKey                  string // "dillad"
	APISecret               string // >= 32 characters
}

// DefaultConfig returns the loopback spike configuration. APISecret is empty:
// the caller supplies one, and YAML refuses a short one.
func DefaultConfig() Config {
	return Config{
		Port:                    7880,
		BindAddress:             "127.0.0.1",
		NodeIP:                  "127.0.0.1",
		UDPPort:                 7882,
		TCPPort:                 0,
		EnableLoopbackCandidate: true,
		APIKey:                  "dillad",
	}
}

// YAML renders the configuration. Every key exists on LiveKit v1.13.7's config
// structs, which strict mode requires.
func (c Config) YAML() (string, error) {
	if c.APIKey == "" {
		return "", errors.New("sfu: api key is empty; ValidateKeys refuses an empty keys map")
	}
	if len(c.APISecret) < minSecretLength {
		return "", fmt.Errorf("sfu: api secret is %d characters, want at least %d",
			len(c.APISecret), minSecretLength)
	}
	if c.BindAddress == "" || c.NodeIP == "" {
		return "", errors.New("sfu: bind address and node ip must both be set explicitly")
	}
	var b strings.Builder
	fmt.Fprintf(&b, "port: %d\n", c.Port)
	fmt.Fprintf(&b, "bind_addresses:\n  - %s\n", c.BindAddress)
	fmt.Fprintf(&b, "keys:\n  %s: %q\n", c.APIKey, c.APISecret)
	b.WriteString("rtc:\n")
	fmt.Fprintf(&b, "  node_ip: %s\n", c.NodeIP)
	b.WriteString("  use_external_ip: false\n")
	fmt.Fprintf(&b, "  enable_loopback_candidate: %t\n", c.EnableLoopbackCandidate)
	fmt.Fprintf(&b, "  udp_port: %d\n", c.UDPPort)
	fmt.Fprintf(&b, "  tcp_port: %d\n", c.TCPPort)
	// R18 and spec line 415 name turn.enabled: false explicitly. It is also
	// LiveKit's own default (DefaultConfig.TURN.Enabled == false,
	// livekit-server@v1.13.7/pkg/config/config.go:597-603), so this changes no
	// behaviour; it is written so the rendered config can be read against the
	// spec line by line. TURNConfig.Enabled carries `yaml:"enabled,omitempty"`
	// (same file, line 272), so strict mode accepts the key.
	b.WriteString("turn:\n  enabled: false\n")
	return b.String(), nil
}
