// Every user-visible string of @dilla/web. Keys are flat and dot-separated; {name} is a placeholder.
// Apostrophes are typographic (’). The copy lint (scripts/check-ui-copy.mjs) scans this file.
export const en = {
  'boot.loading.status': 'Starting dilla',
  'boot.unsupported.status': 'This window cannot keep dilla’s data',
  'boot.unsupported.detail': 'dilla needs storage that lasts. Private windows and some privacy settings turn it off. Open this address in a normal window.',
  'boot.otherTab.status': 'dilla is open in another tab',
  'boot.otherTab.detail': 'Use that tab, or close it. This tab takes over as soon as the other one closes.',
  'boot.storeLost.status': 'This browser can no longer open its saved data',
  'boot.storeLost.detail': 'The key that opens dilla’s storage in this browser is gone, so the account on this device cannot be used here. Resetting clears this browser so you can sign up again.',
  'boot.storeLost.action': 'Reset this browser',
  'boot.storeLost.confirmTitle': 'Reset this browser?',
  'boot.storeLost.confirmBody': 'This deletes dilla’s data for this site from this browser. It cannot be undone.',
  'boot.storeLost.confirmAction': 'Reset',
  'boot.resetting.status': 'Clearing this browser’s data',
  'boot.revoked.status': 'This browser was signed out',
  'boot.revoked.detail': 'Your account no longer accepts this browser. Ask the host if you did not expect this. To start over here, clear this site’s data in the browser’s settings.',
  'boot.revoked.action': 'Forget this browser',
  'boot.revoked.confirmTitle': 'Forget this browser?',
  'boot.revoked.confirmBody': 'This deletes dilla’s data for this site from this browser. To use your account here again, sign in with your password and your recovery key.',
  'boot.revoked.confirmAction': 'Forget',
  'boot.error.status': 'dilla could not start',
  'boot.error.detail': 'Error {code}. Reload the page to try again.',
  'boot.error.action': 'Reload',
  'dialog.close': 'Close',
  'onboarding.step': 'Step {n} of 5',
  'onboarding.back': 'Back',
  'onboarding.next': 'Continue',
  'onboarding.connect.title': 'Join {instance}',
  'onboarding.connect.body': 'You need an invite from someone on {instance}. Paste it below.',
  'onboarding.connect.bodyOpen': '{instance} is open to new accounts. Paste an invite if you were given one.',
  'onboarding.connect.invite': 'Invite',
  'onboarding.connect.inviteOptional': 'Invite (optional)',
  'onboarding.connect.inviteHint': 'A code or a link, as you received it.',
  'onboarding.connect.signIn': 'Use an existing account',
  'onboarding.closed.title': '{instance} is not taking new accounts',
  'onboarding.closed.body': 'Ask the host of {instance} when sign-ups open again.',
  'onboarding.identity.title': 'Choose your name',
  'onboarding.identity.body': 'People on {instance} see these next to your messages.',
  'onboarding.identity.username': 'Username',
  'onboarding.identity.usernameHint': '3 to 32 characters: a–z, 0–9, dot, underscore or hyphen.',
  'onboarding.identity.display': 'Display name (optional)',
  'onboarding.identity.displayHint': 'Up to 64 characters. Your username is shown when this is empty.',
  'onboarding.identity.password': 'Password',
  'onboarding.identity.passwordHint': 'At least 8 characters.',
  'onboarding.keys.title': 'Your recovery key',
  'onboarding.keys.body': 'This key is shown once and is kept nowhere. Write it down or print it, and keep it away from this computer.',
  'onboarding.keys.loss': 'This key is the only way to get your account back or to add another browser. If every browser you use loses its data and you do not have the key, the account and its history are gone, and the host cannot bring them back.',
  'onboarding.keys.label': 'Recovery key',
  'onboarding.keys.acknowledge': 'I have written down or printed my recovery key',
  'onboarding.keys.ackHint': 'Tick the box to continue.',
  'onboarding.keys.print': 'Print',
  'onboarding.keys.preparing': 'Making your keys',
  'onboarding.browser.title': 'What this browser keeps',
  'onboarding.browser.device': 'This browser now holds the key of this device, in its storage for {instance}. The key never leaves this browser.',
  'onboarding.browser.clear': 'Clearing this site’s data removes the key and the messages kept here, and this browser stops being your device.',
  'onboarding.browser.oneBrowser': 'To use this account in another browser, sign in there with your password and this recovery key. Messages sent before that browser joins are not shown in it.',
  'onboarding.browser.private': 'A private window forgets all of this when it closes.',
  'onboarding.browser.submit': 'Create account',
  'onboarding.browser.submitting': 'Creating account…',
  'onboarding.browser.registering': 'Creating your account on {instance}…',
  'onboarding.done.title': 'You’re in',
  'onboarding.done.body': 'You are {username} on {instance}.',
  'onboarding.done.next': 'Open dilla',
  'onboarding.error.inviteRequired': 'Paste the invite you were given.',
  'onboarding.error.inviteInvalid': 'This invite is expired, used up or unknown. Ask for a new one.',
  'onboarding.error.usernameRule': 'Use 3 to 32 characters: a–z, 0–9, dot, underscore or hyphen, with no dot at the start or end.',
  'onboarding.error.usernameTaken': 'That username is taken. Try another.',
  'onboarding.error.displayLength': 'Use at most 64 characters.',
  'onboarding.error.detailsRefused': '{instance} did not accept these details. Check the username and the display name.',
  'onboarding.error.passwordShort': 'Use at least 8 characters.',
  'onboarding.error.rateLimited': 'Too many attempts from this network. Try again in {seconds} s.',
  'onboarding.error.rateLimitedNoWait': 'Too many attempts from this network. Wait a few minutes, then try again.',
  'onboarding.error.network': 'The connection dropped while creating your account. Reload the page to finish.',
  'onboarding.error.reload': 'Reload',
  'onboarding.error.other': 'The account could not be created ({code}). Try again.',
  'signin.step': 'Step {n} of 4',
  'signin.login.title': 'Sign in to {instance}',
  'signin.login.body': 'Use the username and password of your account on {instance}.',
  'signin.login.username': 'Username',
  'signin.login.password': 'Password',
  'signin.login.submit': 'Continue',
  'signin.login.working': 'Checking…',
  'signin.login.createInstead': 'Create a new account instead',
  'signin.totp.title': 'Your second factor',
  'signin.totp.body': 'Enter the six-digit code from your authenticator app.',
  'signin.totp.code': 'Code',
  'signin.key.title': 'Your recovery key',
  'signin.key.body': 'Type or paste the recovery key you wrote down when the account was created. Spaces and hyphens do not matter.',
  'signin.key.label': 'Recovery key',
  'signin.key.hint': '{n} of 52 characters',
  'signin.key.submit': 'Add this browser',
  'signin.key.working': 'Adding this browser to your account…',
  'signin.done.title': 'You’re in',
  'signin.done.body': 'This browser is now a device of {username} on {instance}. Messages sent before now are not shown here.',
  'signin.done.next': 'Open dilla',
  'signin.cancel': 'Cancel',
  'signin.error.loginFailed': 'That username and password did not work.',
  'signin.error.totpFailed': 'That code did not work. Sign in again with a fresh code.',
  'signin.error.required': 'Fill in this field.',
  'signin.error.noBackup': 'This account has no recovery data on {instance}. It was created before recovery existed, and its browser has not been online since. Open it there first.',
  'signin.error.noBackupState': 'This account has no backup to recover from on {instance}. Sign in on a device that still holds this account and open dilla there; it repairs the backup. Then try again.',
  'signin.error.wrongKey': 'This is not the recovery key of this account. Check every character.',
  'signin.error.keyLength': 'A recovery key has 52 characters.',
  'signin.error.deviceCap': 'This account already has as many devices as {instance} allows. Remove one in Settings on another device first.',
  'signin.error.tooMany': 'Too many sign-in attempts. Try again in {seconds} s.',
  'signin.error.listRace': 'The account’s devices changed while you were signing in. Sign in again.',
  'signin.error.evicted': 'Someone else is signing in to this account. Change your password from a device you still have, or ask the operator.',
  'signin.error.network': 'The connection dropped. Check it and try again.',
  'signin.error.other': 'Signing in did not work ({code}). Try again.',
  'shell.skip': 'skip to messages',
  'shell.rail.label': 'servers',
  'shell.rail.join': 'join a server',
  'shell.channels.label': 'channels',
  'shell.channels.loading': 'loading channels…',
  'shell.channels.empty': 'no channels you can see',
  'shell.sidebar.loadError': 'This server did not load ({code}).',
  'shell.sidebar.retry': 'try again',
  'shell.noServer.title': 'You are not in a server yet',
  'shell.noServer.body': 'Ask a friend for a server invite, then join with it here.',
  'shell.noServer.action': 'Join a server',
  'shell.noChannel.title': 'No channels here yet',
  'shell.noChannel.body': 'This server has no channels you can see.',
  'shell.unsupported.title': 'This channel does not open here yet',
  'shell.unsupported.voice': 'Voice channels arrive in a later version of the web client.',
  'shell.unsupported.readable': 'Channels this server can read arrive in a later version of the web client.',
  'shell.unsupported.other': 'This kind of channel arrives in a later version of the web client.',
  'shell.readable': 'Readable by this server',
  'shell.log.label': 'messages in #{channel}',
  'shell.log.loading': 'loading messages…',
  'shell.log.empty': 'nothing here yet. Messages sent before this browser joined are not shown.',
  'shell.log.earlier': 'load earlier',
  'shell.message.unknownAuthor': 'device {id}',
  'shell.message.pending': 'sending…',
  'shell.message.failed': 'not sent',
  'shell.message.cannotRead': 'This message could not be read on this device.',
  'shell.message.deleted': 'message deleted',
  'shell.message.retry': 'retry',
  'shell.message.discard': 'discard',
  'shell.composer.label': 'message #{channel}',
  'shell.composer.placeholder': 'message #{channel}',
  'shell.composer.send': 'send',
  'shell.composer.remaining': '{n} left',
  'shell.composer.over': '{n} bytes over the limit',
  'shell.composer.joining': 'joining this channel…',
  'shell.composer.resync': 'catching up with this channel…',
  'shell.composer.notMember': 'you cannot post in this channel and new messages will not arrive. Reload, or ask the host.',
  'shell.composer.unsupported': 'this channel does not open here yet',
  'shell.composer.openFailed': 'this channel did not open',
  'shell.openFailed.title': 'This channel did not open',
  'shell.openFailed.body': 'Something went wrong while opening it ({code}).',
  'shell.openFailed.action': 'try again',
  'shell.banner.offline': 'Connection lost. Reconnecting…',
  'shell.banner.clientTooOld': 'This server needs a newer client. Reload the page.',
  'shell.banner.commandError': 'That did not work ({code}). Try again, or reload the page.',
  'shell.banner.dismiss': 'dismiss',
  'shell.status.label': 'connection',
  'shell.status.node': 'node',
  'shell.status.link': 'link',
  'shell.status.gen': 'gen',
  'shell.status.online': 'online',
  'shell.status.connecting': 'connecting',
  'shell.status.offline': 'offline',
  'shell.status.unknown': '–',
  'shell.rail.settings': 'settings',
  'shell.tabs.label': 'sidebar',
  'shell.tabs.channels': 'channels',
  'shell.tabs.dms': 'direct messages',
  'shell.dms.label': 'direct messages',
  'shell.dms.empty': 'no direct messages yet',
  'shell.dms.new': 'message someone',
  'shell.dms.newTitle': 'Message someone',
  'shell.dms.newBody': 'Pick a member of this server.',
  'shell.dms.open': 'message',
  'shell.channels.rowLabel': '{name}, unread {unread}, mentions {mentions}',
  'shell.channels.rowLabelMuted': '{name}, muted, mentions {mentions}',
  'shell.rail.itemLabel': '{name}, unread {unread}, mentions {mentions}',
  'shell.dm.log': 'messages with {name}',
  'shell.dm.composer': 'message @{name}',
  'shell.status.devices': 'devices',
  'join.title': 'Join a server',
  'join.invite': 'Invite',
  'join.inviteHint': 'A server invite, as a code or a link.',
  'join.submit': 'Join',
  'join.joining': 'Joining…',
  'join.error.empty': 'Paste an invite first.',
  'join.error.invalid': 'This invite is expired, used up or unknown.',
  'join.error.notCommunity': 'This invite is for the instance, not for a server. Ask for a server invite.',
  'join.error.forbidden': 'This server does not let your account join.',
  'join.error.malformed': 'That is not an invite code.',
  'join.error.other': 'Could not join ({code}). Try again.',
  'settings.title': 'Settings',
  'settings.close': 'Close settings',
  'settings.nav.label': 'settings sections',
  'settings.nav.devices': 'devices',
  'settings.nav.notifications': 'notifications',
  'settings.nav.appearance': 'appearance',
  'devices.title': 'Devices',
  'devices.body': 'Every browser and app signed in to your account. Removing a device needs your recovery key.',
  'devices.thisBrowser': 'this browser',
  'devices.tier.web': 'browser',
  'devices.tier.native': 'app',
  'devices.lastSeen': 'last seen {when}',
  'devices.unlisted': 'not yet in the device list',
  'devices.revoked': 'removed',
  'devices.cap.one': 'one device',
  'devices.cap.other': '{n} devices',
  'devices.keyLabel': 'Recovery key',
  'devices.refresh': 'refresh',
  'devices.revoke': 'remove',
  'devices.signOut': 'sign out and remove this browser',
  'devices.forget': 'forget this browser',
  'devices.revokeTitle': 'Remove this device?',
  'devices.revokeBody': 'The device is signed out everywhere and leaves every conversation. Enter your recovery key to confirm.',
  'devices.removeUnlistedTitle': 'Remove this device?',
  'devices.removeUnlistedBody': 'This device signed in with your password but is not in the device list, so it cannot read anything. Removing it needs no recovery key.',
  'devices.signOutTitle': 'Sign out and remove this browser?',
  'devices.signOutBody': 'This browser is removed from your account and its data here is cleared. You can sign in again later with your password and recovery key. Enter the key to confirm.',
  'devices.forgetTitle': 'Forget this browser?',
  'devices.forgetBody': 'This clears dilla’s data from this browser and signs it out. The device stays in your account’s device list until you remove it from another device.',
  'devices.confirmRevoke': 'Remove',
  'devices.confirmSignOut': 'Sign out',
  'devices.confirmForget': 'Forget',
  'devices.working': 'Working…',
  'devices.error.wrongKey': 'This is not the recovery key of this account.',
  'devices.rootMismatch': 'The recovery data stored for this account on {instance} is not this account’s. The recovery key will not work until the operator resets it.',
  'settings.error.other': 'That did not work ({code}). Try again.',
  'notify.title': 'Notifications',
  'notify.body': 'Desktop notifications show while a dilla tab is open. Nothing is shown when every tab is closed.',
  'notify.permission.label': 'desktop notifications',
  'notify.permission.ask': 'turn on',
  'notify.permission.granted': 'on',
  'notify.permission.denied': 'Blocked in the browser. Allow notifications for this site in the browser’s settings.',
  'notify.permission.unsupported': 'This browser cannot show notifications.',
  'notify.default.label': 'notify me about',
  'notify.default.dmsMentions': 'direct messages and mentions',
  'notify.default.everything': 'every message',
  'notify.default.nothing': 'nothing',
  'notify.channels.title': 'Per channel',
  'notify.channels.body': 'Every channel and direct message. Rows left on default follow the choice above.',
  'notify.channel.all': 'all',
  'notify.channel.mentions': 'mentions',
  'notify.channel.nothing': 'nothing',
  'notify.channel.default': 'default',
  'notify.mute': 'mute',
  'notify.unmute': 'unmute',
  'notify.title.channel': '#{channel} · {server}',
  'notify.title.dm': '{sender}',
  'appearance.title': 'Appearance',
  'appearance.theme.label': 'theme',
  'appearance.theme.system': 'system',
  'appearance.theme.mesh': 'mesh',
  'appearance.theme.light': 'light',
  'appearance.theme.contrast': 'high contrast',
} as const;
