// Every user-visible string of @dilla/web. Keys are flat and dot-separated; {name} is a placeholder.
// Apostrophes are typographic (’). The copy lint (scripts/check-ui-copy.mjs) scans this file.
export const en = {
  'boot.loading.status': 'Starting dilla',
  'boot.unsupported.status': 'This window cannot keep dilla’s data',
  'boot.unsupported.detail': 'dilla needs storage that lasts. Private windows and some privacy settings turn it off. Open this address in a normal window.',
  'boot.otherTab.status': 'dilla is open in another tab',
  'boot.otherTab.detail': 'Use that tab, or close it. This tab takes over as soon as the other one closes.',
  'boot.storeLost.status': 'This browser can no longer open its saved data',
  'boot.storeLost.detail': 'The key that opens dilla’s storage in this browser is gone, so the account on this device cannot be used here. Resetting clears this browser so you can sign up again.',
  'boot.storeLost.action': 'Reset this browser',
  'boot.storeLost.confirmTitle': 'Reset this browser?',
  'boot.storeLost.confirmBody': 'This deletes dilla’s data for this site from this browser. It cannot be undone.',
  'boot.storeLost.confirmAction': 'Reset',
  'boot.resetting.status': 'Clearing this browser’s data',
  'boot.revoked.status': 'This browser was signed out',
  'boot.revoked.detail': 'Your account no longer accepts this browser. Ask the host if you did not expect this. To start over here, clear this site’s data in the browser’s settings.',
  'boot.error.status': 'dilla could not start',
  'boot.error.detail': 'Error {code}. Reload the page to try again.',
  'boot.error.action': 'Reload',
  'dialog.close': 'Close',
  'onboarding.step': 'Step {n} of 5',
  'onboarding.back': 'Back',
  'onboarding.next': 'Continue',
  'onboarding.connect.title': 'Join {instance}',
  'onboarding.connect.body': 'You need an invite from someone on {instance}. Paste it below.',
  'onboarding.connect.bodyOpen': '{instance} is open to new accounts. Paste an invite if you were given one.',
  'onboarding.connect.invite': 'Invite',
  'onboarding.connect.inviteOptional': 'Invite (optional)',
  'onboarding.connect.inviteHint': 'A code or a link, as you received it.',
  'onboarding.closed.title': '{instance} is not taking new accounts',
  'onboarding.closed.body': 'Ask the host of {instance} when sign-ups open again.',
  'onboarding.identity.title': 'Choose your name',
  'onboarding.identity.body': 'People on {instance} see these next to your messages.',
  'onboarding.identity.username': 'Username',
  'onboarding.identity.usernameHint': '3 to 32 characters: a–z, 0–9, dot, underscore or hyphen.',
  'onboarding.identity.display': 'Display name (optional)',
  'onboarding.identity.displayHint': 'Up to 64 characters. Your username is shown when this is empty.',
  'onboarding.identity.password': 'Password',
  'onboarding.identity.passwordHint': 'At least 8 characters.',
  'onboarding.keys.title': 'Your recovery key',
  'onboarding.keys.body': 'This key is shown once and is kept nowhere. Write it down or print it, and keep it away from this computer.',
  'onboarding.keys.loss': 'Getting an account back with this key is not available in this version. Until it is, your account lives only in this browser: if this browser loses its data, the account and its history are gone, and the host cannot bring them back. Keep the key for when recovery arrives.',
  'onboarding.keys.label': 'Recovery key',
  'onboarding.keys.acknowledge': 'I have written down or printed my recovery key',
  'onboarding.keys.ackHint': 'Tick the box to continue.',
  'onboarding.keys.print': 'Print',
  'onboarding.keys.preparing': 'Making your keys',
  'onboarding.browser.title': 'What this browser keeps',
  'onboarding.browser.device': 'This browser now holds the key of this device, in its storage for {instance}. The key never leaves this browser.',
  'onboarding.browser.clear': 'Clearing this site’s data removes the key and the messages kept here, and this browser stops being your device.',
  'onboarding.browser.oneBrowser': 'This version cannot add a second browser or restore an account from the recovery key yet. For now, your account works in this browser only.',
  'onboarding.browser.private': 'A private window forgets all of this when it closes.',
  'onboarding.browser.submit': 'Create account',
  'onboarding.browser.submitting': 'Creating account…',
  'onboarding.browser.registering': 'Creating your account on {instance}…',
  'onboarding.done.title': 'You’re in',
  'onboarding.done.body': 'You are {username} on {instance}.',
  'onboarding.done.next': 'Open dilla',
  'onboarding.error.inviteRequired': 'Paste the invite you were given.',
  'onboarding.error.inviteInvalid': 'This invite is expired, used up or unknown. Ask for a new one.',
  'onboarding.error.usernameRule': 'Use 3 to 32 characters: a–z, 0–9, dot, underscore or hyphen, with no dot at the start or end.',
  'onboarding.error.usernameTaken': 'That username is taken. Try another.',
  'onboarding.error.displayLength': 'Use at most 64 characters.',
  'onboarding.error.detailsRefused': '{instance} did not accept these details. Check the username and the display name.',
  'onboarding.error.passwordShort': 'Use at least 8 characters.',
  'onboarding.error.rateLimited': 'Too many attempts from this network. Try again in {seconds} s.',
  'onboarding.error.rateLimitedNoWait': 'Too many attempts from this network. Wait a few minutes, then try again.',
  'onboarding.error.network': 'The connection dropped while creating your account. Reload the page to finish.',
  'onboarding.error.reload': 'Reload',
  'onboarding.error.other': 'The account could not be created ({code}). Try again.',
} as const;
