package gateway

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/fxamacker/cbor/v2"

	"github.com/jonasthim/dilla/internal/cborx"
	"github.com/jonasthim/dilla/internal/id"
)

// The committed corpus, generated by packages/protocol-vectors (protocol/vectors/frames.json).
type framesVectors struct {
	Version int `json:"version"`
	Cases   []struct {
		Name    string `json:"name"`
		Op      uint64 `json:"op"`
		N       uint64 `json:"n"`
		GroupID string `json:"group_id"` // 32 hex, or "" for null
		Payload string `json:"payload"`  // hex of the payload array alone
		Frame   string `json:"frame"`    // hex of the whole four-element frame
	} `json:"cases"`
	Rejects []struct {
		Name  string `json:"name"`
		Frame string `json:"frame"`
		Code  string `json:"code"`
	} `json:"rejects"`
}

func loadFrameVectors(t *testing.T) framesVectors {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "..", "protocol", "vectors", "frames.json"))
	if err != nil {
		t.Fatalf("frames.json: %v", err)
	}
	var v framesVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("frames.json: %v", err)
	}
	if len(v.Cases) == 0 || len(v.Rejects) == 0 {
		t.Fatal("frames.json carries no cases or no rejects")
	}
	return v
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex %q: %v", s, err)
	}
	return b
}

// decodeServerFrameForTest reads element 0 and element 1 of any frame, in either direction.
// Decode itself refuses server opcodes from a client, which is what the read path wants; these
// tests need to look at what the encoder produced.
func decodeServerFrameForTest(b []byte) (Inbound, error) {
	var elems []cbor.RawMessage
	if err := cborx.Unmarshal(b, &elems); err != nil {
		return Inbound{}, err
	}
	if len(elems) != 4 {
		return Inbound{}, errors.New("frame is not four elements")
	}
	op, err := rawUint(elems[0])
	if err != nil {
		return Inbound{}, err
	}
	n, err := rawUint(elems[1])
	if err != nil {
		return Inbound{}, err
	}
	return Inbound{Op: Op(op), CID: n}, nil
}

// Every accept case encodes to exactly the committed bytes: one encoder, three languages.
func TestEveryOpcodeEncodesToTheCommittedFrame(t *testing.T) {
	v := loadFrameVectors(t)
	for _, c := range v.Cases {
		t.Run(c.Name, func(t *testing.T) {
			var gid *id.ID
			if c.GroupID != "" {
				parsed, err := id.Parse(c.GroupID)
				if err != nil {
					t.Fatalf("group_id: %v", err)
				}
				gid = &parsed
			}
			// Encode forces n = 0 for a frame whose Replay is false, so the corpus's non-zero
			// n cases must be built with Replay set: identify, resume, ready, resumed,
			// heartbeat, subscribe, unsubscribe, all six DS frames, message.plain and
			// interaction all carry n != 0.
			got, err := Encode(Frame{
				Op:      Op(c.Op),
				GroupID: gid,
				Payload: cbor.RawMessage(mustHex(t, c.Payload)),
				Replay:  c.N != 0,
			}, c.N)
			if err != nil {
				t.Fatalf("Encode: %v", err)
			}
			if want := mustHex(t, c.Frame); hex.EncodeToString(got) != hex.EncodeToString(want) {
				t.Fatalf("frame\n got %x\nwant %x", got, want)
			}
		})
	}
}

// The other half of the same rule: a frame the producer did not mark replayable is stamped n = 0
// whatever n is passed, so an ephemeral frame can never consume a replay sequence.
func TestANonReplayableFrameIsAlwaysStampedZero(t *testing.T) {
	p, err := PresencePayload(id.New(), 1, 1758659000, "")
	if err != nil {
		t.Fatalf("payload: %v", err)
	}
	b, err := Encode(Frame{Op: OpPresence, Payload: p}, 99)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	in, err := decodeServerFrameForTest(b)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if in.CID != 0 {
		t.Fatalf("n = %d for a Replay:false frame, want 0", in.CID)
	}
}

// opSpec.replayable is the catalogue's own record of which server frames consume a replay
// sequence, and the committed corpus is the other statement of the same fact. They must agree, or
// one of the two is wrong and a client's resume replays the wrong set.
func TestTheCatalogueAndTheCorpusAgreeOnWhichServerFramesAreReplayable(t *testing.T) {
	v := loadFrameVectors(t)
	for _, c := range v.Cases {
		op := Op(c.Op)
		spec := opSpecs[op]
		if spec.fromClient {
			continue // n is the client's correlation id, not a replay sequence
		}
		if want := spec.replayable; (c.N != 0) != want {
			t.Errorf("%s: corpus n = %d but opSpecs[%d].replayable = %v", c.Name, c.N, op, want)
		}
	}
}

// The same rule for the payload's shape. `Decode` only ever checks `spec.elements` on a CLIENT
// frame, so nothing else in this package notices when a server frame's catalogue entry and the
// committed corpus drift apart — and the corpus is what a second implementation is written
// against. `resumed` gaining its third element (the rotated resume_token) is exactly the change
// that would have slipped through in one language only.
func TestTheCatalogueAndTheCorpusAgreeOnEveryPayloadElementCount(t *testing.T) {
	v := loadFrameVectors(t)
	for _, c := range v.Cases {
		t.Run(c.Name, func(t *testing.T) {
			var elems []cbor.RawMessage
			if err := cborx.Unmarshal(mustHex(t, c.Payload), &elems); err != nil {
				t.Fatalf("payload: %v", err)
			}
			if want := opSpecs[Op(c.Op)].elements; len(elems) != want {
				t.Fatalf("corpus payload has %d elements but opSpecs[%d].elements = %d",
					len(elems), c.Op, want)
			}
		})
	}
}

// Every client-to-server case decodes back to the same opcode, correlation id and group.
func TestClientFramesDecodeBackToTheirFields(t *testing.T) {
	v := loadFrameVectors(t)
	for _, c := range v.Cases {
		if !isClientOp(Op(c.Op)) {
			continue
		}
		t.Run(c.Name, func(t *testing.T) {
			in, err := Decode(mustHex(t, c.Frame), 16384)
			if err != nil {
				t.Fatalf("Decode: %v", err)
			}
			if in.Op != Op(c.Op) {
				t.Errorf("Op = %d, want %d", in.Op, c.Op)
			}
			if in.CID != c.N {
				t.Errorf("CID = %d, want %d", in.CID, c.N)
			}
			if (in.GroupID == nil) != (c.GroupID == "") {
				t.Errorf("GroupID = %v, want %q", in.GroupID, c.GroupID)
			}
		})
	}
}

// The reject corpus: each entry names the E_FRAME_* code the decoder must produce.
func TestTheRejectCorpusIsRefusedWithTheNamedCode(t *testing.T) {
	v := loadFrameVectors(t)
	for _, r := range v.Rejects {
		t.Run(r.Name, func(t *testing.T) {
			_, err := Decode(mustHex(t, r.Frame), 16384)
			if err == nil {
				t.Fatalf("%s was accepted", r.Name)
			}
			var fe *FrameError
			if !errors.As(err, &fe) {
				t.Fatalf("got %v, want a *FrameError", err)
			}
			if fe.Code != r.Code {
				t.Fatalf("code = %s, want %s", fe.Code, r.Code)
			}
		})
	}
}

func TestAFrameOverTheReadLimitIsEFrameLimit(t *testing.T) {
	payload, err := cborx.Marshal([]any{make([]byte, 64)})
	if err != nil {
		t.Fatalf("payload: %v", err)
	}
	frame, err := Encode(Frame{Op: OpSubscribe, Payload: payload}, 1)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	var fe *FrameError
	if _, err := Decode(frame, len(frame)-1); !errors.As(err, &fe) || fe.Code != "E_FRAME_LIMIT" {
		t.Fatalf("got %v, want E_FRAME_LIMIT", err)
	}
	if _, err := Decode(frame, len(frame)); err != nil {
		t.Fatalf("a frame of exactly the limit must be accepted: %v", err)
	}
}

func TestAnUnknownOpcodeIsAHardError(t *testing.T) {
	payload, err := cborx.Marshal([]any{})
	if err != nil {
		t.Fatalf("payload: %v", err)
	}
	frame, err := Encode(Frame{Op: Op(63), Payload: payload}, 1)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	var fe *FrameError
	if _, err := Decode(frame, 16384); !errors.As(err, &fe) || fe.Code != "E_FRAME_TYPE" {
		t.Fatalf("got %v, want E_FRAME_TYPE — an unknown opcode is never ignored", err)
	}
	if fe.Close != CloseDecode {
		t.Fatalf("close code = %d, want 4002", fe.Close)
	}
}

// An opcode is a uint8 on this side. 256+6 must not wrap to 6 and be served as a heartbeat: it is
// an unknown opcode, exactly like 63.
func TestAnOpcodeThatOverflowsAByteIsAnUnknownOpcode(t *testing.T) {
	payload, err := cborx.Marshal([]any{uint64(1), uint64(2)})
	if err != nil {
		t.Fatalf("payload: %v", err)
	}
	frame, err := cborx.MarshalFrame(uint64(OpHeartbeat)+256, 1, nil, payload)
	if err != nil {
		t.Fatalf("MarshalFrame: %v", err)
	}
	var fe *FrameError
	if _, err := Decode(frame, 16384); !errors.As(err, &fe) || fe.Code != "E_FRAME_TYPE" {
		t.Fatalf("got %v, want E_FRAME_TYPE — opcode 262 is not heartbeat (6)", err)
	}
}
